/**
 * GENERATED by apps/mobile/scripts/generate-conversation-visual.mjs — do not edit by hand.
 *
 * W1A-01: the Conversation surface's visual constants, resolved from the frozen canonical sources and
 * never copied from prose. Regenerate after any source changes; the W1A-01 contract fails on drift.
 *
 * Sources (sha256):
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/src/tokens.mjs  435f4dafa44be9045b07669bdb485385b7d51b07ea08713031b2b94a6de21911
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/base/b4r.semantic.tokens.json  2ac7c739091446b2c4bba53cd9058ac86cac9b877c1c975cb0a781f6a490c441
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/base/c3.material.tokens.json  bb841aa9ce194102da7a2567fd84fc95e9075e6e13805efc0c9698c4c6465928
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/base/d2r.illumination.tokens.json  2d32bf8987016d7d21b226b4c9111b5e38f8786397badc37dd4cd9655cf230b4
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/base/e1.interaction.tokens.json  6be98e6d270db5d8b2313165de51ec75b49a923faf4b16a833ad9db84106cbce
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/base/f1.accessibility.tokens.json  dd47c43cb72eb306f2b701a883ce7c48e280f4d8bcfbf00664d0abca681e35cc
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/base/f2.appearance.tokens.json  513f5dfa419e1a5b7c5729e7b062ea282c32df0a3284e73596bc10b9e652cadc
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/base/g11.utterance.alias.tokens.json  bdc05957547f28786ff0d3388b5e4c4f0ce8bfafbd548e8d763b525d01fd033b
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/dark/b4r.dark.tokens.json  4641f1bcbf1c12473d74ddaa77a39e5bea4314d47753d40bfded0b2e347e1112
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/dark/c3.dark.material.tokens.json  55c56ab78358d8a3353a8794887e31a9194578ab2731f4659d7c6de42df9a367
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/dark/d2r.dark.illumination.tokens.json  688bad2f79ac7b22fdefe4b94f4c07a08b5c249bdcb84327e9df2ff82a565157
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/dark/e1.dark.interaction.tokens.json  397c5e89d534baffd5863136656ded7d8c3b31ef5ec2c0ba0899bc40b5947252
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/dark/f1.dark.accessibility.tokens.json  3d2fbcca824255c5da8ee234f572f35bad68f143c47424ccc0057ad7e7407176
 *   docs/design/canonical-artifacts/product-proofs/g3/g3.2/source/vendor/tokens/contrast/f1.dark.increased.tokens.json  5b27d13790e0ce051822c226aa8f3c11cac04467156210f9469c229f391c8f2a
 *   docs/design/p2-iconography/QANDEEL_P2-A_FINAL_ICONOGRAPHY_INTEGRATED_VISUAL_PROOF/source/src/sig.mjs  960ecd84edd75da91ee6a7c391504bb0ee4f15b92c8bea120847289caca4dde2
 *   docs/design/p2-iconography/QANDEEL_P2-A_FINAL_ICONOGRAPHY_INTEGRATED_VISUAL_PROOF/source/src/utility.mjs  5ab7bad45019e33d85f455b9c3f19e403aaf1d591a8ebee344182ab3017c5df9
 *   docs/design/p2-iconography/QANDEEL_P2-A_FINAL_ICONOGRAPHY_INTEGRATED_VISUAL_PROOF/source/vendor/utility/utility-glyphs.json  54d059f63b92988ae06e7e37a44eee24e71775e76206b4d0f0f1b9c1ffbfea23
 *   docs/design/canonical-artifacts/typography/i-08b3.0-e3/tools/system.json  c31dd4a27603f55220a9a2c55d23ed752bc3490a30bced80671f00530b183ced
 */

export const CANONICAL_VISUAL = {
  "palette": {
    "standard": {
      "world": "#101010",
      "field": "#181818",
      "utterance": "#181818",
      "primary": "#d8d5ca",
      "secondary": "#afaca3",
      "tertiary": "#8b8982",
      "restInk": "#8b8982",
      "pressedInk": "#d8d5ca",
      "pressedPresence": 0.1,
      "focusIndicator": "#d8d5ca",
      "focusCompanion": "#101010",
      "focusThickness": 2,
      "focusCompanionThickness": 1,
      "focusOffset": 2,
      "error": "#fe907e",
      "routes": {
        "world": "qandeel.world.fill → qandeel.expression.world",
        "field": "qandeel.role.field.fill → qandeel.surface.functional → qandeel.expression.surface",
        "utterance": "qandeel.role.utterance.fill → qandeel.surface.functional → qandeel.expression.surface",
        "restInk": "qandeel.state.rest.ink → qandeel.control.functional → qandeel.content.tertiary → qandeel.expression.content.tertiary",
        "error": "qandeel.status.error.ink → qandeel.expression.status.error"
      }
    },
    "increased": {
      "world": "#101010",
      "field": "#181818",
      "utterance": "#181818",
      "primary": "#d8d5ca",
      "secondary": "#afaca3",
      "tertiary": "#8b8982",
      "restInk": "#afaca3",
      "pressedInk": "#d8d5ca",
      "pressedPresence": 0.1,
      "focusIndicator": "#d8d5ca",
      "focusCompanion": "#101010",
      "focusThickness": 3,
      "focusCompanionThickness": 1,
      "focusOffset": 2,
      "error": "#fe907e",
      "routes": {
        "world": "qandeel.world.fill → qandeel.expression.world",
        "field": "qandeel.role.field.fill → qandeel.surface.functional → qandeel.expression.surface",
        "utterance": "qandeel.role.utterance.fill → qandeel.surface.functional → qandeel.expression.surface",
        "restInk": "qandeel.state.rest.ink → qandeel.control.functional → qandeel.content.secondary → qandeel.expression.content.secondary",
        "error": "qandeel.status.error.ink → qandeel.expression.status.error"
      }
    }
  },
  "glyphs": {
    "send": {
      "size": 24,
      "mirrorsInRtl": false,
      "strokes": [
        {
          "d": "M12 19.4V5.2M6.6 10.4 12 5l5.4 5.4",
          "strokeWidth": 1.6
        }
      ],
      "dots": []
    },
    "depth": {
      "size": 22,
      "mirrorsInRtl": false,
      "strokes": [
        {
          "d": "M13.943 19.76A8 8 0 1 1 19.76 13.943",
          "strokeWidth": 1.66
        }
      ],
      "dots": [
        {
          "cx": 13.9,
          "cy": 13.9,
          "r": 2.05
        }
      ]
    },
    "back": {
      "size": 22,
      "mirrorsInRtl": true,
      "flipForLtr": true,
      "strokes": [
        {
          "d": "M9.00005 6C9.00005 6 15 10.4189 15 12C15 13.5812 9 18 9 18",
          "strokeWidth": 1.66
        }
      ],
      "dots": []
    }
  },
  "type": {
    "body": {
      "size": 17,
      "leading": 30,
      "weight": 400
    },
    "supporting": {
      "size": 15,
      "leading": 25,
      "weight": 400
    },
    "action": {
      "size": 14,
      "leading": 23,
      "weight": 500
    },
    "metadata": {
      "size": 12,
      "leading": 20,
      "weight": 400
    }
  },
  "crossfadeMs": 200,
  "crossfadeReducedMotionMs": 0
} as const;
