/**
 * A3-01 — Activity & Attention Core + In-App Production Integration: the static contract.
 *
 * It guards, against the repository as written (Task Contract §22 "Root contract"):
 *   1. I-08N-01 and P3 are CONSUMED, not rewritten: their records and the P3-A sources are byte-unchanged, and the two P3
 *      glyphs are generated from P3-A (`--check`), on P2's unchanged `sig.mjs`, through the P2 / VPORT-02 mechanism;
 *   2. no WebView, no P3-A proof runtime and no runtime icon package entered production;
 *   3. no native Push, device token, provider or OS notification code slipped into A3-01 (A3-02 owns it);
 *   4. Activity is not a World: the depth pair is still exactly Conversation ↔ Analysis, and no Global Switcher exists;
 *   5. no Activity entry, no strip and no call-safe strip in the Analysis; the entry is composed ONCE, at the START edge;
 *   6. no global raw count anywhere: the API's global indicator and the device's decoder are presence only;
 *   7. ONE Direct Entry contract, revalidated at open, typed future destinations failing closed;
 *   8. HIM / HSE "attention" is not the Activity store: nothing in A3-01 reads it;
 *   9. "Reduce" is no score, class rule or threshold, and the absent Proactive Gate fails closed;
 *  10. copy authority: every APPROVED / CANON string is byte-equal to the pinned P4-C3 registry; no FIXTURE sentence is
 *      Product copy; every unapproved row lives in the ONE Product Copy Gate;
 *  11. A3-02 is the named owner of native Push, and Stage 3 is not claimed closed;
 *  12. registration.
 */
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const root = new URL('../', import.meta.url);
const read = (path) => readFileSync(new URL(path, root), 'utf8').replace(/\r\n/gu, '\n');
const stripComments = (text) => text.replace(/\/\*[\s\S]*?\*\//gu, '').replace(/^\s*\/\/.*$/gmu, '').replace(/\s\/\/ .*$/gmu, '');
const code = (path) => stripComments(read(path));
const gitBlob = (path) => execFileSync('git', ['hash-object', new URL(path, root).pathname.replace(/^\/([A-Za-z]:)/u, '$1')], { encoding: 'utf8' }).trim();

function sourcesUnder(dir) {
  const out = [];
  const walk = (relative) => {
    for (const name of readdirSync(new URL(relative, root))) {
      const path = `${relative}/${name}`;
      if (statSync(new URL(path, root)).isDirectory()) {
        if (!['__tests__', '__fixtures__', '__validation__'].includes(name)) walk(path);
      } else if (/\.(ts|tsx)$/u.test(name) && !/\.spec\.ts$/u.test(name)) {
        out.push(path);
      }
    }
  };
  walk(dir);
  return out;
}

const MOBILE = 'apps/mobile/src';
const ACTIVITY = `${MOBILE}/activity`;
const API = 'apps/api/src/activity';
const MIGRATION = 'database/migrations/0136_activity_attention_core_v1.sql';
const RECORD = 'docs/e2e/QANDEEL_A3_01_ACTIVITY_ATTENTION_INAPP_PRODUCTION_IMPLEMENTATION_RECORD_v1.md';
const BACKLOG = 'docs/qandeel-canonical-backlog-v1.md';
const P3A = 'docs/design/p3-notifications/QANDEEL_P3-A_NOTIFICATION_ACTIVITY_INTEGRATED_VISUAL_PROOF';
const REGISTRY = 'docs/design/p4-residual/QANDEEL_P4-C3_RESIDUAL_VISUAL_COPY_PROOF/data/COPY_REGISTRY.json';
const mobileProduction = sourcesUnder(MOBILE);
const apiProduction = sourcesUnder('apps/api/src');

test('1 — I-08N-01 and P3 are consumed, not rewritten; the two P3 glyphs are generated from P3-A on P2', () => {
  const i08n = read('docs/canonical-authority/final-product-experience/i-08n/QANDEEL_I-08N-01_FINAL_CLOSURE_PACKAGE.md');
  assert.match(i08n, /\*\*Status:\*\* `CLOSED \/ NOTIFICATION & PROACTIVE ATTENTION PRODUCT CONTRACT FROZEN`/u);
  const p3 = read('docs/qandeel-p3-notification-activity-final-realization-canonical-closure.md');
  assert.match(p3, /> \*\*Status: `P3 — CLOSED \/ FROZEN — NOTIFICATION & ACTIVITY FINAL PRODUCT REALIZATION`\*\*/u);
  const generated = spawnSync(process.execPath, [new URL('apps/mobile/scripts/generate-p3-production.mjs', root).pathname.replace(/^\/([A-Za-z]:)/u, '$1'), '--check'], { encoding: 'utf8' });
  assert.equal(generated.status, 0, `the P3 glyph geometry is current: ${generated.stderr}`);
  const module = read(`${MOBILE}/iconography/p3-production.generated.ts`);
  assert.match(module, /GENERATED by apps\/mobile\/scripts\/generate-p3-production\.mjs/u);
  assert.deepEqual([...module.matchAll(/^ {2}"(\w+)": \{/gmu)].map((m) => m[1]), ['ledger', 'link'], 'only Open Ledger and Open Link are ported');
  const generator = read('apps/mobile/scripts/generate-p3-production.mjs');
  assert.match(generator, /ACTIVITY_ACCEPTED !== 'ledger'/u);
  assert.match(generator, /INTRO_ACCEPTED !== 'link'/u);
  assert.match(generator, /sha\(P3_SIG\) !== sha\(P2_SIG\)/u, 'P3 applies P2 and does not extend it');
  assert.doesNotMatch(stripComments(generator), /P3G\.(bell|door)|WITHDRAWN\./u, 'comparison drawings are never executed');
  // The P3-A package is evidence: nothing in it is edited by A3-01. Pinned by content (every path and its bytes, as at
  // the baseline 34ea439), not by asking git, so the claim also holds in the forward-safety mirror, which is no repository.
  const files = [];
  const walk = (dir) => {
    for (const entry of readdirSync(new URL(dir, root), { withFileTypes: true })) {
      if (entry.isDirectory()) walk(`${dir}/${entry.name}`);
      else files.push(`${dir}/${entry.name}`);
    }
  };
  walk(P3A);
  const digest = createHash('sha256');
  for (const file of files.sort()) {
    digest.update(`${file.slice(P3A.length + 1)}\0`);
    digest.update(`${createHash('sha256').update(readFileSync(new URL(file, root))).digest('hex')}\n`);
  }
  assert.equal(files.length, 140, 'the P3-A package has exactly the files it had at the baseline');
  assert.equal(digest.digest('hex'), 'ef10ca6e1a949e6193f023f514f4e6dd3e03b9f664b408a3a84a685e8fa7eeee', 'the P3-A package bytes are untouched');
});

test('2 — no WebView, no proof runtime, no runtime icon package in production', () => {
  for (const file of [...mobileProduction, ...apiProduction]) {
    const text = code(file);
    assert.doesNotMatch(text, /p3-notifications|P3-A_NOTIFICATION|prototype\/|react-native-webview|WebView|<iframe|react-native-svg|hugeicons|lucide/u, `${file} imports no proof runtime and no icon package`);
  }
  const pkg = JSON.parse(read('apps/mobile/package.json'));
  const deps = Object.keys({ ...pkg.dependencies, ...pkg.devDependencies });
  assert.deepEqual(deps.filter((name) => /webview|svg|hugeicons|lucide|vector-icons|notification|firebase|push/iu.test(name)), []);
  // The proof-context field `view` and the proof boolean `reduceEligible` are not production schema (P3 §12.1, §18).
  for (const file of [...sourcesUnder(ACTIVITY), ...sourcesUnder(API)]) assert.doesNotMatch(code(file), /reduceEligible|\bview\s*===\s*'analysis'/u, file);
});

test('3 — no native Push, device token, provider or OS notification code in A3-01 (A3-02 owns it)', () => {
  const forbidden = /expo-notifications|firebase|@react-native-firebase|\bapns\b|\bfcm\b|device_?token|push_?token|getDevicePushToken|requestPermissionsAsync|setBadgeCount|notification_?channel/iu;
  for (const file of [...mobileProduction, ...apiProduction]) assert.doesNotMatch(code(file), forbidden, `${file} has no Push / OS notification code`);
  assert.doesNotMatch(stripComments(read(MIGRATION)).replace(/--.*$/gmu, ''), forbidden, 'no device / token column or table');
  const app = JSON.parse(read('apps/mobile/app.json'));
  assert.doesNotMatch(JSON.stringify(app), /notification|POST_NOTIFICATIONS|aps-environment/iu, 'no permission, entitlement or plugin for notifications');
});

test('4 — Activity is not a World: the depth pair is unchanged and no Global Switcher destination exists', () => {
  const depth = read(`${MOBILE}/integration/composition/DepthComposition.tsx`);
  assert.match(depth, /export type WorldDepth = 'CONVERSATION' \| 'ANALYSIS';/u);
  assert.doesNotMatch(code(`${MOBILE}/integration/composition/DepthComposition.tsx`), /setDepth\('ACTIVITY'\)|cross\('ACTIVITY'\)/u);
  assert.deepEqual(readdirSync(new URL(`${MOBILE}/app`, root)).sort(), ['_layout.tsx', 'index.tsx'], 'no route was added');
  for (const file of sourcesUnder(ACTIVITY)) assert.doesNotMatch(code(file), /switcher|navMine|navShared|navPublic|expo-router|router\.push/iu, `${file} is no World / switcher / route`);
});

test('5 — no Activity entry or strip in the Analysis; the entry is composed once, at the START edge', () => {
  for (const file of [`${MOBILE}/conversation/AnalysisReturnBar.tsx`, `${MOBILE}/integration/composition/LivingAnalysisMap.tsx`]) {
    assert.doesNotMatch(code(file), /ActivityEntry|AttentionStrip|CallSafeStrip|qandeel-activity/u, `${file} carries no Activity entry or strip`);
  }
  const depth = code(`${MOBILE}/integration/composition/DepthComposition.tsx`);
  assert.equal((depth.match(/<ActivityEntry\b/gu) ?? []).length, 1, 'one entry');
  assert.match(depth, /chromeStart=\{onSignOut === undefined \? null : \(\n\s*<ActivityEntry /u, 'handed to the non-Analysis upper chrome');
  assert.match(depth, /strip !== null && strip\.form === 'ORDINARY' && depth === 'CONVERSATION'/u, 'the strip host never mounts at the Analysis depth');
  assert.match(depth, /activityShown && depth === 'CONVERSATION' && onSignOut !== undefined \?/u, 'Activity is never reached from the Analysis');
  const surface = read(`${MOBILE}/conversation/ConversationSurface.tsx`);
  const chrome = surface.slice(surface.indexOf('minHeight: insets.top + HEADER_MIN_HEIGHT'), surface.indexOf('onOpenSettings === undefined ? null'));
  assert.equal((chrome.match(/<Control\b/gu) ?? []).length, 1, 'the chrome still draws exactly one control of its own');
  assert.match(chrome, /chromeStart === null \? null : <View testID="qandeel-chrome-start">\{chromeStart\}<\/View>/u);
  assert.match(code(`${ACTIVITY}/presentation.ts`), /if \(context\.surface === 'ANALYSIS'\) return \{ kind: 'WAIT' \};/u, 'ordinary attention waits inside the Analysis');
  // The call-safe strip is built, not mounted: no call authority exists (QAN-BL-VOICE-01).
  for (const file of mobileProduction.filter((f) => !f.endsWith('CallSafeStrip.tsx'))) assert.doesNotMatch(code(file), /<CallSafeStrip\b/u, `${file} mounts no call-safe strip`);
  assert.match(code(`${ACTIVITY}/call-truth.ts`), /PRODUCTION_CALL_TRUTH: CallTruth = Object\.freeze\(\{ kind: 'NO_CALL_KNOWN' \}\)/u);
  assert.doesNotMatch(mobileProduction.filter((f) => !f.endsWith('call-truth.ts') && !f.endsWith('presentation.ts')).map(code).join('\n'), /kind: 'ACTIVE'/u, 'nothing in production fabricates an active call');
});

test('6 — no global raw count: presence only, server and device', () => {
  const types = code(`${API}/activity.types.ts`);
  const global = types.slice(types.indexOf('export interface ActivityIndicatorsView'), types.indexOf('readonly categories'));
  assert.match(global, /readonly present: boolean;/u);
  assert.doesNotMatch(global, /count|total|unread/iu, 'the global indicator has no count field');
  assert.match(code(`${API}/activity.service.ts`), /present: marked\.length > 0,/u, 'derived from eligible attention items, never a sum (D45)');
  assert.match(types, /INTRODUCTIONS: \{ readonly present: boolean \};/u, 'Introductions: presence only (D48)');
  const wire = code(`${MOBILE}/runtime-entry/activity-api.ts`);
  assert.match(wire, /hasExactly\(body, \['present', 'categories', 'interruptions'\]\)/u, 'a global count is not an answer');
  for (const file of sourcesUnder(ACTIVITY)) assert.doesNotMatch(code(file), /unreadCount|badgeCount|totalCount/u, file);
});

test('7 — ONE Direct Entry contract, revalidated at open; Stage 4–8 destinations typed and failing closed', () => {
  const types = code(`${API}/activity.types.ts`);
  assert.match(types, /export const EXECUTABLE_DESTINATIONS: ReadonlySet<EntryDestination> = new Set\(\['PERSONAL_CONVERSATION', 'QANDEEL_UNDERSTANDING', 'GENERAL_SETTINGS'\]\);/u);
  const service = code(`${API}/activity.service.ts`);
  assert.match(service, /return \{ outcome: 'UNAVAILABLE', fallback: null \};/u, 'future destinations fail closed');
  assert.match(service, /if \(row\.outcome === 'STALE'\) return \{ outcome: 'STALE', fallback \};/u, 'no guessed replacement (D39)');
  const migration = read(MIGRATION);
  assert.match(migration, /activity_items_entry_check CHECK \(/u, 'no item can name a destination in another World (D43)');
  assert.equal((apiProduction.map(code).join('\n').match(/export const ENTRY_DESTINATIONS\b/gu) ?? []).length, 1, 'one descriptor');
  // Opening is attention only: the open command writes nothing but the item's attention.
  const open = migration.slice(migration.indexOf('CREATE FUNCTION activity_private.open_own_activity_item_v1'), migration.indexOf('CREATE FUNCTION activity_private.record_own_activity_strip_v1'));
  assert.deepEqual([...open.matchAll(/UPDATE (\S+)/gu)].map((m) => m[1]), ['public.activity_items'], 'opening touches no source table');
  assert.match(open, /SET attention = 'OPENED'/u);
});

test('8 — HIM / HSE attention is not the Activity store', () => {
  for (const file of [...sourcesUnder(API), ...sourcesUnder(ACTIVITY)]) assert.doesNotMatch(code(file), /human-model|hse-attention|him-decision|HseAttention|decision_attention/u, `${file} reads no human-model attention`);
  const sql = read(MIGRATION).split('\n').filter((line) => !line.trimStart().startsWith('--')).join('\n');
  assert.doesNotMatch(sql, /\bhse_|\bhim_|decision_attention|human_model/iu, 'the migration touches no human-model object');
  assert.doesNotMatch(sql, /shared_world_membership_episodes|public\.shared_worlds\b|public_experience|introduction_/u, 'and reads no Connected Worlds table (0075 §3)');
});

test('9 — "Reduce" is no score, class rule or threshold; the absent Proactive Gate fails closed', () => {
  const decision = code(`${API}/activity-decision.ts`);
  assert.match(decision, /export const PROACTIVE_GATE: ProactiveGateVerdict = 'ABSENT';/u);
  assert.match(decision, /if \(item\.kind === 'PROACTIVE' && \(input\.gate \?\? PROACTIVE_GATE\) === 'ABSENT'\) return 'PROACTIVE_GATE_ABSENT';/u);
  assert.doesNotMatch(decision, /score|weight|threshold|REDUCE'[^;]*interruption_class/iu, 'no number stands in for the Gate');
  assert.doesNotMatch(read(MIGRATION).replace(/--.*$/gmu, ''), /score|weight|threshold|importance|urgency/iu, 'no invented importance model');
});

test('10 — copy authority: APPROVED / CANON byte-equal to the pinned registry; no FIXTURE as Product copy; one Copy Gate', () => {
  const registry = JSON.parse(read(REGISTRY));
  assert.equal(gitBlob(REGISTRY), 'feaee4405d07db30bf7689257c866a7442bce927', 'the pinned P4-C3 registry P4-C4 ratified');
  const rows = new Map(registry.rows.map((row) => [row.k, row]));
  const copy = read(`${ACTIVITY}/copy.ts`);
  const cited = [...copy.matchAll(/\/\/ (?:APPROVED|CANON) — ((?:p3\.)?[\w.*]+)/gu)].map((m) => m[1]);
  assert.ok(cited.length >= 30, 'the copy module cites its registry keys');
  for (const key of cited) {
    const expand = key.endsWith('.*') ? registry.rows.filter((row) => row.k.startsWith(key.slice(0, -1))) : [rows.get(key)];
    for (const row of expand) {
      assert.ok(row, `${key} is a registry key`);
      assert.ok(['CANON', 'PROPOSED_FOR_PO_REVIEW'].includes(row.st), `${row.k} is CANON or P4-C4-ratified`);
      assert.ok(copy.includes(row.ar), `${row.k} Arabic is byte-equal: ${row.ar}`);
      assert.ok(copy.includes(row.en.replace(/'/gu, "\\'")) || copy.includes(row.en), `${row.k} English is byte-equal: ${row.en}`);
    }
  }
  const fixtures = registry.rows.filter((row) => row.st === 'FIXTURE_ONLY' || row.st === 'AUDIT_OWNED').flatMap((row) => [row.ar, row.en]).filter((text) => text && text !== '—' && text.length > 6);
  const production = [...sourcesUnder(ACTIVITY), `${MOBILE}/settings/NotificationsSection.tsx`].map(read).join('\n');
  for (const text of fixtures) assert.equal(production.includes(text), false, `FIXTURE / AUDIT_OWNED text is not Product copy: ${text}`);
  assert.match(copy, /export const ACTIVITY_COPY_GATE = Object\.freeze\(\{\n {2}status: '(PROPOSED — AWAITING PRODUCT OWNER APPROVAL|APPROVED BY THE PRODUCT OWNER[^']*)'/u, 'the one Copy Gate states its status');
});

test('11 — A3-02 is the named owner of native Push, and Stage 3 is not claimed closed', () => {
  const backlog = read(BACKLOG);
  assert.match(backlog, /\| `QAN-BL-NOTIF-01` \| [^|]+ \| `A3-02 — Native Push, Permission & Platform Delivery Integration` \| `HIGH` \| `DEFERRED — OWNED` \|/u);
  const record = read(RECORD);
  assert.match(record, /Orphan gaps = 0/u);
  assert.match(record, /DO NOT MERGE/u);
  assert.match(record, /A3-01 does not close Stage 3/u);
  // Read from the record, not the root locators: the forward-safety mirror carries only the source a contract may read.
  assert.match(record, /`A3-02` remains its named owner/u, 'A3-02 stays the remaining Stage-3 owner');
});

test('12 — registration', () => {
  const pkg = JSON.parse(read('package.json'));
  assert.equal(pkg.scripts['test:a3-01-activity-attention-inapp-contract'], 'node --test tests/a3-01-activity-attention-inapp-contract.test.mjs');
  assert.equal(pkg.scripts['verify:activity-attention-core:integration'], 'node --env-file-if-exists=.env database/verify-migration-0136.mjs');
  assert.match(read('.github/workflows/mobile-ci.yml'), /run: npm run test:a3-01-activity-attention-inapp-contract\}/u);
  assert.match(read('.github/workflows/api-ci.yml'), /run: npm run test:a3-01-activity-attention-inapp-contract\}/u);
  assert.match(read('.github/workflows/api-ci.yml'), /run: npm run verify:activity-attention-core:integration\n/u);
});
