import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

/**
 * VPORT-01 — Living Analysis World — Final Production Visual Port. The static guards.
 *
 * The port replaced the T-04 neutral placeholder paint with the frozen I-08B1 world. These guards keep
 * it that way and keep it honest: the world's values come from the closed sources by a deterministic
 * generator; the Map paints no placeholder, no literal palette of its own, no WebView and no HTML; the
 * visual owner reads no analytical quantity and draws no relation without a fact; and nothing visual is
 * an input to scene membership, placement, hit testing or accessibility.
 */

const root = new URL('../', import.meta.url);
const rootPath = fileURLToPath(root);
const read = (path) => readFileSync(new URL(path, root), 'utf8').replace(/\r\n/gu, '\n');
const stripComments = (text) => text.replace(/\/\*[\s\S]*?\*\//gu, '').replace(/\/\/[^\n]*/gu, '');

const I08B1 = 'docs/design/canonical-artifacts/living-analysis/i-08b1/wf-living-constellation.html';
const I08B1_SHA256 = '4dfd9d27d752c3a445168c0cc7067d71df4ada84bc61b806d12c8bb3202bc413';
const VISUAL_DIR = 'apps/mobile/src/map/visual';
const GENERATED = ['world-visual.generated.ts', 'world-field.generated.ts'];
// LA-VIS-01 (controlled re-anchor): the declared presentation palette joins the hand-written owner, under every rule below.
// LA-VIS-01 (final closure re-anchor): the mass material `world-mass.ts` joins it too, under every rule below.
const HAND_WRITTEN = ['WorldMarks.tsx', 'WorldStrata.tsx', 'index.ts', 'useWorldResponse.ts', 'world-presentation.ts', 'world-resolver.ts', 'world-chroma.ts', 'world-mass.ts'];

const visual = Object.fromEntries([...GENERATED, ...HAND_WRITTEN].map((file) => [file, read(`${VISUAL_DIR}/${file}`)]));
const visualCode = Object.fromEntries(HAND_WRITTEN.map((file) => [file, stripComments(visual[file])]));
// S5-03B Phase 1 (controlled re-anchor, after the Personal golden equivalence proof): MapCanvas remains the Personal
// owner of the Map's paint and delegates, verbatim, to the generic world composition in WorldCanvas.tsx; MapSurface
// delegates its presentation mechanics to useWorldSurface.ts. The world's rules are asserted on the owner TOGETHER WITH
// the seam its code now lives in; none is weakened.
const personalCanvasOwner = stripComments(read('apps/mobile/src/map/renderer/MapCanvas.tsx'));
const worldCanvas = stripComments(read('apps/mobile/src/map/renderer/WorldCanvas.tsx'));
const canvas = `${personalCanvasOwner}\n${worldCanvas}`;
// S5-03B R1 (controlled re-anchor): the world's expression is gathered by the one Living Analysis world view
// (`useWorldView` in WorldViewSurface.tsx, called in place by MapSurface), so it is asserted there too.
const surface = stripComments(read('apps/mobile/src/map/renderer/MapSurface.tsx')) + '\n' + stripComments(read('apps/mobile/src/map/renderer/WorldViewSurface.tsx')) + '\n' + stripComments(read('apps/mobile/src/map/renderer/useWorldSurface.ts'));

test('the closed I-08B1 source is untouched, and the generated world is current and reproducible', () => {
  const sha = createHash('sha256').update(readFileSync(new URL(I08B1, root))).digest('hex');
  assert.equal(sha, I08B1_SHA256, 'the canonical I-08B1 source is read-only');
  // Re-running the generator against the frozen sources reproduces both modules byte for byte.
  execFileSync(process.execPath, [join(rootPath, 'apps/mobile/scripts/generate-world-visual.mjs'), '--check'], { stdio: 'pipe' });
  for (const file of GENERATED) {
    const text = visual[file];
    assert.match(text, /^\/\*\*\n \* GENERATED by apps\/mobile\/scripts\/generate-world-visual\.mjs — do not edit by hand\./u, `${file} declares its generator and the no-hand-edit rule`);
    assert.match(text, new RegExp(`${I08B1.replace(/[.]/gu, '\\.')}  ${I08B1_SHA256}`, 'u'), `${file} names the canonical source and its exact hash`);
  }
});

test('the generator takes the world from the canonical source itself, never from prose', () => {
  const generator = read('apps/mobile/scripts/generate-world-visual.mjs');
  // The four canonical painters are EXECUTED, unmodified, against a recording context.
  for (const declaration of ["block('function dustTile(){')", "block('function sprite(hue,sat,light,profile){')", "block('function shadeSprite(){')", "block('function nodePath(ctx,k,x,y,r,rot){')", "block('const P={')"]) {
    assert.ok(generator.includes(declaration), `the generator lifts ${declaration} from the canonical file`);
  }
  // The distance schedule is copied expression for expression, and its flags are the shipped ones.
  assert.match(generator, /const SCHEDULE_KEYS = \['lod', 'map', 'mapA', 'far', 'atmo', 'cosmos'/u);
  assert.match(generator, /for \(const flag of \['let HIER=true;', 'let LODON=true;', 'let MAPON=true;', 'let FARCAL=true;'\]\) exactLine\(flag\);/u);
  // Tokens through F2 FINAL's own resolver.
  assert.match(generator, /f2r\.loadTokens\(\{ appearance: 'dark', contrast \}\)/u);
  const generated = visual['world-visual.generated.ts'];
  const html = read(I08B1);
  for (const [, key, expression] of generated.matchAll(/^ {2}S\.(\w+) = (.+);$/gmu)) {
    assert.ok(new RegExp(`^\\s*S\\.${key}\\s*=\\s*${expression.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')};`, 'mu').test(html), `S.${key} is the canonical expression`);
  }
});

test('the neutral placeholder world is gone, and no palette fork replaced it', () => {
  for (const placeholder of ['GROUND', 'AMBIENT', 'EMPTY_SPACE', 'HOME_FILL', 'APPEARANCE_FILL', 'TETHER', 'REGISTER_FILL']) {
    assert.equal(new RegExp(`\\bconst ${placeholder} =`, 'u').test(canvas), false, `the placeholder ${placeholder} is gone`);
  }
  assert.equal(/rgb\(\d/u.test(canvas), false, 'the renderer has no colour literal');
  assert.equal(/'#[0-9a-fA-F]{3,8}'/u.test(canvas), false, 'the renderer has no hex literal');
  // Plain circles are no longer the world: every object is its canonical morphology through the visual owner.
  assert.equal(canvas.includes('<Circle'), false, 'the renderer draws no plain circle of its own');
  assert.equal(canvas.includes('<Line'), false, 'the renderer draws no plain line of its own');
  // The canonical tone curve, exactly (renderComposite: out = (1-a)*w + a*w*w), and its a from P.toneA.
  assert.ok(visual['WorldStrata.tsx'].includes('return half4(c.rgb * (1.0 - a) + c.rgb * c.rgb * a, c.a);'), 'the tone curve is the canonical one');
  assert.match(visual['world-visual.generated.ts'], /"tone": \{\s*"a": 0\.46\s*\}/u);
  for (const required of ['<WorldTone', '<WorldPlaceAtmosphere', '<WorldGround', '<WorldAtmosphere', '<WorldObject', '<WorldTether', '<WorldVeil', '<RegisterMark']) {
    assert.ok(canvas.includes(required), `the renderer paints ${required}`);
  }
  // The hand-written visual modules hold no colour or palette literal: every value is generated.
  for (const [file, code] of Object.entries(visualCode)) {
    assert.equal(/rgb\(\d/u.test(code), false, `${file} has no rgb literal`);
    assert.equal(/['"]#[0-9a-fA-F]{6}['"]/u.test(code), false, `${file} has no hex literal`);
    assert.equal(/hsla?\(\d/u.test(code), false, `${file} has no hsl literal`);
  }
});

test('no WebView, no HTML world, no runtime icon package', () => {
  const mapFiles = [];
  const walk = (dir) => {
    for (const entry of readdirSync(new URL(dir, root), { withFileTypes: true })) {
      if (entry.isDirectory()) walk(`${dir}/${entry.name}`);
      else if (/\.tsx?$/u.test(entry.name)) mapFiles.push(`${dir}/${entry.name}`);
    }
  };
  walk('apps/mobile/src/map');
  for (const file of mapFiles) {
    const code = stripComments(read(file));
    for (const forbidden of ['react-native-webview', 'WebView', '<iframe', 'srcdoc', 'hugeicons', 'react-native-svg']) {
      assert.equal(code.includes(forbidden), false, `${file} must not contain ${forbidden}`);
    }
    // The canonical prototype is named only as provenance in a generated module, never loaded.
    if (!file.endsWith('.generated.ts')) assert.equal(code.includes('wf-living-constellation'), false, `${file} must not load the prototype`);
  }
  const manifest = JSON.parse(read('apps/mobile/package.json'));
  for (const name of Object.keys({ ...manifest.dependencies, ...manifest.devDependencies })) {
    assert.equal(/webview|hugeicons|react-native-svg/iu.test(name), false, `${name} is not a VPORT-01 dependency`);
  }
});

test('the world is derived from the presented scene, and the only relation drawn is the one the scene holds', () => {
  // One source for objects and one for register marks, both the surface's presented set.
  assert.equal((canvas.match(/<WorldObject\b/gu) ?? []).length, 1);
  assert.equal((canvas.match(/<RegisterMark\b/gu) ?? []).length, 1);
  assert.equal((canvas.match(/<WorldTether\b/gu) ?? []).length, 1);
  // S5-03B Phase 1: the generic canvas maps every presented plane node to ONE object and every register node to ONE
  // register entry; the Personal owner says what each is: a WorldObject, a RegisterMark.
  assert.match(worldCanvas, /planeNodes\.map\(\(node\) => \(\s*\n?[\s\S]*?\{renderObject\(node, frame\)\}/u);
  assert.match(worldCanvas, /registerNodes\.map\(\(node\) => \(\s*\n?[\s\S]*?\{renderRegister\?\.\(node, frame\)\}/u);
  assert.match(personalCanvasOwner, /renderObject=\{\(node, \{ S, response \}\) => \(\s*\n\s*<WorldObject/u);
  assert.match(personalCanvasOwner, /renderRegister=\{\(node, \{ S \}\) => \(\s*\n\s*<RegisterMark/u);
  // The generic canvas paints no object of its own: what an object IS stays the projection's.
  assert.equal(/<WorldObject|<RegisterMark|<WorldTether|<WorldMark\b/u.test(worldCanvas), false, 'the generic canvas names no object family');
  // The tether is drawn only for a contextual appearance, only from the Home that hosts it in THIS placement.
  const tetherBlock = canvas.slice(canvas.indexOf("node.locus?.kind === 'CONTEXTUAL_APPEARANCE'"), canvas.indexOf('<WorldTether'));
  assert.match(tetherBlock, /const host = hostOf\(node, placed\);\s*\n\s*if \(host === undefined\) return null;/u);
});

test('the visual owner reads no analytical quantity, no ordinal and no fact it would invent', () => {
  const all = Object.values(visualCode).join('\n');
  for (const forbidden of ['ordinal', 'boundSp', 'disclosedAtDepth', '.current', 'confidence', 'importance', 'liveFocus', 'LiveFocus', 'statement', 'HistoricalDisclosure', 'context.disclosure']) {
    assert.equal(all.includes(forbidden), false, `the visual owner must not read ${forbidden}`);
  }
  // QANDEEL Light: AMBIENT is the atmosphere and CONNECTION's residue is the hosting tether. PATTERN and
  // INSIGHT have no production truth, so they have no expression at all.
  for (const forbidden of [/\bpattern\b/iu, /\binsight\b/iu, /\bnow\b/u, /illumination/u]) {
    assert.equal(forbidden.test(all), false, `no expression for ${forbidden}`);
  }
  // The world draws no words: no label, no Text, no font.
  assert.equal(/<Text\b|Paragraph|useFont|matchFont/u.test(all + canvas), false, 'the world carries no typography');
});

test('nothing visual reaches membership, placement, hit testing, accessibility or an act', () => {
  for (const file of [
    'apps/mobile/src/map/projection/map-scene.ts',
    'apps/mobile/src/map/renderer/map-geometry.ts',
    'apps/mobile/src/map/accessibility/map-accessibility.ts',
    'apps/mobile/src/map/accessibility/MapAccessibilityLayer.tsx',
    'apps/mobile/src/map/inspection/entitlement.ts',
    'apps/mobile/src/map/inspection/locatability.ts',
    'apps/mobile/src/map/inspection/map-actions.ts',
    'apps/mobile/src/map/camera/camera.ts',
    'apps/mobile/src/map/camera/viewport.ts',
  ]) {
    const code = stripComments(read(file));
    assert.equal(/from '\.\.\/visual'|from '\.\/visual'|world-resolver|WORLD_VISUAL/u.test(code), false, `${file} must not read the visual owner`);
  }
  // The visual owner dispatches nothing and touches no store.
  const all = Object.values(visualCode).join('\n');
  for (const forbidden of ['dispatch', 'getState', 'subscribe', 'useSyncExternalStore']) {
    assert.equal(all.includes(forbidden), false, `the visual owner must not use ${forbidden}`);
  }
  // The T-04 placement radii (which hit testing reads) did not move.
  const geometry = read('apps/mobile/src/map/renderer/map-geometry.ts');
  for (const value of ['HOME_RADIUS_POINTS = 13', 'APPEARANCE_RADIUS_POINTS = 6', 'APPEARANCE_RING_RADIUS_POINTS = 40', 'REGISTER_RADIUS_POINTS = 6']) {
    assert.ok(geometry.includes(value), `placement geometry is unchanged: ${value}`);
  }
  // The surface hands the canvas its facts and decides nothing new with them.
  assert.match(surface, /const world = useMemo\(/u);
  assert.match(surface, /world=\{world\}/u);
});

test('the Analysis world is dark, whatever the reader chose elsewhere, and contrast is the F1 override', () => {
  const generated = visual['world-visual.generated.ts'];
  assert.equal(generated.includes('"LIGHT"'), false, 'no Light family reaches the world');
  assert.match(generated, /"palettes": \{\s*"standard": \{[\s\S]*?\},\s*"increased": \{[\s\S]*?\}\s*\},\s*"parallax"/u, 'the only palettes are Dark standard and Dark increased');
  assert.equal(/useSurfaceAppearance|useAppearance\(/u.test(Object.values(visualCode).join('\n') + canvas + surface), false, 'the world reads no appearance preference');
  assert.match(generated, /"analysisRelation": "#8b8982"/u);
  assert.match(generated, /"analysisRelation": "#afaca3"/u);
  assert.match(generated, /"strokeAlphaMultiplier": 0/u);
});

test('motion stays T-10\'s: the world reads the residual through the motion owner and animates nothing of its own', () => {
  const all = Object.values(visualCode).join('\n') + canvas;
  for (const forbidden of ['react-native-reanimated', 'withTiming', 'withSpring', 'withRepeat', 'useFrameCallback', 'setInterval', 'setTimeout', 'requestAnimationFrame', 'useClock', 'Easing']) {
    assert.equal(all.includes(forbidden), false, `the world must not use ${forbidden}`);
  }
  const reading = stripComments(read('apps/mobile/src/motion/presentation-camera/usePresentationReading.ts'));
  assert.equal((reading.match(/useDerivedValue\(/gu) ?? []).length, 2, 'the reading seam is two derivations and nothing else');
  for (const forbidden of ['withTiming', 'withSpring', 'cancelAnimation', 'useSharedValue', 'scheduleOnRN', '.set(']) {
    assert.equal(reading.includes(forbidden), false, `the reading seam must not use ${forbidden}`);
  }
});

test('LA-VIS-01: the one declared chroma palette is exactly the six authorized families, and its field reads a world address only', () => {
  // Product Owner authorization (2026-10-07): a PRESENTATION-ONLY palette extension, declared in one module, never an
  // open exception. Its families are pinned here exactly; any change to them is a new decision, not a tuning.
  const chroma = visualCode['world-chroma.ts'];
  const families = [...chroma.matchAll(/Object\.freeze\(\{ hue: (\d+), saturation: (\d+), lightness: (\d+) \}\)/gu)].map((f) => f.slice(1).map(Number));
  assert.deepEqual(families, [[186, 78, 50], [218, 82, 52], [268, 72, 58], [328, 74, 56], [34, 92, 52], [152, 66, 46]], 'teal, deep blue, violet, magenta, amber, emerald');
  // The field is a function of a canonical world address and nothing else: no camera, screen, identity, store or time.
  assert.match(chroma, /export function worldChroma\(address: CanonicalWorldAddress\): ChromaFamily/u);
  assert.match(chroma, /export function chromaPhase\(address: CanonicalWorldAddress\): number/u);
  for (const forbidden of ['camera', 'scale', 'envelope', 'key', 'region', 'Date', 'random', 'useState', "'../../state", "'../camera"]) {
    assert.equal(chroma.includes(forbidden), false, `the chroma field must not read ${forbidden}`);
  }
  // It is worn only by the world around a place: the generic canvas reads the owner's address for that, and only that.
  assert.match(worldCanvas, /chroma=\{chromaAt\(worldAddressOf\?\.\(node\)\)\}/u);
  assert.equal((worldCanvas.match(/worldAddressOf/gu) ?? []).length, 3, 'declared, destructured, read once');
  assert.match(personalCanvasOwner, /worldAddressOf=\{\(node\) => \(node\.locus\?\.kind === 'THREAD_HOME' \? node\.locus\.address : undefined\)\}/u);
  // Nothing that decides membership, placement, hit testing or accessibility reads it.
  for (const file of ['apps/mobile/src/map/renderer/map-geometry.ts', 'apps/mobile/src/map/projection/map-scene.ts', 'apps/mobile/src/map/accessibility/map-accessibility.ts', 'apps/mobile/src/map/camera/camera.ts']) {
    assert.equal(read(file).includes('world-chroma'), false, `${file} must not read the chroma field`);
  }
});

test('LA-VIS-01: a place mass is pure paint — one picture per meaning-free variant and chroma, read by nothing that decides', () => {
  // Product Owner task LA-VIS-01 (closure re-anchor): the mass material is recorded once per shape variant and colour.
  // It imports Skia, the declared chroma type and the resolver's paint helpers, and nothing else: no camera, store,
  // projection, scene or time.
  const mass = visualCode['world-mass.ts'];
  const imports = [...mass.matchAll(/^import [^;]*? from '([^']+)';/gmu)].map((m) => m[1]);
  assert.deepEqual(imports, ['@shopify/react-native-skia', './world-chroma', './world-resolver']);
  assert.match(mass, /export function massPicture\(seed: string, chroma: ChromaFamily\): SkPicture/u);
  for (const forbidden of ['camera', 'envelope', 'Date', 'Math.random', 'useState', "'../../state", "'../projection", "'../camera"]) {
    assert.equal(mass.includes(forbidden), false, `the mass material must not read ${forbidden}`);
  }
  // It is worn only by the world around a place, through the one owner of that paint.
  const readers = HAND_WRITTEN.filter((file) => file !== 'world-mass.ts' && visualCode[file].includes("'./world-mass'"));
  assert.deepEqual(readers, ['WorldMarks.tsx']);
  for (const file of ['apps/mobile/src/map/renderer/map-geometry.ts', 'apps/mobile/src/map/projection/map-scene.ts', 'apps/mobile/src/map/accessibility/map-accessibility.ts', 'apps/mobile/src/map/camera/camera.ts']) {
    assert.equal(read(file).includes('world-mass'), false, `${file} must not read the mass material`);
  }
});
