import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

/**
 * VPORT-02 — Final Temporal / Orientation / Iconography Production Port + Stage-2 Coherence Closure. The static guards.
 *
 * VPORT-02 consumed the existing Timeline, Temporal Navigation, Return, OrientationChrome and T-10 runtime and added
 * only the final production visual / coherence layer over them. These guards keep it that way:
 *
 *   - the P2 Temporal Spine + Aperture C "Parting" is what production draws, from geometry GENERATED out of the merged
 *     P2-A package — never a proof DOM, a comparison variant or a hand-typed copy;
 *   - Return acts stay text-led: no icon, arrow or chevron path into any return act;
 *   - the Call Rail A "Keyed Seam" is a truth-safe visual machine with no activity input and no fake call surface;
 *   - the VPORT-01 Living Analysis World is byte-for-byte what VPORT-01 shipped;
 *   - the T-10 camera and temporal-motion hooks read the ONE live Reduce Motion reader (`QAN-BL-A11Y-01`);
 *   - the G3 composition (the temporal line beside the Timeline; Return Live's one home) and the dark Analysis ground
 *     are wired on the production route;
 *   - the backlog and the record cannot claim VPORT-02's closure while `QAN-BL-A11Y-01` is unreconciled.
 */

const root = new URL('../', import.meta.url);
const rootPath = fileURLToPath(root);
const read = (path) => readFileSync(new URL(path, root), 'utf8').replace(/\r\n/gu, '\n');
const stripComments = (text) => text.replace(/\/\*[\s\S]*?\*\//gu, '').replace(/\/\/[^\n]*/gu, '');
const gitBlob = (path) => execFileSync('git', ['hash-object', path], { cwd: rootPath, encoding: 'utf8' }).trim();

const MOBILE = 'apps/mobile/src';
const ICONOGRAPHY = `${MOBILE}/iconography`;
const GENERATED = `${ICONOGRAPHY}/p2-production.generated.ts`;
const P2A = 'docs/design/p2-iconography/QANDEEL_P2-A_FINAL_ICONOGRAPHY_INTEGRATED_VISUAL_PROOF/source/src';
const RECORD = 'docs/e2e/QANDEEL_VPORT_02_TIMELINE_ORIENTATION_P2_FINAL_COHERENCE_IMPLEMENTATION_RECORD_v1.md';
const BACKLOG = 'docs/qandeel-canonical-backlog-v1.md';

function sourcesUnder(dir) {
  const found = [];
  for (const entry of readdirSync(new URL(dir, root))) {
    const path = `${dir}/${entry}`;
    if (statSync(new URL(path, root)).isDirectory()) {
      if (entry === '__tests__' || entry === '__fixtures__' || entry === '__validation__') continue;
      found.push(...sourcesUnder(path));
    } else if (/\.(?:ts|tsx)$/u.test(entry)) {
      found.push(path);
    }
  }
  return found;
}
const production = sourcesUnder(MOBILE);
const code = (path) => stripComments(read(path));

const layer = code(`${MOBILE}/temporal-navigation/timeline-integration/TemporalTargetLayer.tsx`);
const machine = code(`${ICONOGRAPHY}/TemporalMachine.tsx`);
const rail = code(`${ICONOGRAPHY}/CallRail.tsx`);
const composition = code(`${MOBILE}/integration/composition/LivingAnalysisMap.tsx`);

test('production draws the frozen P2 Temporal Spine C, generated from the merged P2-A package and current', () => {
  execFileSync(process.execPath, [join(rootPath, 'apps/mobile/scripts/generate-p2-production.mjs'), '--check'], { stdio: 'pipe' });
  const generated = read(GENERATED);
  assert.match(generated, /^\/\*\*\n \* GENERATED by apps\/mobile\/scripts\/generate-p2-production\.mjs — do not edit by hand\./u);
  for (const source of ['app.js', 'machines.mjs', 'sig.mjs']) {
    assert.match(generated, new RegExp(`${P2A.replace(/[.]/gu, '\\.')}/${source.replace(/[.]/gu, '\\.')}  [0-9a-f]{64}`, 'u'), `the generated geometry names ${source} and its hash`);
  }
  const generator = read('apps/mobile/scripts/generate-p2-production.mjs');
  // The accepted variants and nothing else: C for the Spine, A for the Rail, N1 for the glyphs.
  assert.match(generator, /if \(machines\.SPINE_RECOMMENDED !== 'C'\) fail/u);
  assert.match(generator, /if \(machines\.RAIL_RECOMMENDED !== 'A'\) fail/u);
  assert.match(generator, /if \(OPEN\.id !== 'N1'\) fail/u);
  assert.match(generator, /aperture\('C', /u, 'the proof\'s own aperture() is executed for variant C');
  assert.doesNotMatch(generator, /aperture\('[AB]'/u, 'no comparison variant is ever executed');
  // The temporal surface draws it: the spine, the two apertures on T-06's own markers, and the Live terminal.
  for (const used of ['<SpineLayer', '<Aperture kind="COMMITTED"', '<Aperture kind="PREVIEW"', '<LiveTerminal']) {
    assert.ok(layer.includes(used), `the production temporal surface renders ${used}`);
  }
  assert.match(layer, /from '\.\.\/\.\.\/iconography'/u);
  assert.match(machine, /P2_SPINE/u);
  // A preview has no committed mark; the committed aperture has one.
  assert.match(machine, /kind === 'COMMITTED' \? \(\s*<RoundedRect/u);
  // Not promoted into Product law: the craft values are labelled as such where they are emitted.
  assert.match(generated, /reference CRAFT values, not Product law/u);
});

test('no proof-only P2 implementation is runtime authority, and no new icon dependency entered', () => {
  for (const path of production) {
    const text = code(path);
    // Provenance STRINGS in a generated header are fine; an import or require of the proof package is not.
    assert.doesNotMatch(text, /(?:from\s+|require\()\s*'[^']*(?:p2-iconography|QANDEEL_P2-A|docs\/)/u, `${path} reads nothing from the proof package at runtime`);
    assert.doesNotMatch(text, /from 'react-native-svg'|hugeicons|lucide|react-native-webview/u, `${path} adopts no proof renderer or icon package`);
  }
  const mobile = JSON.parse(read('apps/mobile/package.json'));
  for (const name of ['react-native-svg', 'hugeicons-react-native', '@hugeicons/react-native', 'lucide-react-native', 'react-native-vector-icons']) {
    assert.equal(mobile.dependencies?.[name], undefined, `${name} is not a mobile dependency`);
  }
});

test('Return acts stay text-led: no icon, arrow or chevron reaches any return act', () => {
  for (const file of ['ReturnControls.tsx', 'OrientationChrome.tsx', 'InspectionOrientation.tsx', 'TemporalOrientationLine.tsx']) {
    const text = code(`${MOBILE}/orientation-chrome/${file}`);
    for (const forbidden of ['iconography', 'Glyph', '@shopify/react-native-skia', '<Canvas', '<Path', 'chevron', 'arrow']) {
      assert.equal(text.toLowerCase().includes(forbidden.toLowerCase()), false, `${file} carries no ${forbidden}`);
    }
  }
  const copy = read(`${MOBILE}/orientation-chrome/product-copy.ts`);
  assert.doesNotMatch(copy, /[←→↩↪‹›«»]\s*$|[←→↩↪⟵⟶➜➔]/mu, 'no arrow glyph is smuggled into return words');
  // The Live edge keeps its words beside the terminal: never icon-only (T-12).
  assert.match(layer, /<Text style=\{\[type\('action'\), \{ color: wordInk \}\]\}>\{words\}<\/Text>/u);
});

test('the Call Rail is the frozen Keyed Seam, truth-safe, and mounted on no Product route', () => {
  const generated = read(GENERATED);
  assert.match(generated, /"end": 27/u, 'End Call renders at the frozen 27 px');
  assert.match(generated, /"width": 44/u);
  // No activity input of any kind: no level, waveform, speaking, listening or meter can be passed or drawn.
  for (const forbidden of ['level', 'waveform', 'speaking', 'listening', 'amplitude', 'meter', 'activity', 'Math.random', 'setInterval', 'withRepeat']) {
    assert.equal(rail.toLowerCase().includes(forbidden.toLowerCase()), false, `the Call Rail carries no ${forbidden}`);
  }
  // Neutral: End Call is primary ink, never the error ink and never Brass.
  assert.match(rail, /<EndCallGlyph ink=\{palette\.primary\} \/>/u);
  assert.doesNotMatch(rail, /palette\.error|brass|#[0-9a-f]{6}/iu);
  // Toggles expose their state and change form: the slash and the cut, the fill and the second wave.
  assert.match(rail, /accessibilityState=\{\{ checked: muted \}\}/u);
  assert.match(rail, /blendMode="clear"/u);
  assert.match(rail, /route === null \? null :/u, 'an unknown route is absent, never guessed');
  // Not mounted on the Product route: the only consumers are the barrel and validation entries.
  const consumers = production.filter((path) => path !== `${ICONOGRAPHY}/CallRail.tsx` && path !== `${ICONOGRAPHY}/index.ts` && /\bCallRail\b/u.test(code(path)));
  assert.deepEqual(consumers, [], 'no Product surface mounts a call surface with nothing behind it');
});

test('the VPORT-01 Living Analysis World is byte-for-byte what VPORT-01 shipped', () => {
  // S5-03B Phase 1 — CONTROLLED RE-ANCHOR (Product Owner decision D4, after the Personal golden equivalence proof in
  // apps/mobile/src/map/__tests__/golden-equivalence.test.tsx, recorded before the extraction): MapCanvas, MapSurface,
  // WorldMarks and the visual barrel now delegate to the generic Living Analysis World seam, and the two seam files
  // (WorldCanvas, useWorldSurface) are pinned beside them so the moved code stays frozen too. Previous pins:
  // MapCanvas 2738a72f, MapSurface 8f90bd39, WorldMarks fd4c9110, visual/index d65150b2.
  // S5-03B Phase 2 — CONTROLLED RE-ANCHOR (Public adoption, Personal golden still 16/16 with the golden file unchanged):
  // useWorldSurface gains the additive Class-D `atRest` fact (useWorldMotion), and worldPresentation reads its camera
  // as `Pick<MapCamera, 'anchor' | 'scale'>` so the Public world camera reads the same expression. Previous pins:
  // useWorldSurface 40d18141, world-presentation ca529b14.
  // S5-03B R1 — CONTROLLED RE-ANCHOR (Task Contract amendment 2026-10-07; after the Personal Map golden, 16 / 16, AND the
  // Living Analysis screen golden recorded before the extraction): MapSurface calls the one Living Analysis world view
  // (`useWorldView` / `WorldViewSurface`) in place, and that seam is pinned beside it. Previous pin: MapSurface 19440a92.
  for (const [path, blob] of [
    ['apps/mobile/src/map/renderer/MapCanvas.tsx', '974f515d0e2fedca69bb74150959c52850a67f1a'],
    ['apps/mobile/src/map/renderer/MapSurface.tsx', '680b2a42ceaff81a79e17ae9aae2557c6da6c68f'],
    ['apps/mobile/src/map/renderer/WorldViewSurface.tsx', '50786b8e2ffc375bbab416492a8aa21e2fe270a1'],
    ['apps/mobile/src/map/renderer/WorldCanvas.tsx', 'b3036bfc0290d81e669d23733e3b61a3184ed7ba'],
    ['apps/mobile/src/map/renderer/useWorldSurface.ts', 'ed4f83bade4ffa4af906f54cadb644febc19eee8'],
    ['apps/mobile/src/map/visual/WorldMarks.tsx', 'd50652c2eccc6158809916369e66ff111eec1b7b'],
    ['apps/mobile/src/map/visual/WorldStrata.tsx', 'bce9df4ab738bc090bb9247dbd5b5a445ca70ad9'],
    ['apps/mobile/src/map/visual/index.ts', '64e1bc4a276b046d70ac0818a08c6b3c120c5907'],
    ['apps/mobile/src/map/visual/useWorldResponse.ts', '2640e891cfeff3645d9f155f9e888b41d58f3748'],
    ['apps/mobile/src/map/visual/world-field.generated.ts', '1eab16b0c6ec722eacf96c7179c0034bdd10c7af'],
    ['apps/mobile/src/map/visual/world-presentation.ts', 'f0c3ec437b5e8ef582ade76ba65417ec82265bc0'],
    ['apps/mobile/src/map/visual/world-resolver.ts', 'ffe05a27613634cec00a3c5c5519afb0777c35bc'],
    ['apps/mobile/src/map/visual/world-visual.generated.ts', '172863d5b90e43ec0a6f299551296f410cf95f6a'],
  ]) {
    assert.equal(gitBlob(path), blob, `${path} is the VPORT-01 world, unchanged by VPORT-02`);
  }
  // The chrome layer reads no world paint and computes no second FAR / MID / NEAR mapping.
  for (const dir of [ICONOGRAPHY, `${MOBILE}/analysis-visual`, `${MOBILE}/orientation-chrome`, `${MOBILE}/temporal-navigation`, `${MOBILE}/timeline`]) {
    for (const path of sourcesUnder(dir)) {
      const text = code(path);
      assert.doesNotMatch(text, /map\/visual|useWorldResponse|worldUnitsPerPoint|\bFAR\b|\bNEAR\b/u, `${path} reads no world paint and no distance mapping`);
    }
  }
});

test('QAN-BL-A11Y-01: the T-10 camera and temporal motion read the ONE live Reduce Motion reader', () => {
  const owner = code(`${MOBILE}/motion/runtime/reduce-motion.ts`);
  assert.match(owner, /AccessibilityInfo\.addEventListener\('reduceMotionChanged'/u);
  // ONE platform listener in the whole app.
  const listeners = production.filter((path) => /addEventListener\('reduceMotionChanged'/u.test(code(path)));
  assert.deepEqual(listeners, [`${MOBILE}/motion/runtime/reduce-motion.ts`], 'one reader, one listener');
  for (const path of [`${MOBILE}/motion/presentation-camera/usePresentationCamera.ts`, `${MOBILE}/temporal-navigation/motion/useTemporalMotion.ts`]) {
    const text = code(path);
    assert.match(text, /const reducedMotion = useReduceMotion\(\);/u, `${path} reads the live reader`);
    assert.doesNotMatch(text, /useReducedMotion/u, `${path} no longer reads Reanimated's launch-only value`);
    // Every animation names its reduced-motion behaviour, so the live plan is the only authority.
    for (const match of text.matchAll(/with(?:Timing|Spring)\(/gu)) {
      const call = text.slice(match.index, match.index + 260);
      // The camera's travel shares one spring config, itself asserted to name Never just below.
      if (/^withSpring\(0, spring\)/u.test(call)) continue;
      const closes = call.indexOf('})');
      assert.match(call.slice(0, closes + 2), /reduceMotion: (?:ReduceMotion\.Never|NEVER)/u, `${path}: ${call.slice(0, 80)}… names ReduceMotion.Never`);
    }
  }
  assert.match(code(`${MOBILE}/motion/presentation-camera/usePresentationCamera.ts`), /const spring = \{ duration: plan\.translationMs, dampingRatio: plan\.dampingRatio, reduceMotion: ReduceMotion\.Never \};/u);
  const proof = read(`${MOBILE}/motion/__tests__/reduce-motion-mid-session.test.tsx`);
  assert.match(proof, /await act\(async \(\) => emit\(true\)\);[\s\S]*applyCanonicalChange\(LONG_TRAVEL\)\.kind\)\.toBe\('CUT_AND_RESOLVE'\)/u, 'proved mid-session, without a remount');
  assert.match(proof, /expect\(listening\)\.toBe\(1\);/u);
});

test('the frozen G3 composition and the dark Analysis ground are wired on the production route', () => {
  // S5-03B R1 — CONTROLLED RE-ANCHOR (after the Living Analysis screen golden, recorded before the extraction): the
  // screen — the dark ground, the Timeline row that says the line, the chrome band that yields its room — is the one
  // Living Analysis surface's; the Personal Analysis hands it the line, the Timeline and the chrome. Both are asserted.
  const screen = code(`${MOBILE}/living-analysis/LivingAnalysisSurface.tsx`);
  assert.match(screen, /style=\{\{ backgroundColor: ink\.world \}\}/u, 'the Analysis paints its own dark ground');
  assert.match(composition, /line: <TemporalOrientationLine store=\{store\} language=\{locale\.language\} preview=\{preview\} \/>,/u);
  assert.match(screen, /line=\{timeline\.line\}/u, 'the line is said in the Timeline row');
  assert.match(composition, /temporalLine="WITH_TIMELINE"/u);
  assert.match(composition, /returnLiveHome="LIVE_EDGE"/u);
  assert.match(screen, /<ResponsiveChromeBand chrome=\{plan\.chrome\} support=\{plan\.support\} yieldPoints=\{linePoints\}>/u, 'OrientationChrome yields the line\'s room');
  // Every Analysis chrome owner paints with the Analysis ink.
  for (const path of [
    `${MOBILE}/orientation-chrome/OrientationChrome.tsx`,
    `${MOBILE}/orientation-chrome/ReturnControls.tsx`,
    `${MOBILE}/orientation-chrome/InspectionOrientation.tsx`,
    `${MOBILE}/orientation-chrome/TemporalOrientationLine.tsx`,
    `${MOBILE}/temporal-navigation/timeline-integration/TemporalTargetLayer.tsx`,
    `${MOBILE}/temporal-navigation/accessibility/TemporalNavigator.tsx`,
    `${MOBILE}/timeline/virtualization/TimelinePresentation.tsx`,
    `${MOBILE}/timeline/accessibility/PresentationNavigator.tsx`,
  ]) {
    const text = code(path);
    assert.match(text, /useAnalysisInk\(\)/u, `${path} paints with the Analysis ink`);
    const bare = [...text.matchAll(/<Text(?![A-Za-z])([^>]*)>/gu)].filter((match) => !/style=/u.test(match[1]));
    assert.deepEqual(bare.map((match) => match[0]), [], `${path} renders no un-inked text`);
  }
  const ink = code(`${MOBILE}/analysis-visual/index.ts`);
  assert.match(ink, /CANONICAL_VISUAL\.palettes\.DARK/u, 'the Analysis is Dark by construction');
  assert.doesNotMatch(ink, /useSurfaceAppearance|LIGHT/u, 'and never reads the appearance preference');
});

test('VPORT-02 cannot claim closure while QAN-BL-A11Y-01 is unreconciled, and leaves no orphan gap', () => {
  const backlog = read(BACKLOG);
  const record = read(RECORD);
  const row = backlog.split('\n').find((line) => line.startsWith('| `QAN-BL-A11Y-01` |'));
  assert.ok(row, 'the backlog index still lists QAN-BL-A11Y-01 (IDs are never reused or removed)');
  assert.match(row, /`CLOSED — TOMBSTONE` \|$/u, 'QAN-BL-A11Y-01 is reconciled to a tombstone');
  const tombstones = backlog.slice(backlog.indexOf('## 6. Tombstones'), backlog.indexOf('## 7. Counts'));
  const entry = tombstones.slice(tombstones.indexOf('### `QAN-BL-A11Y-01`'));
  assert.ok(tombstones.includes('### `QAN-BL-A11Y-01`'), 'its tombstone is recorded in §6');
  assert.match(entry, /\*\*Closing task:\*\* `VPORT-02/u);
  assert.match(entry, /\*\*PR \/ SHA:\*\*/u);
  assert.match(entry, /\*\*Disposition:\*\*/u);
  // The record carries the gap matrix's verdict and does not claim a merge it cannot know.
  assert.match(record, /Orphan gaps = 0/u);
  assert.match(record, /QAN-BL-A11Y-01/u);
  assert.match(record, /Stage-2 Gap Closure Matrix/u);
  assert.match(record, /READY FOR INDEPENDENT REVIEW — DO NOT MERGE/u);
});

test('the VPORT-02 gate is registered at the root and in Mobile CI', () => {
  const pkg = JSON.parse(read('package.json'));
  assert.equal(pkg.scripts['test:vport-02-temporal-orientation-p2-contract'], 'node --test tests/vport-02-temporal-orientation-p2-contract.test.mjs');
  assert.match(read('.github/workflows/mobile-ci.yml'), /run: npm run test:vport-02-temporal-orientation-p2-contract/u);
});
