/**
 * GENERATED by apps/mobile/scripts/generate-world-visual.mjs — do not edit by hand.
 *
 * VPORT-01: the Living Analysis World's material, morphology, distance schedule and state tokens, from the closed I-08B1 source and the frozen token tree.
 * Regenerate after any source changes; the VPORT-01 contract fails on drift.
 *
 * Sources (sha256):
 *   docs/design/canonical-artifacts/living-analysis/i-08b1/wf-living-constellation.html  4dfd9d27d752c3a445168c0cc7067d71df4ada84bc61b806d12c8bb3202bc413
 *   docs/design/canonical-artifacts/living-analysis/i-08b1/I-08B1-WS7R-NOTES.md  fbaa8712e1454132a681f8f478ba75ee35ceae7af392a49d3f374ebad8440704
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/tools/f2-resolve.mjs  def095f5b5da30d97f770df71d8cbd5b04f691843f465062d0b756a91777f806
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/vendor/c3/b4r/semantic.tokens.json  2ac7c739091446b2c4bba53cd9058ac86cac9b877c1c975cb0a781f6a490c441
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/vendor/c3/tokens/base/material.tokens.json  bb841aa9ce194102da7a2567fd84fc95e9075e6e13805efc0c9698c4c6465928
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/vendor/d2r/tokens/base/illumination.tokens.json  2d32bf8987016d7d21b226b4c9111b5e38f8786397badc37dd4cd9655cf230b4
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/vendor/e1/tokens/base/interaction.tokens.json  6be98e6d270db5d8b2313165de51ec75b49a923faf4b16a833ad9db84106cbce
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/tokens/base/accessibility.tokens.json  dd47c43cb72eb306f2b701a883ce7c48e280f4d8bcfbf00664d0abca681e35cc
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/tokens/base/appearance.tokens.json  513f5dfa419e1a5b7c5729e7b062ea282c32df0a3284e73596bc10b9e652cadc
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/vendor/c3/b4r/dark.tokens.json  4641f1bcbf1c12473d74ddaa77a39e5bea4314d47753d40bfded0b2e347e1112
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/vendor/c3/tokens/appearance/dark.material.tokens.json  55c56ab78358d8a3353a8794887e31a9194578ab2731f4659d7c6de42df9a367
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/vendor/d2r/tokens/appearance/dark.illumination.tokens.json  688bad2f79ac7b22fdefe4b94f4c07a08b5c249bdcb84327e9df2ff82a565157
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/vendor/e1/tokens/appearance/dark.interaction.tokens.json  397c5e89d534baffd5863136656ded7d8c3b31ef5ec2c0ba0899bc40b5947252
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/tokens/appearance/dark.accessibility.tokens.json  3d2fbcca824255c5da8ee234f572f35bad68f143c47424ccc0057ad7e7407176
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/tokens/appearance/dark/f2.dark.illumination-technique.tokens.json  93b5fa8138c6ce9dea047f2ab34ba7c1a8c4de8aa9b89b2ac6da22c8ca4441c9
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/vendor/c3/b4r/standard.tokens.json  0916a7a5520e0f3696fd0c7420665bb86298171c79aef3634e0475627da6116a
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/tokens/transparency/full.accessibility.tokens.json  4551473f1fee8f6451e28d1c00bc4b5de66f2a5bfec6f6199c83ce7ec6bd90c5
 *   docs/design/canonical-artifacts/accessibility-appearance/i-08b3.1-f2r/vendor/f1/tokens/contrast/increased.accessibility.tokens.json  5b27d13790e0ce051822c226aa8f3c11cac04467156210f9469c229f391c8f2a
 */

export const WORLD_VISUAL = {
  "source": {
    "file": "docs/design/canonical-artifacts/living-analysis/i-08b1/wf-living-constellation.html",
    "sha256": "4dfd9d27d752c3a445168c0cc7067d71df4ada84bc61b806d12c8bb3202bc413"
  },
  "worldHue": 170,
  "mediumShift": 16,
  "material": {
    "ground": [
      "#02040a",
      "#03060d",
      "#010204"
    ],
    "vignette": 0.34,
    "grain": 0.048,
    "haloObj": 0.062,
    "haloObjMinor": 0.028,
    "objGnd": {
      "a": 0.7,
      "r": 3.1
    },
    "relGnd": {
      "a": 0.42,
      "w": 2.4,
      "k": 1.15,
      "max": 0.34
    },
    "rel": {
      "a": 0.54,
      "w": 0.58,
      "bead": 1.5
    },
    "neb": {
      "a": 0.66,
      "sat": 34
    }
  },
  "floor": {
    "rgb": [
      4,
      15,
      24
    ],
    "alpha": 0.44
  },
  "vignette": {
    "rgb": [
      1,
      2,
      5
    ],
    "inner": 0.3,
    "outer": 0.6,
    "midStop": 0.62,
    "midShare": 0.36,
    "mapRelief": 0.25
  },
  "groundDirection": {
    "x": 0.35,
    "y": 1
  },
  "mark": {
    "major": {
      "light": 82,
      "sat": 58,
      "alpha": 1.04,
      "halo": 6.6,
      "haloWide": 15,
      "core": 1.22,
      "coreAlpha": 0.24
    },
    "minor": {
      "light": 74,
      "sat": 40,
      "alpha": 0.72,
      "halo": 4.2,
      "haloWide": 9,
      "core": 1.05,
      "coreAlpha": 0.16
    },
    "mapLight": 5,
    "mapDesaturate": 0.4,
    "haloSat": 58,
    "haloLight": 70,
    "haloWideLight": 56,
    "haloNearGain": 4.6,
    "haloWideShare": 0.3,
    "rimWidth": 0.24,
    "limbWidth": 0.52,
    "limbShare": 0.38,
    "coreSatShare": 0.8
  },
  "relation": {
    "end": {
      "sat": 58,
      "light": 88
    },
    "middle": {
      "sat": 48,
      "satNear": 18,
      "light": 80,
      "lightNear": -9
    },
    "endAlpha": [
      1,
      0.34
    ],
    "middleAlpha": [
      0.46,
      1
    ],
    "ground": {
      "rgb": [
        3,
        5,
        11
      ]
    },
    "body": {
      "sat": 54,
      "light": 68,
      "share": 0.17,
      "width": 4.6,
      "max": 0.4
    },
    "bead": {
      "sat": 40,
      "light": 94,
      "share": 1.9,
      "max": 0.96
    },
    "widthScale": 1.3
  },
  "field": {
    "far": 3600,
    "near": 640
  },
  "profiles": {
    "point": [
      [
        0,
        1
      ],
      [
        0.16,
        0.4
      ],
      [
        0.42,
        0.09
      ],
      [
        1,
        0
      ]
    ],
    "wide": [
      [
        0,
        1
      ],
      [
        0.13,
        0.28
      ],
      [
        0.48,
        0.055
      ],
      [
        1,
        0
      ]
    ],
    "core": [
      [
        0,
        1
      ],
      [
        0.4,
        0.72
      ],
      [
        0.7,
        0.16
      ],
      [
        1,
        0
      ]
    ],
    "soft": [
      [
        0,
        1
      ],
      [
        0.34,
        0.32
      ],
      [
        1,
        0
      ]
    ]
  },
  "shade": [
    {
      "offset": 0,
      "rgb": [
        3,
        5,
        11
      ],
      "alpha": 1
    },
    {
      "offset": 0.46,
      "rgb": [
        3,
        5,
        11
      ],
      "alpha": 0.62
    },
    {
      "offset": 0.78,
      "rgb": [
        3,
        5,
        11
      ],
      "alpha": 0.17
    },
    {
      "offset": 1,
      "rgb": [
        3,
        5,
        11
      ],
      "alpha": 0
    }
  ],
  "shapes": {
    "THREAD": {
      "slot": "THREAD",
      "rotation": 1,
      "ops": [
        [
          "ellipse",
          0,
          0,
          1.34,
          0.62,
          0,
          0,
          6.2832
        ]
      ],
      "stroked": false
    },
    "READING": {
      "slot": "READING",
      "rotation": 0.18,
      "ops": [
        [
          "M",
          -1.14,
          -0.56
        ],
        [
          "L",
          1.14,
          -0.56
        ],
        [
          "Q",
          1.42,
          -0.56,
          1.42,
          -0.28
        ],
        [
          "L",
          1.42,
          0.28
        ],
        [
          "Q",
          1.42,
          0.56,
          1.14,
          0.56
        ],
        [
          "L",
          -1.14,
          0.56
        ],
        [
          "Q",
          -1.42,
          0.56,
          -1.42,
          0.28
        ],
        [
          "L",
          -1.42,
          -0.28
        ],
        [
          "Q",
          -1.42,
          -0.56,
          -1.14,
          -0.56
        ],
        [
          "close"
        ]
      ],
      "stroked": false
    },
    "EMERGING_FOCUS": {
      "slot": "OPEN",
      "rotation": 1,
      "ops": [
        [
          "arc",
          0,
          0,
          1.02,
          0.66,
          5.6232
        ]
      ],
      "stroked": true
    }
  },
  "palettes": {
    "standard": {
      "world": "#101010",
      "analysisNode": "#d8d5ca",
      "analysisRelation": "#8b8982",
      "selectedInk": "#d8d5ca",
      "selectedMarker": "#d8d5ca",
      "markerThickness": 2,
      "strokeAlphaMultiplier": 1,
      "routes": {
        "analysisNode": "qandeel.analysis.node → qandeel.content.primary → qandeel.expression.content.primary",
        "analysisRelation": "qandeel.analysis.relation → qandeel.content.tertiary → qandeel.expression.content.tertiary",
        "selectedMarker": "qandeel.state.selected.marker → qandeel.content.primary → qandeel.expression.content.primary"
      }
    },
    "increased": {
      "world": "#101010",
      "analysisNode": "#d8d5ca",
      "analysisRelation": "#afaca3",
      "selectedInk": "#d8d5ca",
      "selectedMarker": "#d8d5ca",
      "markerThickness": 2,
      "strokeAlphaMultiplier": 0,
      "routes": {
        "analysisNode": "qandeel.analysis.node → qandeel.content.primary → qandeel.expression.content.primary",
        "analysisRelation": "qandeel.analysis.relation → qandeel.content.secondary → qandeel.expression.content.secondary",
        "selectedMarker": "qandeel.state.selected.marker → qandeel.content.primary → qandeel.expression.content.primary"
      }
    }
  },
  "parallax": {
    "near": 1,
    "mid": 0.72,
    "far": 0.48,
    "reducedDifferential": 0
  }
} as const;

/** The canonical distance schedule — each line below is the I-08B1 `schedule(A)` expression of the same name. */
export interface WorldSchedule {
  lod: number;
  map: number;
  mapA: number;
  far: number;
  cosmos: number;
  rel: number;
  relBead: number;
  relGnd: number;
  relW: number;
  objMin: number;
  objMaj: number;
  objMat: number;
  objGnd: number;
  hier: number;
}

export function worldSchedule(A: number): WorldSchedule {
  'worklet';
  const clamp = (v: number, a: number, b: number): number => (v < a ? a : v > b ? b : v);
  const ss = (e0: number, e1: number, x: number): number => {
    const t = clamp((x - e0) / (e1 - e0), 0, 1);
    return t * t * (3 - 2 * t);
  };
  const LODON = true;
  const MAPON = true;
  const FARCAL = true;
  const S = {} as WorldSchedule;
  S.lod = LODON? ss(0.68,1.00,A) : 0;
  S.map = MAPON? ss(0.12,0.50,A)*(1-ss(0.56,0.98,A)) : 0;
  S.mapA = S.map*ss(0,0.04,S.map);
  S.far = FARCAL? (1-ss(0.0,0.12,A)) : 0;
  S.cosmos = (1-ss(0.26,0.88,A)*0.78)*(1-S.map*0.34);
  S.rel = (0.30+ss(0.24,0.66,A)*0.70)*(1-S.far*0.84);
  S.relBead = 1+ss(0.55,1.0,A)*0.55;
  S.relGnd = ss(0.44,0.90,A);
  S.relW = 1+ss(0.50,1.0,A)*0.85;
  S.objMin = (0.34+ss(0.14,0.52,A)*0.66)*(1-S.far*0.52);
  S.objMaj = (0.62+ss(0.02,0.42,A)*0.38)*(1-S.far*0.46);
  S.objMat = ss(0.58,0.92,A);
  S.objGnd = ss(0.48,0.92,A);
  S.hier = ss(0.50,1.0,A);
  return S;
}

/** The canonical star admission and weight at approach A (`S.stars`). */
export function worldStars(A: number, S: WorldSchedule): { cut: number; a: number } {
  'worklet';
  const clamp = (v: number, a: number, b: number): number => (v < a ? a : v > b ? b : v);
  const lerp = (a: number, b: number, t: number): number => a + (b - a) * t;
  const ss = (e0: number, e1: number, x: number): number => {
    const t = clamp((x - e0) / (e1 - e0), 0, 1);
    return t * t * (3 - 2 * t);
  };
  return {
    cut: lerp(0.24, 0.4, ss(0.08, 0.52, A)) * (1 - ss(0.62, 1.0, A) * 0.28),
    a: (1 - ss(0.3, 0.8, A) * 0.44 + ss(0.78, 1.0, A) * 0.16) * (1 + S.lod * 0.26) * (1 - S.map * 0.42),
  };
}
