import type { BackgroundIntelligenceAuthorityService, BackgroundIntelligenceExecutionContext } from '../background-intelligence/background-intelligence-authority.service';
import type { BackgroundIntelligenceEnrichmentService } from '../background-intelligence/background-intelligence-enrichment.service';
import type { HypothesisEvidenceAssociationAuthorityService } from '../hypothesis/hypothesis-evidence-association-authority.service';
import { FakeHypothesisEvidenceAssociationProvider } from '../hypothesis/fake-hypothesis-evidence-association.provider';
import type { HypothesisEvidenceAssociationSnapshot } from '../hypothesis/hypothesis-evidence-association.types';
import type { RuntimeEventEnvelope } from '../runtime-events/runtime-event.types';
import { ModelAssistedHypothesisAssociationService } from './model-assisted-hypothesis-association.service';

const ids={event:'10000000-0000-4000-8000-000000000001',user:'10000000-0000-4000-8000-000000000002',session:'10000000-0000-4000-8000-000000000003',turn:'10000000-0000-4000-8000-000000000004',evidence:'memory:10000000-0000-4000-8000-000000000005',hypothesis:'10000000-0000-4000-8000-000000000006'};
const context={eventId:ids.event,userId:ids.user,sessionId:ids.session,sourceTurnId:ids.turn}as BackgroundIntelligenceExecutionContext;
const event={event_id:ids.event,subject_user_id:ids.user,subject_session_id:ids.session,subject_turn_id:ids.turn}as RuntimeEventEnvelope;
const snapshot:HypothesisEvidenceAssociationSnapshot={contractVersion:1,freshEvidence:{evidenceId:ids.evidence,evidenceKind:'USER_STATED_FACT',statement:'fact',source:'USER_STATED'},candidateHypotheses:[{hypothesisId:ids.hypothesis,hypothesisVersion:1,statement:'candidate',type:'CAUSAL',domain:'GENERAL',scope:`CONVERSATION_SESSION:${ids.session}`,assumptions:[],disconfirmingConditions:[],alreadySupporting:false,alreadyContradicting:false}],maxAssociationCount:4};

describe('ModelAssistedHypothesisAssociationService',()=>{
 const setup=()=>{const enrichment={listEligibleEvidence:jest.fn().mockResolvedValue([snapshot.freshEvidence]),listActiveHypotheses:jest.fn().mockResolvedValue([])}as unknown as jest.Mocked<BackgroundIntelligenceEnrichmentService>;const authority={prepareFromCanonicalState:jest.fn().mockReturnValue({status:'PREPARED',snapshot}),authorizeFromCanonicalState:jest.fn().mockReturnValue({status:'AUTHORIZED',commands:[{hypothesisId:ids.hypothesis,expectedVersion:1,evidenceId:ids.evidence,evidenceRole:'SUPPORTING'}]})}as unknown as jest.Mocked<HypothesisEvidenceAssociationAuthorityService>;const background={authorize:jest.fn().mockResolvedValue({outcome:'AUTHORIZED',context})}as unknown as jest.Mocked<BackgroundIntelligenceAuthorityService>;const provider=new FakeHypothesisEvidenceAssociationProvider();provider.setProposals([{hypothesisId:ids.hypothesis,evidenceRole:'SUPPORTING'}]);return{enrichment,authority,background,provider,service:new ModelAssistedHypothesisAssociationService(enrichment,authority,background,provider)};};
 it('prepares only through canonical background state and the existing authority',async()=>{const s=setup();await expect(s.service.prepare(context,ids.evidence)).resolves.toEqual({status:'PREPARED',snapshot});expect(s.authority.prepareFromCanonicalState).toHaveBeenCalledWith(ids.user,ids.session,ids.evidence,expect.any(Array),expect.any(Array));expect(s.provider.calls).toHaveLength(0);});
 it('returns bounded authorized commands without invoking a mutation service',async()=>{const s=setup();await expect(s.service.proposeAndAuthorize(event,context,snapshot)).resolves.toEqual({status:'AUTHORIZED',commands:[{hypothesisId:ids.hypothesis,expectedVersion:1,evidenceId:ids.evidence,evidenceRole:'SUPPORTING'}]});expect(s.provider.calls).toHaveLength(1);expect(s.background.authorize).toHaveBeenCalledWith(event);expect(s.authority.authorizeFromCanonicalState).toHaveBeenCalledTimes(1);});
 it.each([{userId:'foreign'},{sessionId:'foreign'},{sourceTurnId:'foreign'},{eventId:'foreign'}])('fails closed after provider output when canonical authority changes: %o',async change=>{const s=setup();s.background.authorize.mockResolvedValueOnce({outcome:'AUTHORIZED',context:{...context,...change}}as never);await expect(s.service.proposeAndAuthorize(event,context,snapshot)).rejects.toThrow('ASSOCIATION_CANONICAL_AUTHORITY_CHANGED');expect(s.authority.authorizeFromCanonicalState).not.toHaveBeenCalled();});
 it('propagates provider failure without producing commands or mutation',async()=>{const s=setup();const failing={propose:jest.fn().mockRejectedValue(new Error('provider failed'))};const service=new ModelAssistedHypothesisAssociationService(s.enrichment,s.authority,s.background,failing);await expect(service.proposeAndAuthorize(event,context,snapshot)).rejects.toThrow('provider failed');expect(s.background.authorize).not.toHaveBeenCalled();expect(s.authority.authorizeFromCanonicalState).not.toHaveBeenCalled();});
});
