import{randomUUID}from'node:crypto';import{Inject,Injectable}from'@nestjs/common';import{BackgroundIntelligenceAuthorityService}from'../background-intelligence/background-intelligence-authority.service';import{BackgroundIntelligenceEnrichmentService}from'../background-intelligence/background-intelligence-enrichment.service';import{HypothesisGenerationIntentExtractionService}from'../hypothesis/hypothesis-generation-intent-extraction.service';import{HypothesisGenerationRequestAssemblerService}from'../hypothesis/hypothesis-generation-request-assembler.service';import{HYPOTHESIS_CANDIDATE_GENERATOR,type BoundHypothesisCandidateGenerator}from'../hypothesis/hypothesis-candidate-generator-provider.types';import{isValidRuntimeEventEnvelope,type RuntimeEventEnvelope}from'../runtime-events/runtime-event.types';import{PostResponseIntelligenceRepository}from'./post-response-intelligence.repository';import type{IntelligenceEffect,IntelligenceExecution}from'./post-response-intelligence.types';

@Injectable()
export class PostResponseIntelligenceDispatcherService{
 constructor(private readonly ledger:PostResponseIntelligenceRepository,private readonly authority:BackgroundIntelligenceAuthorityService,private readonly enrichment:BackgroundIntelligenceEnrichmentService,private readonly extraction:HypothesisGenerationIntentExtractionService,private readonly assembler:HypothesisGenerationRequestAssemblerService,@Inject(HYPOTHESIS_CANDIDATE_GENERATOR)private readonly generator:BoundHypothesisCandidateGenerator){}
 async dispatch(raw:string):Promise<boolean>{let event:RuntimeEventEnvelope;try{event=JSON.parse(raw)as RuntimeEventEnvelope;}catch{return true;}if(!isValidRuntimeEventEnvelope(event))return true;if(event.event_type!=='ConversationTurnCompleted')return true;const v2=event.event_version==='2.0';const execution=await this.ledger.acquire({id:randomUUID(),eventId:event.event_id,userId:event.subject_user_id,sessionId:event.subject_session_id,sourceTurnId:event.subject_turn_id,eventVersion:event.event_version,processingPath:(event.payload.processing_path??null)as'FAST'|'DEEP'|null,safetyDisposition:v2?event.payload.safety_disposition as'ALLOW'|'GUIDED'|'BLOCK':null});if(execution.state!=='RUNNING')return true;const effects=await this.ledger.effects(execution.id);if(effects.some(effect=>effect.state==='CLAIMED'))return this.terminal(execution,'QUARANTINED','INDETERMINATE_EFFECT','EFFECT_RECOVERY');if(execution.attempt_count>=5)return this.terminal(execution,'QUARANTINED','MAX_ATTEMPTS','DELIVERY');if(!v2)return this.terminal(execution,'SKIPPED','LEGACY_UNSUPPORTED','VALIDATION');const authorized=await this.authority.authorize(event);if(authorized.outcome!=='AUTHORIZED'||!authorized.context)return this.terminal(execution,'QUARANTINED',authorized.outcome==='NOT_AUTHORIZED_OWNER_MISMATCH'?'CANONICAL_MISMATCH':'AUTHORITY_REJECTED','AUTHORITY');if(execution.safety_disposition!=='ALLOW')return this.terminal(execution,'SKIPPED','SAFETY_SKIPPED','SAFETY');const context=authorized.context;const turn=await this.enrichment.readCanonicalSourceTurn(context);if(turn.processing_path!==execution.processing_path)return this.terminal(execution,'QUARANTINED','CANONICAL_MISMATCH','CANONICAL_REREAD');
  const completed=new Set(effects.filter(effect=>effect.state==='COMPLETED').map(effect=>effect.effect_key));
  if(!await this.effect(execution,'MEMORY_WRITE',completed,()=>this.enrichment.evaluateAndWriteMemory(context,turn.content)))return true;
  const assessment=await this.enrichment.evaluateGenerationEligibility(context,turn.content,'ALLOW');if(!('triggerClassification'in assessment))return this.terminal(execution,'SKIPPED','NOT_ELIGIBLE','ELIGIBILITY');
  let intentResult:Awaited<ReturnType<HypothesisGenerationIntentExtractionService['extract']>>|undefined;if(!await this.effect(execution,'INTENT_PROVIDER',completed,async()=>{intentResult=await this.extraction.extract({currentTurn:{id:turn.id,sessionId:turn.session_id,role:'USER',status:'COMPLETED',text:turn.content},eligibility:assessment.eligibility,triggerReason:assessment.triggerClassification.reason,eligibleEvidence:assessment.eligibleEvidence});}))return true;
  if(!intentResult||intentResult.status!=='AUTHORIZED')return this.terminal(execution,'SKIPPED','INTENT_NOT_AUTHORIZED','INTENT');const assembled=this.assembler.assemble(intentResult.intent);if(assembled.status!=='READY')return this.terminal(execution,'SKIPPED','ASSEMBLY_NOT_READY','ASSEMBLY');
  let accepted:readonly{id:string}[]=[];const generationAlreadyCompleted=completed.has('CANDIDATE_PROVIDER')&&completed.has('HYPOTHESIS_PERSISTENCE');if(!await this.claimBoth(execution,completed,'CANDIDATE_PROVIDER','HYPOTHESIS_PERSISTENCE'))return true;if(!generationAlreadyCompleted)try{accepted=(await this.enrichment.generateHypotheses(context,assembled.request,this.generator)).accepted;await this.ledger.complete(execution.id,'CANDIDATE_PROVIDER');await this.ledger.complete(execution.id,'HYPOTHESIS_PERSISTENCE');}catch{return this.terminal(execution,'QUARANTINED','INDETERMINATE_EFFECT','GENERATION');}
  if(!await this.effect(execution,'CONFIDENCE_BATCH',completed,async()=>{for(const item of accepted){try{await this.enrichment.evaluateHypothesisConfidence(context,item.id);}catch{}}}))return true;return this.terminal(execution,'COMPLETED','COMPLETED','DONE');}
 private async effect(execution:IntelligenceExecution,key:IntelligenceEffect,completed:Set<IntelligenceEffect>,work:()=>Promise<unknown>):Promise<boolean>{if(completed.has(key))return true;if(!await this.ledger.claim(execution.id,key))return false;try{await work();const done=await this.ledger.complete(execution.id,key);if(done)completed.add(key);return done;}catch{await this.ledger.finish(execution.id,'QUARANTINED','INDETERMINATE_EFFECT',key);return false;}}
 private async claimBoth(execution:IntelligenceExecution,completed:Set<IntelligenceEffect>,a:IntelligenceEffect,b:IntelligenceEffect):Promise<boolean>{if(completed.has(a)&&completed.has(b))return true;if(completed.has(a)!==completed.has(b)){await this.ledger.finish(execution.id,'QUARANTINED','INDETERMINATE_EFFECT','GENERATION_PAIR');return false;}if(!await this.ledger.claim(execution.id,a))return false;if(!await this.ledger.claim(execution.id,b)){await this.ledger.finish(execution.id,'QUARANTINED','INDETERMINATE_EFFECT',b);return false;}return true;}
 private async terminal(execution:IntelligenceExecution,state:'COMPLETED'|'SKIPPED'|'QUARANTINED',outcome:string,stage:string):Promise<true>{await this.ledger.finish(execution.id,state,outcome,stage);return true;}
}
