import { BackgroundIntelligenceAuthorityService } from '../background-intelligence/background-intelligence-authority.service';
import { BackgroundIntelligenceContextFactory } from '../background-intelligence/background-intelligence-context.factory';
import type { BackgroundIntelligenceDataApiService } from '../background-intelligence/background-intelligence-data-api.service';
import type { BackgroundIntelligenceEnrichmentService } from '../background-intelligence/background-intelligence-enrichment.service';
import type { HypothesisGenerationIntentExtractionService } from '../hypothesis/hypothesis-generation-intent-extraction.service';
import type { HypothesisGenerationRequestAssemblerService } from '../hypothesis/hypothesis-generation-request-assembler.service';
import type { BoundHypothesisCandidateGenerator } from '../hypothesis/hypothesis-candidate-generator-provider.types';
import type { RuntimeEventEnvelope } from '../runtime-events/runtime-event.types';
import type { ModelAssistedHypothesisAssociationService } from './model-assisted-hypothesis-association.service';
import { PostResponseIntelligenceDispatcherService } from './post-response-intelligence-dispatcher.service';
import type { PostResponseIntelligenceRepository } from './post-response-intelligence.repository';

const id={event:'10000000-0000-4000-8000-000000000001',user:'10000000-0000-4000-8000-000000000002',session:'10000000-0000-4000-8000-000000000003',turn:'10000000-0000-4000-8000-000000000004',execution:'10000000-0000-4000-8000-000000000005'};
const event=(version:'1.0'|'2.0'='2.0',safety:'ALLOW'|'GUIDED'|'BLOCK'='ALLOW'):RuntimeEventEnvelope=>({event_id:id.event,event_type:'ConversationTurnCompleted',event_version:version,occurred_at:'2026-01-01T00:00:00Z',producer:'conversation-service',subject_user_id:id.user,subject_session_id:id.session,subject_turn_id:id.turn,correlation_id:null,causation_id:null,classification:'SENSITIVE',schema_ref:`qandeel.runtime.conversation-turn-completed.v${version==='2.0'?'2':'1'}`,payload:{user_id:id.user,session_id:id.session,source_turn_id:id.turn,terminal_status:'COMPLETED',processing_path:'FAST',routing_reason:'FAST_DEFAULT',orchestration_id:null,...(version==='2.0'?{safety_disposition:safety}:{})},contains_content:false,retention_class:'OPERATIONAL_EVENT_V1'});

describe('PostResponseIntelligenceDispatcherService',()=>{
 const setup=(overrides:{effects?:unknown[];state?:string}={})=>{const ledger={acquire:jest.fn().mockResolvedValue({id:id.execution,event_id:id.event,user_id:id.user,session_id:id.session,source_turn_id:id.turn,event_version:'2.0',processing_path:'FAST',safety_disposition:'ALLOW',state:overrides.state??'RUNNING',attempt_count:1}),effects:jest.fn().mockResolvedValue(overrides.effects??[]),claim:jest.fn().mockResolvedValue(true),complete:jest.fn().mockResolvedValue(true),finish:jest.fn().mockResolvedValue(true)}as unknown as jest.Mocked<PostResponseIntelligenceRepository>;const ownership={findSession:jest.fn().mockResolvedValue({id:id.session,status:'ACTIVE',channel:'TEXT'}),findSourceTurn:jest.fn().mockResolvedValue({id:id.turn,session_id:id.session,role:'USER',status:'COMPLETED',source_turn_id:null}),findCompletedAssistant:jest.fn().mockResolvedValue({id:'assistant',session_id:id.session,role:'ASSISTANT',status:'COMPLETED',source_turn_id:id.turn})}as unknown as BackgroundIntelligenceDataApiService;const authority=new BackgroundIntelligenceAuthorityService(new BackgroundIntelligenceContextFactory(),ownership);const enrichment={readCanonicalSourceTurn:jest.fn().mockResolvedValue({id:id.turn,session_id:id.session,role:'USER',status:'COMPLETED',source_turn_id:null,content:'Why do I repeat this pattern?',processing_path:'FAST',routing_reason:'FAST_DEFAULT'}),evaluateAndWriteMemory:jest.fn().mockResolvedValue({decision:'SKIP'}),evaluateGenerationEligibility:jest.fn().mockResolvedValue({eligibility:{status:'NOT_ELIGIBLE',reason:'NO_TRIGGER'}}),generateHypotheses:jest.fn(),evaluateHypothesisConfidence:jest.fn()}as unknown as jest.Mocked<BackgroundIntelligenceEnrichmentService>;const extraction={extract:jest.fn()}as unknown as jest.Mocked<HypothesisGenerationIntentExtractionService>;const assembler={assemble:jest.fn()}as unknown as jest.Mocked<HypothesisGenerationRequestAssemblerService>;const generator={generate:jest.fn()}as BoundHypothesisCandidateGenerator;const association={prepare:jest.fn(),proposeAndAuthorize:jest.fn()}as unknown as jest.Mocked<ModelAssistedHypothesisAssociationService>;return{ledger,enrichment,association,service:new PostResponseIntelligenceDispatcherService(ledger,authority,enrichment,extraction,assembler,generator,association)};};
 it('ACKs failed/cancelled and poison messages without background effects',async()=>{const s=setup(),failed={...event('1.0'),event_type:'ConversationTurnFailed',schema_ref:'qandeel.runtime.conversation-turn-failed.v1',payload:{...event('1.0').payload,terminal_status:'FAILED'}};await expect(s.service.dispatch(JSON.stringify(failed))).resolves.toBe(true);await expect(s.service.dispatch('{')).resolves.toBe(true);expect(s.ledger.acquire).not.toHaveBeenCalled();});
 it('terminalizes legacy Completed v1 without inferring Safety',async()=>{const s=setup();s.ledger.acquire.mockResolvedValueOnce({id:id.execution,event_id:id.event,user_id:id.user,session_id:id.session,source_turn_id:id.turn,event_version:'1.0',processing_path:'FAST',safety_disposition:null,state:'RUNNING',attempt_count:1});await s.service.dispatch(JSON.stringify(event('1.0')));expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'SKIPPED','LEGACY_UNSUPPORTED','VALIDATION');expect(s.enrichment.readCanonicalSourceTurn).not.toHaveBeenCalled();});
 it.each(['GUIDED','BLOCK']as const)('skips %s before enrichment',async safety=>{const s=setup();s.ledger.acquire.mockResolvedValueOnce({id:id.execution,event_id:id.event,user_id:id.user,session_id:id.session,source_turn_id:id.turn,event_version:'2.0',processing_path:'FAST',safety_disposition:safety,state:'RUNNING',attempt_count:1});await s.service.dispatch(JSON.stringify(event('2.0',safety)));expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'SKIPPED','SAFETY_SKIPPED','SAFETY');expect(s.enrichment.evaluateAndWriteMemory).not.toHaveBeenCalled();});
 it.each(['MEMORY_WRITE','ASSOCIATION_PROVIDER']as const)('quarantines a redelivery with an indeterminate claimed %s effect',async effectKey=>{const s=setup({effects:[{effect_key:effectKey,state:'CLAIMED'}]});await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','EFFECT_RECOVERY');expect(s.enrichment.readCanonicalSourceTurn).not.toHaveBeenCalled();expect(s.ledger.claim).not.toHaveBeenCalled();});
 it('claims Memory once and stops conservatively when deterministic eligibility says no',async()=>{const s=setup();await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.claim).toHaveBeenCalledWith(id.execution,'MEMORY_WRITE');expect(s.ledger.complete).toHaveBeenCalledWith(id.execution,'MEMORY_WRITE');expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'SKIPPED','NOT_ELIGIBLE','ELIGIBILITY');});
 it('claims the provider effect only for a prepared fresh-Evidence association',async()=>{const s=setup(),snapshot={contractVersion:1,freshEvidence:{evidenceId:`memory:${id.execution}`,evidenceKind:'USER_STATED_FACT',statement:'fact',source:'USER_STATED'},candidateHypotheses:[{hypothesisId:id.event,hypothesisVersion:1,statement:'candidate',type:'CAUSAL',domain:'GENERAL',scope:`CONVERSATION_SESSION:${id.session}`,assumptions:[],disconfirmingConditions:[],alreadySupporting:false,alreadyContradicting:false}],maxAssociationCount:4}as const;s.enrichment.evaluateAndWriteMemory.mockResolvedValueOnce({decision:'WRITE',type:'GOAL',memoryId:id.execution,evidenceId:`memory:${id.execution}`});s.association.prepare.mockResolvedValueOnce({status:'PREPARED',snapshot}as never);s.association.proposeAndAuthorize.mockResolvedValueOnce({status:'AUTHORIZED',commands:[]} as never);await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.claim).toHaveBeenCalledWith(id.execution,'ASSOCIATION_PROVIDER');expect(s.association.proposeAndAuthorize).toHaveBeenCalledTimes(1);});
 it('does not claim or call the provider for EMPTY preparation',async()=>{const s=setup();s.enrichment.evaluateAndWriteMemory.mockResolvedValueOnce({decision:'WRITE',type:'GOAL',memoryId:id.execution,evidenceId:`memory:${id.execution}`});s.association.prepare.mockResolvedValueOnce({status:'EMPTY',reason:'NO_SAME_SESSION_HYPOTHESES'});await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.claim).not.toHaveBeenCalledWith(id.execution,'ASSOCIATION_PROVIDER');expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();});
 it('does not repeat a completed association-provider effect on redelivery',async()=>{const s=setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED'},{effect_key:'ASSOCIATION_PROVIDER',state:'COMPLETED'}]});await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.claim).not.toHaveBeenCalledWith(id.execution,'ASSOCIATION_PROVIDER');expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();});
 it('quarantines after completed Memory when canonical fresh-Evidence identity cannot be recovered',async()=>{const s=setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED'}]});s.enrichment.listEligibleEvidence=jest.fn().mockResolvedValue([{evidenceId:`memory:${id.execution}`}]) as never;await s.service.dispatch(JSON.stringify(event()));expect(s.enrichment.evaluateAndWriteMemory).not.toHaveBeenCalled();expect(s.association.prepare).not.toHaveBeenCalled();expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();expect(s.enrichment.evaluateGenerationEligibility).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_RECOVERY');});
 it('quarantines provider failure before downstream generation or mutation',async()=>{const s=setup();s.enrichment.evaluateAndWriteMemory.mockResolvedValueOnce({decision:'WRITE',type:'GOAL',memoryId:id.execution,evidenceId:`memory:${id.execution}`});s.association.prepare.mockResolvedValueOnce({status:'PREPARED',snapshot:{} as never});s.association.proposeAndAuthorize.mockRejectedValueOnce(new Error('provider failed'));await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_PROVIDER');expect(s.enrichment.evaluateGenerationEligibility).not.toHaveBeenCalled();expect(s.enrichment.generateHypotheses).not.toHaveBeenCalled();expect(s.enrichment.evaluateHypothesisConfidence).not.toHaveBeenCalled();});
 it('quarantines failed post-provider reauthorization before downstream generation or mutation',async()=>{const s=setup();s.enrichment.evaluateAndWriteMemory.mockResolvedValueOnce({decision:'WRITE',type:'GOAL',memoryId:id.execution,evidenceId:`memory:${id.execution}`});s.association.prepare.mockResolvedValueOnce({status:'PREPARED',snapshot:{} as never});s.association.proposeAndAuthorize.mockResolvedValueOnce({status:'NOT_AUTHORIZED',reason:'TARGET_OUT_OF_UNIVERSE'});await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.complete).not.toHaveBeenCalledWith(id.execution,'ASSOCIATION_PROVIDER');expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_PROVIDER');expect(s.enrichment.evaluateGenerationEligibility).not.toHaveBeenCalled();expect(s.enrichment.generateHypotheses).not.toHaveBeenCalled();expect(s.enrichment.evaluateHypothesisConfidence).not.toHaveBeenCalled();});
});
