import { Injectable } from '@nestjs/common';
import type{HypothesisGenerationIntentExtractionResult}from'../hypothesis/hypothesis-generation-intent-extraction.types';
import type{MemoryWriteResult}from'../memory/memory-write.service';
import type{DurableAssociationResult}from'./durable-association-result';
import type{DurableCandidateProviderResult}from'./durable-generation-result';
import{CONFIDENCE_BATCH_COMMAND_STATUSES}from'./post-response-intelligence.types';
import type{ClaimableIntelligenceEffect,ConfidenceBatchCommandStatus,IntelligenceEffectState,IntelligenceExecution}from'./post-response-intelligence.types';

@Injectable()
export class PostResponseIntelligenceRepository{
 async acquire(input:{id:string;eventId:string;userId:string;sessionId:string;sourceTurnId:string;eventVersion:'1.0'|'2.0';processingPath:'FAST'|'DEEP'|null;safetyDisposition:'ALLOW'|'GUIDED'|'BLOCK'|null}):Promise<IntelligenceExecution>{return(await this.request<IntelligenceExecution[]>('rpc/acquire_post_response_intelligence_execution_v1',{method:'POST',body:JSON.stringify({p_id:input.id,p_event_id:input.eventId,p_user_id:input.userId,p_session_id:input.sessionId,p_source_turn_id:input.sourceTurnId,p_event_version:input.eventVersion,p_processing_path:input.processingPath,p_safety_disposition:input.safetyDisposition})}))[0];}
 async effects(id:string):Promise<readonly IntelligenceEffectState[]>{return this.request<IntelligenceEffectState[]>('rpc/list_post_response_intelligence_effects_v1',{method:'POST',body:JSON.stringify({p_execution_id:id})});}
 /** Ordinary claim-then-work claim. Both managed effects (HYPOTHESIS_UPDATE_BATCH, CONFIDENCE_BATCH) are excluded at compile time and rejected by the RPC: each is claimed, executed and completed inside its one-transaction execute command. There is no generic result-less completion left - every effect carries a typed durable result written by its own dedicated command. */
 async claim(id:string,effect:ClaimableIntelligenceEffect):Promise<boolean>{return this.booleanRpc('claim_post_response_intelligence_effect_v1',{p_execution_id:id,p_effect_key:effect});}
 async completeMemory(id:string,result:MemoryWriteResult):Promise<boolean>{return result.decision==='SKIP'?this.booleanRpc('complete_post_response_memory_write_effect_v1',{p_execution_id:id,p_result_code:'NO_FRESH_EVIDENCE',p_result_reference:null}):this.booleanRpc('complete_post_response_memory_write_effect_v1',{p_execution_id:id,p_result_code:'FRESH_EVIDENCE_CREATED',p_result_reference:result.evidenceId});}
 /** Persists the post-authority canonical outcome atomically with CLAIMED -> COMPLETED. Only the authorized intent is durable: no raw provider output, and no reason for a NOT_AUTHORIZED. */
 async completeIntent(id:string,result:HypothesisGenerationIntentExtractionResult):Promise<boolean>{return result.status==='AUTHORIZED'?this.booleanRpc('complete_post_response_intent_provider_effect_v1',{p_execution_id:id,p_result_code:'INTENT_AUTHORIZED',p_result_payload:result.intent}):this.booleanRpc('complete_post_response_intent_provider_effect_v1',{p_execution_id:id,p_result_code:'INTENT_NOT_AUTHORIZED',p_result_payload:null});}
 /** Persists the post-authority Association outcome atomically with CLAIMED -> COMPLETED on the canonical result_payload field. Only the exact authorized command batch is durable: no raw provider output and no rejected proposal. */
 async completeAssociation(id:string,result:DurableAssociationResult):Promise<boolean>{return result.code==='NO_ASSOCIATION'?this.booleanRpc('complete_post_response_association_provider_effect_v1',{p_execution_id:id,p_result_code:'NO_ASSOCIATION',p_result_payload:null}):this.booleanRpc('complete_post_response_association_provider_effect_v1',{p_execution_id:id,p_result_code:'AUTHORIZED_COMMANDS',p_result_payload:result.commands});}
 /** Persists the exact post-validation canonical candidate plan atomically with CLAIMED -> COMPLETED on the canonical result_payload field. Only accepted canonical candidates with their pre-assigned stable Hypothesis UUIDs are durable: no raw provider output, no rejected proposal, no rejection reason. */
 async completeCandidateProvider(id:string,result:DurableCandidateProviderResult):Promise<boolean>{return result.code==='NO_ACCEPTED_CANDIDATES'?this.booleanRpc('complete_post_response_candidate_provider_effect_v1',{p_execution_id:id,p_result_code:'NO_ACCEPTED_CANDIDATES',p_result_payload:null}):this.booleanRpc('complete_post_response_candidate_provider_effect_v1',{p_execution_id:id,p_result_code:'VALIDATED_CANDIDATES',p_result_payload:result.candidates});}
 /** Runs the ONE atomic server-side Hypothesis batch persistence command. The application supplies only the execution identity: the database reads the durable Candidate result itself, performs every create/attach/link write and the HYPOTHESIS_PERSISTENCE completion in one transaction, and rolls all of it back on any failure. */
 async persistHypothesisGeneration(id:string):Promise<boolean>{return this.booleanRpc('persist_post_response_hypothesis_generation_v1',{p_execution_id:id});}
 /** Runs the ONE managed A2.3c command. The application supplies only pre-generated audit/evaluation UUID identities - never a userId, sessionId, command payload, access token or user JWT: the database derives user/session from the execution and the commands from the durable ASSOCIATION_PROVIDER / AUTHORIZED_COMMANDS result, then claims, mutates, evaluates exact-version Confidence and completes HYPOTHESIS_UPDATE_BATCH in one transaction. Returns true only when UPDATES_APPLIED was durably written by this call. */
 async executeHypothesisUpdateBatch(id:string,invocationIds:ReadonlyArray<{updateId:string;confidenceEvaluationId:string}>):Promise<boolean>{return this.booleanRpc('execute_post_response_hypothesis_update_batch_v1',{p_execution_id:id,p_invocation_ids:invocationIds});}
 /** Runs the ONE managed QAN-AUD-06 Confidence-batch command. The application supplies only the execution identity - never a userId, sessionId, target ID, target version, Evidence, Confidence payload, access token or user JWT: the database derives the owner from the execution, the exact targets from the durable HYPOTHESIS_PERSISTENCE result, the frozen target versions from the canonical Hypothesis rows at first initialization, and the stable evaluation identities itself, then evaluates only unfinished items and completes CONFIDENCE_BATCH only when every target has a valid result. */
 async executeConfidenceBatch(id:string):Promise<ConfidenceBatchCommandStatus>{const value=await this.request<string>('rpc/execute_post_response_confidence_batch_v1',{method:'POST',body:JSON.stringify({p_execution_id:id})});return(CONFIDENCE_BATCH_COMMAND_STATUSES as readonly string[]).includes(value)?value as ConfidenceBatchCommandStatus:'NO_OP';}
 async finish(id:string,state:'COMPLETED'|'SKIPPED'|'QUARANTINED'|'FAILED',outcome:string,stage:string):Promise<boolean>{return this.booleanRpc('finish_post_response_intelligence_execution_v1',{p_execution_id:id,p_state:state,p_outcome_code:outcome,p_stage:stage});}
 private async booleanRpc(name:string,body:Record<string,unknown>):Promise<boolean>{const value=await this.request<boolean>(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)});return value===true;}
 private async request<T>(path:string,init:RequestInit):Promise<T>{const base=process.env.SUPABASE_URL?.replace(/\/$/u,''),key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)throw new Error('POST_RESPONSE_DATABASE_DISABLED');let response:Response;try{response=await fetch(`${base}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(5000)});}catch{throw new Error('POST_RESPONSE_DATABASE_UNAVAILABLE');}if(!response.ok)throw new Error('POST_RESPONSE_DATABASE_UNAVAILABLE');return response.status===204?undefined as T:response.json()as Promise<T>;}
}
