import{randomUUID}from'node:crypto';import{Inject,Injectable}from'@nestjs/common';import{BackgroundIntelligenceAuthorityService}from'../background-intelligence/background-intelligence-authority.service';import type{BackgroundIntelligenceExecutionContext}from'../background-intelligence/background-intelligence-authority.service';import{BackgroundIntelligenceEnrichmentService}from'../background-intelligence/background-intelligence-enrichment.service';import{HypothesisGenerationIntentExtractionService}from'../hypothesis/hypothesis-generation-intent-extraction.service';import type{AuthorizedHypothesisGenerationIntent}from'../hypothesis/hypothesis-generation-intent-authority.types';import{HypothesisGenerationRequestAssemblerService}from'../hypothesis/hypothesis-generation-request-assembler.service';import{HYPOTHESIS_CANDIDATE_GENERATOR,type BoundHypothesisCandidateGenerator}from'../hypothesis/hypothesis-candidate-generator-provider.types';import type{HypothesisEvidenceAssociationSnapshot}from'../hypothesis/hypothesis-evidence-association.types';import{isValidRuntimeEventEnvelope,type RuntimeEventEnvelope}from'../runtime-events/runtime-event.types';import{recoverAssociationResult,toDurableAssociationResult}from'./durable-association-result';import{recoverDurableIntentProviderResult}from'./durable-intent-provider-result';import{ModelAssistedHypothesisAssociationService}from'./model-assisted-hypothesis-association.service';import{PostResponseIntelligenceRepository}from'./post-response-intelligence.repository';import type{GenericIntelligenceEffect,IntelligenceEffect,IntelligenceExecution}from'./post-response-intelligence.types';

@Injectable()
export class PostResponseIntelligenceDispatcherService{
 constructor(private readonly ledger:PostResponseIntelligenceRepository,private readonly authority:BackgroundIntelligenceAuthorityService,private readonly enrichment:BackgroundIntelligenceEnrichmentService,private readonly extraction:HypothesisGenerationIntentExtractionService,private readonly assembler:HypothesisGenerationRequestAssemblerService,@Inject(HYPOTHESIS_CANDIDATE_GENERATOR)private readonly generator:BoundHypothesisCandidateGenerator,private readonly association:ModelAssistedHypothesisAssociationService){}
 async dispatch(raw:string):Promise<boolean>{let event:RuntimeEventEnvelope;try{event=JSON.parse(raw)as RuntimeEventEnvelope;}catch{return true;}if(!isValidRuntimeEventEnvelope(event))return true;if(event.event_type!=='ConversationTurnCompleted')return true;const v2=event.event_version==='2.0';const execution=await this.ledger.acquire({id:randomUUID(),eventId:event.event_id,userId:event.subject_user_id,sessionId:event.subject_session_id,sourceTurnId:event.subject_turn_id,eventVersion:event.event_version,processingPath:(event.payload.processing_path??null)as'FAST'|'DEEP'|null,safetyDisposition:v2?event.payload.safety_disposition as'ALLOW'|'GUIDED'|'BLOCK':null});if(execution.state!=='RUNNING')return true;const effects=await this.ledger.effects(execution.id);if(effects.some(effect=>effect.state==='CLAIMED'))return this.terminal(execution,'QUARANTINED','INDETERMINATE_EFFECT','EFFECT_RECOVERY');if(execution.attempt_count>=5)return this.terminal(execution,'QUARANTINED','MAX_ATTEMPTS','DELIVERY');if(!v2)return this.terminal(execution,'SKIPPED','LEGACY_UNSUPPORTED','VALIDATION');const authorized=await this.authority.authorize(event);if(authorized.outcome!=='AUTHORIZED'||!authorized.context)return this.terminal(execution,'QUARANTINED',authorized.outcome==='NOT_AUTHORIZED_OWNER_MISMATCH'?'CANONICAL_MISMATCH':'AUTHORITY_REJECTED','AUTHORITY');if(execution.safety_disposition!=='ALLOW')return this.terminal(execution,'SKIPPED','SAFETY_SKIPPED','SAFETY');const context=authorized.context;const turn=await this.enrichment.readCanonicalSourceTurn(context);if(turn.processing_path!==execution.processing_path)return this.terminal(execution,'QUARANTINED','CANONICAL_MISMATCH','CANONICAL_REREAD');
  const completed=new Set(effects.filter(effect=>effect.state==='COMPLETED').map(effect=>effect.effect_key));
  const persistedMemory=effects.find(effect=>effect.effect_key==='MEMORY_WRITE'&&effect.state==='COMPLETED');let freshEvidenceId:string|undefined;
  if(persistedMemory){if(persistedMemory.result_code==='NO_FRESH_EVIDENCE'&&persistedMemory.result_reference===null){}else if(persistedMemory.result_code==='FRESH_EVIDENCE_CREATED'&&validEvidenceReference(persistedMemory.result_reference))freshEvidenceId=persistedMemory.result_reference;else return this.terminal(execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_RECOVERY');}
  else{if(!await this.ledger.claim(execution.id,'MEMORY_WRITE'))return true;try{const result=await this.enrichment.evaluateAndWriteMemory(context,turn.content);if(!await this.ledger.completeMemory(execution.id,result))return true;completed.add('MEMORY_WRITE');if(result.decision==='WRITE')freshEvidenceId=result.evidenceId;}catch{return this.terminal(execution,'QUARANTINED','INDETERMINATE_EFFECT','MEMORY_WRITE');}}
  // A durably COMPLETED ASSOCIATION_PROVIDER carries its own post-authority result, so a redelivery recovers the exact NO_ASSOCIATION or authorized command batch instead of losing it with the process. Recovery is deterministic: a legacy result-less completion, a malformed payload, or a payload bound to different Evidence is INDETERMINATE and quarantines - never a provider replay, never inference. A2.3a only persists and recovers; the recovered commands mutate nothing yet.
  if(!freshEvidenceId&&completed.has('ASSOCIATION_PROVIDER'))return this.terminal(execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_RECOVERY');
  if(freshEvidenceId){if(completed.has('ASSOCIATION_PROVIDER')){if(recoverAssociationResult(effects.find(effect=>effect.effect_key==='ASSOCIATION_PROVIDER')!,freshEvidenceId).status==='INDETERMINATE')return this.terminal(execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_RECOVERY');}else{const preparation=await this.association.prepare(context,freshEvidenceId);if(preparation.status==='NOT_AUTHORIZED')return this.terminal(execution,'QUARANTINED','AUTHORITY_REJECTED','ASSOCIATION_PREPARATION');if(preparation.status==='PREPARED'&&!await this.completeAssociation(execution,completed,event,context,preparation.snapshot))return true;}}
  const assessment=await this.enrichment.evaluateGenerationEligibility(context,turn.content,'ALLOW');if(!('triggerClassification'in assessment))return this.terminal(execution,'SKIPPED','NOT_ELIGIBLE','ELIGIBILITY');
  // A durably COMPLETED INTENT_PROVIDER carries its own post-authority result, so a redelivery recovers the exact authorized intent instead of losing it with the process and false-skipping. A fresh run persists the typed result atomically with completion before consuming it.
  const persistedIntent=effects.find(effect=>effect.effect_key==='INTENT_PROVIDER'&&effect.state==='COMPLETED');let intent:AuthorizedHypothesisGenerationIntent;
  if(persistedIntent){const recovered=recoverDurableIntentProviderResult(persistedIntent,execution);if(recovered.status==='INDETERMINATE')return this.terminal(execution,'QUARANTINED','INDETERMINATE_EFFECT','INTENT_RECOVERY');if(recovered.status==='NOT_AUTHORIZED')return this.terminal(execution,'SKIPPED','INTENT_NOT_AUTHORIZED','INTENT');intent=recovered.intent;}
  else{if(!await this.ledger.claim(execution.id,'INTENT_PROVIDER'))return true;let extracted:Awaited<ReturnType<HypothesisGenerationIntentExtractionService['extract']>>;try{extracted=await this.extraction.extract({currentTurn:{id:turn.id,sessionId:turn.session_id,role:'USER',status:'COMPLETED',text:turn.content},eligibility:assessment.eligibility,triggerReason:assessment.triggerClassification.reason,eligibleEvidence:assessment.eligibleEvidence});}catch{await this.ledger.finish(execution.id,'QUARANTINED','INDETERMINATE_EFFECT','INTENT_PROVIDER');return true;}
   if(!await this.ledger.completeIntent(execution.id,extracted))return true;completed.add('INTENT_PROVIDER');if(extracted.status!=='AUTHORIZED')return this.terminal(execution,'SKIPPED','INTENT_NOT_AUTHORIZED','INTENT');intent=extracted.intent;}
  const assembled=this.assembler.assemble(intent);if(assembled.status!=='READY')return this.terminal(execution,'SKIPPED','ASSEMBLY_NOT_READY','ASSEMBLY');
  let accepted:readonly{id:string}[]=[];const generationAlreadyCompleted=completed.has('CANDIDATE_PROVIDER')&&completed.has('HYPOTHESIS_PERSISTENCE');if(!await this.claimBoth(execution,completed,'CANDIDATE_PROVIDER','HYPOTHESIS_PERSISTENCE'))return true;if(!generationAlreadyCompleted)try{accepted=(await this.enrichment.generateHypotheses(context,assembled.request,this.generator)).accepted;await this.ledger.complete(execution.id,'CANDIDATE_PROVIDER');await this.ledger.complete(execution.id,'HYPOTHESIS_PERSISTENCE');}catch{return this.terminal(execution,'QUARANTINED','INDETERMINATE_EFFECT','GENERATION');}
  if(!await this.effect(execution,'CONFIDENCE_BATCH',completed,async()=>{for(const item of accepted){try{await this.enrichment.evaluateHypothesisConfidence(context,item.id);}catch{}}}))return true;return this.terminal(execution,'COMPLETED','COMPLETED','DONE');}
 private async effect(execution:IntelligenceExecution,key:GenericIntelligenceEffect,completed:Set<IntelligenceEffect>,work:()=>Promise<unknown>):Promise<boolean>{if(completed.has(key))return true;if(!await this.ledger.claim(execution.id,key))return false;try{await work();const done=await this.ledger.complete(execution.id,key);if(done)completed.add(key);return done;}catch{await this.ledger.finish(execution.id,'QUARANTINED','INDETERMINATE_EFFECT',key);return false;}}
 // Result-aware completion for a newly executed ASSOCIATION_PROVIDER effect. The
 // provider is invoked at most once; a successful post-authority outcome persists
 // its typed durable result atomically with completion, and any non-success
 // (including a NOT_AUTHORIZED reauthorization) fails closed as indeterminate -
 // no Hypothesis mutation, no provider replay.
 private async completeAssociation(execution:IntelligenceExecution,completed:Set<IntelligenceEffect>,event:RuntimeEventEnvelope,context:BackgroundIntelligenceExecutionContext,snapshot:HypothesisEvidenceAssociationSnapshot):Promise<boolean>{if(!await this.ledger.claim(execution.id,'ASSOCIATION_PROVIDER'))return false;let durable;try{durable=toDurableAssociationResult(await this.association.proposeAndAuthorize(event,context,snapshot));}catch{await this.ledger.finish(execution.id,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_PROVIDER');return false;}if(!durable){await this.ledger.finish(execution.id,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_PROVIDER');return false;}const done=await this.ledger.completeAssociation(execution.id,durable);if(done)completed.add('ASSOCIATION_PROVIDER');return done;}
 private async claimBoth(execution:IntelligenceExecution,completed:Set<IntelligenceEffect>,a:IntelligenceEffect,b:IntelligenceEffect):Promise<boolean>{if(completed.has(a)&&completed.has(b))return true;if(completed.has(a)!==completed.has(b)){await this.ledger.finish(execution.id,'QUARANTINED','INDETERMINATE_EFFECT','GENERATION_PAIR');return false;}if(!await this.ledger.claim(execution.id,a))return false;if(!await this.ledger.claim(execution.id,b)){await this.ledger.finish(execution.id,'QUARANTINED','INDETERMINATE_EFFECT',b);return false;}return true;}
 private async terminal(execution:IntelligenceExecution,state:'COMPLETED'|'SKIPPED'|'QUARANTINED',outcome:string,stage:string):Promise<true>{await this.ledger.finish(execution.id,state,outcome,stage);return true;}
}
function validEvidenceReference(value:string|null):value is `memory:${string}`{return typeof value==='string'&&/^memory:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(value);}
