import { BackgroundIntelligenceAuthorityService } from '../background-intelligence/background-intelligence-authority.service';
import { BackgroundIntelligenceContextFactory } from '../background-intelligence/background-intelligence-context.factory';
import type { BackgroundIntelligenceDataApiService } from '../background-intelligence/background-intelligence-data-api.service';
import type { BackgroundIntelligenceEnrichmentService } from '../background-intelligence/background-intelligence-enrichment.service';
import type { HypothesisGenerationIntentExtractionService } from '../hypothesis/hypothesis-generation-intent-extraction.service';
import type { HypothesisGenerationRequestAssemblerService } from '../hypothesis/hypothesis-generation-request-assembler.service';
import type { BoundHypothesisCandidateGenerator } from '../hypothesis/hypothesis-candidate-generator-provider.types';
import type { RuntimeEventEnvelope } from '../runtime-events/runtime-event.types';
import { recoverDurableIntentProviderResult } from './durable-intent-provider-result';
import type { ModelAssistedHypothesisAssociationService } from './model-assisted-hypothesis-association.service';
import { PostResponseIntelligenceDispatcherService } from './post-response-intelligence-dispatcher.service';
import type { PostResponseIntelligenceRepository } from './post-response-intelligence.repository';

const id={event:'10000000-0000-4000-8000-000000000001',user:'10000000-0000-4000-8000-000000000002',session:'10000000-0000-4000-8000-000000000003',turn:'10000000-0000-4000-8000-000000000004',execution:'10000000-0000-4000-8000-000000000005',evidence:'10000000-0000-4000-8000-000000000006'};
const event=(version:'1.0'|'2.0'='2.0',safety:'ALLOW'|'GUIDED'|'BLOCK'='ALLOW'):RuntimeEventEnvelope=>({event_id:id.event,event_type:'ConversationTurnCompleted',event_version:version,occurred_at:'2026-01-01T00:00:00Z',producer:'conversation-service',subject_user_id:id.user,subject_session_id:id.session,subject_turn_id:id.turn,correlation_id:null,causation_id:null,classification:'SENSITIVE',schema_ref:`qandeel.runtime.conversation-turn-completed.v${version==='2.0'?'2':'1'}`,payload:{user_id:id.user,session_id:id.session,source_turn_id:id.turn,terminal_status:'COMPLETED',processing_path:'FAST',routing_reason:'FAST_DEFAULT',orchestration_id:null,...(version==='2.0'?{safety_disposition:safety}:{})},contains_content:false,retention_class:'OPERATIONAL_EVENT_V1'});

describe('PostResponseIntelligenceDispatcherService',()=>{
 const setup=(overrides:{effects?:unknown[];state?:string}={})=>{const ledger={acquire:jest.fn().mockResolvedValue({id:id.execution,event_id:id.event,user_id:id.user,session_id:id.session,source_turn_id:id.turn,event_version:'2.0',processing_path:'FAST',safety_disposition:'ALLOW',state:overrides.state??'RUNNING',attempt_count:1}),effects:jest.fn().mockResolvedValue(overrides.effects??[]),claim:jest.fn().mockResolvedValue(true),complete:jest.fn().mockResolvedValue(true),completeMemory:jest.fn().mockResolvedValue(true),completeIntent:jest.fn().mockResolvedValue(true),completeAssociation:jest.fn().mockResolvedValue(true),completeCandidateProvider:jest.fn().mockResolvedValue(true),persistHypothesisGeneration:jest.fn().mockResolvedValue(true),finish:jest.fn().mockResolvedValue(true)}as unknown as jest.Mocked<PostResponseIntelligenceRepository>;const ownership={findSession:jest.fn().mockResolvedValue({id:id.session,status:'ACTIVE',channel:'TEXT'}),findSourceTurn:jest.fn().mockResolvedValue({id:id.turn,session_id:id.session,role:'USER',status:'COMPLETED',source_turn_id:null}),findCompletedAssistant:jest.fn().mockResolvedValue({id:'assistant',session_id:id.session,role:'ASSISTANT',status:'COMPLETED',source_turn_id:id.turn})}as unknown as BackgroundIntelligenceDataApiService;const authority=new BackgroundIntelligenceAuthorityService(new BackgroundIntelligenceContextFactory(),ownership);const enrichment={readCanonicalSourceTurn:jest.fn().mockResolvedValue({id:id.turn,session_id:id.session,role:'USER',status:'COMPLETED',source_turn_id:null,content:'Why do I repeat this pattern?',processing_path:'FAST',routing_reason:'FAST_DEFAULT'}),evaluateAndWriteMemory:jest.fn().mockResolvedValue({decision:'SKIP',reason:'NO_SUPPORTED_EXPLICIT_PATTERN'}),evaluateGenerationEligibility:jest.fn().mockResolvedValue({eligibility:{status:'NOT_ELIGIBLE',reason:'NO_TRIGGER'}}),generateHypothesisCandidatePlan:jest.fn(),evaluateHypothesisConfidence:jest.fn(),applyAuthorizedHypothesisUpdate:jest.fn()}as unknown as jest.Mocked<BackgroundIntelligenceEnrichmentService>;const extraction={extract:jest.fn()}as unknown as jest.Mocked<HypothesisGenerationIntentExtractionService>;const assembler={assemble:jest.fn()}as unknown as jest.Mocked<HypothesisGenerationRequestAssemblerService>;const generator={generate:jest.fn()}as BoundHypothesisCandidateGenerator;const association={prepare:jest.fn(),proposeAndAuthorize:jest.fn()}as unknown as jest.Mocked<ModelAssistedHypothesisAssociationService>;return{ledger,enrichment,association,extraction,assembler,service:new PostResponseIntelligenceDispatcherService(ledger,authority,enrichment,extraction,assembler,generator,association)};};
 const intent=()=>({problem:{text:'Why do I repeat this pattern?',source:'CURRENT_USER_TURN' as const,sourceTurnId:id.turn},domain:'GENERAL' as const,scope:{kind:'CONVERSATION_SESSION' as const,sessionId:id.session,serialized:`CONVERSATION_SESSION:${id.session}`},evidenceIds:[`memory:${id.evidence}`]});
 const eligible=()=>({eligibility:{status:'ELIGIBLE',reason:'TRIGGER_AND_EVIDENCE_AVAILABLE'},triggerClassification:{status:'TRIGGERED',reason:'RECURRING_PATTERN'},eligibleEvidence:[{evidenceId:`memory:${id.evidence}`,originatingMemoryId:id.evidence}]});
 const eligibleRun=(s:ReturnType<typeof setup>)=>{s.enrichment.evaluateGenerationEligibility.mockResolvedValue(eligible() as never);s.assembler.assemble.mockReturnValue({status:'READY',request:{problem:intent().problem.text,domain:'GENERAL',scope:intent().scope.serialized,evidenceIds:intent().evidenceIds}} as never);s.enrichment.generateHypothesisCandidatePlan.mockResolvedValue({code:'NO_ACCEPTED_CANDIDATES'} as never);return s;};
 const intentEffect=(overrides:Record<string,unknown>={})=>({effect_key:'INTENT_PROVIDER',state:'COMPLETED',result_code:'INTENT_AUTHORIZED',result_reference:null,result_payload:intent(),...overrides});
 const memorySkipEffect=()=>({effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'NO_FRESH_EVIDENCE',result_reference:null,result_payload:null});
 const durableCandidate=(overrides:Record<string,unknown>={})=>({hypothesisId:'10000000-0000-4000-8000-00000000000a',statement:'I procrastinate when goals feel vague.',type:'CAUSAL' as const,domain:'GENERAL' as const,scope:`CONVERSATION_SESSION:${id.session}`,supportingEvidenceIds:[`memory:${id.evidence}`],contradictingEvidenceIds:[],assumptions:[],disconfirmingConditions:[],...overrides});
 const candidateEffect=(overrides:Record<string,unknown>={})=>({effect_key:'CANDIDATE_PROVIDER',state:'COMPLETED',result_code:'VALIDATED_CANDIDATES',result_reference:null,result_payload:[durableCandidate()],...overrides});
 const persistenceEffect=(overrides:Record<string,unknown>={})=>({effect_key:'HYPOTHESIS_PERSISTENCE',state:'COMPLETED',result_code:'HYPOTHESES_PERSISTED',result_reference:null,result_payload:['10000000-0000-4000-8000-00000000000a'],...overrides});
 it('ACKs failed/cancelled and poison messages without background effects',async()=>{const s=setup(),failed={...event('1.0'),event_type:'ConversationTurnFailed',schema_ref:'qandeel.runtime.conversation-turn-failed.v1',payload:{...event('1.0').payload,terminal_status:'FAILED'}};await expect(s.service.dispatch(JSON.stringify(failed))).resolves.toBe(true);await expect(s.service.dispatch('{')).resolves.toBe(true);expect(s.ledger.acquire).not.toHaveBeenCalled();});
 it('terminalizes legacy Completed v1 without inferring Safety',async()=>{const s=setup();s.ledger.acquire.mockResolvedValueOnce({id:id.execution,event_id:id.event,user_id:id.user,session_id:id.session,source_turn_id:id.turn,event_version:'1.0',processing_path:'FAST',safety_disposition:null,state:'RUNNING',attempt_count:1});await s.service.dispatch(JSON.stringify(event('1.0')));expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'SKIPPED','LEGACY_UNSUPPORTED','VALIDATION');expect(s.enrichment.readCanonicalSourceTurn).not.toHaveBeenCalled();});
 it.each(['GUIDED','BLOCK']as const)('skips %s before enrichment',async safety=>{const s=setup();s.ledger.acquire.mockResolvedValueOnce({id:id.execution,event_id:id.event,user_id:id.user,session_id:id.session,source_turn_id:id.turn,event_version:'2.0',processing_path:'FAST',safety_disposition:safety,state:'RUNNING',attempt_count:1});await s.service.dispatch(JSON.stringify(event('2.0',safety)));expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'SKIPPED','SAFETY_SKIPPED','SAFETY');expect(s.enrichment.evaluateAndWriteMemory).not.toHaveBeenCalled();});
 it.each(['MEMORY_WRITE','INTENT_PROVIDER','ASSOCIATION_PROVIDER']as const)('quarantines a redelivery with an indeterminate claimed %s effect',async effectKey=>{const s=setup({effects:[{effect_key:effectKey,state:'CLAIMED'}]});await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','EFFECT_RECOVERY');expect(s.enrichment.readCanonicalSourceTurn).not.toHaveBeenCalled();expect(s.ledger.claim).not.toHaveBeenCalled();expect(s.extraction.extract).not.toHaveBeenCalled();expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();});
 it('claims Memory once and durably records SKIP before continuing',async()=>{const s=setup();await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.claim).toHaveBeenCalledWith(id.execution,'MEMORY_WRITE');expect(s.ledger.completeMemory).toHaveBeenCalledWith(id.execution,{decision:'SKIP',reason:'NO_SUPPORTED_EXPLICIT_PATTERN'});expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'SKIPPED','NOT_ELIGIBLE','ELIGIBILITY');});
 it('completes a prepared fresh-Evidence association through the typed durable result and calls the provider once',async()=>{const s=setup(),snapshot={contractVersion:1,freshEvidence:{evidenceId:`memory:${id.execution}`,evidenceKind:'USER_STATED_FACT',statement:'fact',source:'USER_STATED'},candidateHypotheses:[{hypothesisId:id.event,hypothesisVersion:1,statement:'candidate',type:'CAUSAL',domain:'GENERAL',scope:`CONVERSATION_SESSION:${id.session}`,assumptions:[],disconfirmingConditions:[],alreadySupporting:false,alreadyContradicting:false}],maxAssociationCount:4}as const;s.enrichment.evaluateAndWriteMemory.mockResolvedValueOnce({decision:'WRITE',type:'GOAL',memoryId:id.execution,evidenceId:`memory:${id.execution}`});s.association.prepare.mockResolvedValueOnce({status:'PREPARED',snapshot}as never);s.association.proposeAndAuthorize.mockResolvedValueOnce({status:'NO_ASSOCIATION'}as never);await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.claim).toHaveBeenCalledWith(id.execution,'ASSOCIATION_PROVIDER');expect(s.association.proposeAndAuthorize).toHaveBeenCalledTimes(1);expect(s.ledger.completeAssociation).toHaveBeenCalledWith(id.execution,{code:'NO_ASSOCIATION'});expect(s.ledger.complete).not.toHaveBeenCalledWith(id.execution,'ASSOCIATION_PROVIDER');});
 it('persists the exact authorized command batch through the typed durable completion',async()=>{const s=setup(),commands=[{hypothesisId:id.user,expectedVersion:7,evidenceId:`memory:${id.execution}`,evidenceRole:'SUPPORTING' as const},{hypothesisId:id.turn,expectedVersion:2,evidenceId:`memory:${id.execution}`,evidenceRole:'CONTRADICTING' as const}];s.enrichment.evaluateAndWriteMemory.mockResolvedValueOnce({decision:'WRITE',type:'GOAL',memoryId:id.execution,evidenceId:`memory:${id.execution}`});s.association.prepare.mockResolvedValueOnce({status:'PREPARED',snapshot:{} as never});s.association.proposeAndAuthorize.mockResolvedValueOnce({status:'AUTHORIZED',commands}as never);await s.service.dispatch(JSON.stringify(event()));expect(s.association.proposeAndAuthorize).toHaveBeenCalledTimes(1);expect(s.ledger.completeAssociation).toHaveBeenCalledWith(id.execution,{code:'AUTHORIZED_COMMANDS',commands});expect(s.ledger.complete).not.toHaveBeenCalledWith(id.execution,'ASSOCIATION_PROVIDER');expect(s.enrichment.applyAuthorizedHypothesisUpdate).not.toHaveBeenCalled();});
 it('does not claim or call the provider for EMPTY preparation',async()=>{const s=setup();s.enrichment.evaluateAndWriteMemory.mockResolvedValueOnce({decision:'WRITE',type:'GOAL',memoryId:id.execution,evidenceId:`memory:${id.execution}`});s.association.prepare.mockResolvedValueOnce({status:'EMPTY',reason:'NO_SAME_SESSION_HYPOTHESES'});await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.claim).not.toHaveBeenCalledWith(id.execution,'ASSOCIATION_PROVIDER');expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();});
 it('recovers a completed valid durable association result on redelivery without a provider call',async()=>{for(const assoc of[{result_code:'NO_ASSOCIATION',result_reference:null,result_payload:null},{result_code:'AUTHORIZED_COMMANDS',result_reference:null,result_payload:[{hypothesisId:id.user,expectedVersion:4,evidenceId:`memory:${id.execution}`,evidenceRole:'SUPPORTING'}]}]){const s=setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'FRESH_EVIDENCE_CREATED',result_reference:`memory:${id.execution}`,result_payload:null},{effect_key:'ASSOCIATION_PROVIDER',state:'COMPLETED',...assoc}as never]});await s.service.dispatch(JSON.stringify(event()));expect(s.enrichment.evaluateAndWriteMemory).not.toHaveBeenCalled();expect(s.association.prepare).not.toHaveBeenCalled();expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();
  // A2.3b isolation: recovered AUTHORIZED_COMMANDS still cause zero Hypothesis
  // mutations - the server-authorized update boundary is never dispatched here.
  expect(s.enrichment.applyAuthorizedHypothesisUpdate).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'SKIPPED','NOT_ELIGIBLE','ELIGIBILITY');}});
 it('quarantines a legacy completed association effect that has no durable result instead of continuing',async()=>{const s=setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'FRESH_EVIDENCE_CREATED',result_reference:`memory:${id.execution}`,result_payload:null},{effect_key:'ASSOCIATION_PROVIDER',state:'COMPLETED',result_code:null,result_reference:null,result_payload:null}]});await s.service.dispatch(JSON.stringify(event()));expect(s.enrichment.evaluateAndWriteMemory).not.toHaveBeenCalled();expect(s.association.prepare).not.toHaveBeenCalled();expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_RECOVERY');});
 it('quarantines a completed association effect when no durable fresh Memory evidence exists',async()=>{const s=setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'NO_FRESH_EVIDENCE',result_reference:null,result_payload:null},{effect_key:'ASSOCIATION_PROVIDER',state:'COMPLETED',result_code:'NO_ASSOCIATION',result_reference:null,result_payload:null}]});await s.service.dispatch(JSON.stringify(event()));expect(s.association.prepare).not.toHaveBeenCalled();expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_RECOVERY');});
 it.each([{result_code:'AUTHORIZED_COMMANDS',result_reference:null,result_payload:[]},{result_code:'AUTHORIZED_COMMANDS',result_reference:null,result_payload:[{hypothesisId:id.user,expectedVersion:1,evidenceId:`memory:${id.session}`,evidenceRole:'SUPPORTING'}]},{result_code:'AUTHORIZED_COMMANDS',result_reference:null,result_payload:[{hypothesisId:'not-a-uuid',expectedVersion:1,evidenceId:`memory:${id.execution}`,evidenceRole:'SUPPORTING'}]},{result_code:'AUTHORIZED_COMMANDS',result_reference:`memory:${id.execution}`,result_payload:[{hypothesisId:id.user,expectedVersion:1,evidenceId:`memory:${id.execution}`,evidenceRole:'SUPPORTING'}]},{result_code:'NO_ASSOCIATION',result_reference:null,result_payload:[{hypothesisId:id.user,expectedVersion:1,evidenceId:`memory:${id.execution}`,evidenceRole:'SUPPORTING'}]}])('quarantines an invalid completed association durable result without provider replay: %o',async assoc=>{const s=setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'FRESH_EVIDENCE_CREATED',result_reference:`memory:${id.execution}`,result_payload:null},{effect_key:'ASSOCIATION_PROVIDER',state:'COMPLETED',...assoc}as never]});await s.service.dispatch(JSON.stringify(event()));expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_RECOVERY');});
 it('recovers durable Memory SKIP after crash without false quarantine or provider call',async()=>{const s=setup();s.enrichment.evaluateGenerationEligibility.mockRejectedValueOnce(new Error('simulated crash'));await expect(s.service.dispatch(JSON.stringify(event()))).rejects.toThrow('simulated crash');expect(s.ledger.completeMemory).toHaveBeenCalledWith(id.execution,{decision:'SKIP',reason:'NO_SUPPORTED_EXPLICIT_PATTERN'});s.ledger.effects.mockResolvedValueOnce([{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'NO_FRESH_EVIDENCE',result_reference:null}] as never);s.enrichment.evaluateAndWriteMemory.mockClear();s.ledger.finish.mockClear();await s.service.dispatch(JSON.stringify(event()));expect(s.enrichment.evaluateAndWriteMemory).not.toHaveBeenCalled();expect(s.association.prepare).not.toHaveBeenCalled();expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'SKIPPED','NOT_ELIGIBLE','ELIGIBILITY');});
 it('recovers the exact durable Evidence reference after crash without replaying Memory',async()=>{const s=setup();s.enrichment.evaluateAndWriteMemory.mockResolvedValueOnce({decision:'WRITE',type:'GOAL',memoryId:id.execution,evidenceId:`memory:${id.execution}`});s.association.prepare.mockRejectedValueOnce(new Error('simulated crash before Association claim'));await expect(s.service.dispatch(JSON.stringify(event()))).rejects.toThrow('simulated crash before Association claim');expect(s.ledger.completeMemory).toHaveBeenCalledWith(id.execution,expect.objectContaining({evidenceId:`memory:${id.execution}`}));s.ledger.effects.mockResolvedValueOnce([{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'FRESH_EVIDENCE_CREATED',result_reference:`memory:${id.execution}`}] as never);s.enrichment.evaluateAndWriteMemory.mockClear();s.association.prepare.mockResolvedValueOnce({status:'PREPARED',snapshot:{} as never});s.association.proposeAndAuthorize.mockResolvedValueOnce({status:'AUTHORIZED',commands:[{hypothesisId:id.user,expectedVersion:3,evidenceId:`memory:${id.execution}`,evidenceRole:'SUPPORTING'}]}as never);await s.service.dispatch(JSON.stringify(event()));expect(s.enrichment.evaluateAndWriteMemory).not.toHaveBeenCalled();expect(s.association.prepare).toHaveBeenLastCalledWith(expect.anything(),`memory:${id.execution}`);expect(s.association.proposeAndAuthorize).toHaveBeenCalledTimes(1);expect(s.ledger.completeAssociation).toHaveBeenCalledWith(id.execution,{code:'AUTHORIZED_COMMANDS',commands:[{hypothesisId:id.user,expectedVersion:3,evidenceId:`memory:${id.execution}`,evidenceRole:'SUPPORTING'}]});});
 it('safely reruns EMPTY preparation after crash without calling the provider',async()=>{const s=setup();s.enrichment.evaluateAndWriteMemory.mockResolvedValueOnce({decision:'WRITE',type:'GOAL',memoryId:id.execution,evidenceId:`memory:${id.execution}`});s.association.prepare.mockResolvedValueOnce({status:'EMPTY',reason:'NO_SAME_SESSION_HYPOTHESES'});s.enrichment.evaluateGenerationEligibility.mockRejectedValueOnce(new Error('simulated crash'));await expect(s.service.dispatch(JSON.stringify(event()))).rejects.toThrow('simulated crash');s.ledger.effects.mockResolvedValueOnce([{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'FRESH_EVIDENCE_CREATED',result_reference:`memory:${id.execution}`}] as never);s.enrichment.evaluateAndWriteMemory.mockClear();s.association.prepare.mockResolvedValueOnce({status:'EMPTY',reason:'NO_SAME_SESSION_HYPOTHESES'});s.ledger.finish.mockClear();await s.service.dispatch(JSON.stringify(event()));expect(s.enrichment.evaluateAndWriteMemory).not.toHaveBeenCalled();expect(s.association.prepare).toHaveBeenCalledTimes(2);expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'SKIPPED','NOT_ELIGIBLE','ELIGIBILITY');});
 it.each([{result_code:null,result_reference:null},{result_code:'FRESH_EVIDENCE_CREATED',result_reference:null},{result_code:'NO_FRESH_EVIDENCE',result_reference:`memory:${id.execution}`},{result_code:'FRESH_EVIDENCE_CREATED',result_reference:'memory:invalid'}])('quarantines a legacy or invalid completed Memory result without inference: %o',async result=>{const s=setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED',...result}]});await s.service.dispatch(JSON.stringify(event()));expect(s.enrichment.evaluateAndWriteMemory).not.toHaveBeenCalled();expect(s.association.prepare).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_RECOVERY');});
 it('fails closed before provider when recovered Evidence is no longer eligible',async()=>{const s=setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'FRESH_EVIDENCE_CREATED',result_reference:`memory:${id.execution}`}]});s.association.prepare.mockResolvedValueOnce({status:'NOT_AUTHORIZED',reason:'FRESH_EVIDENCE_NOT_ELIGIBLE'});await s.service.dispatch(JSON.stringify(event()));expect(s.association.proposeAndAuthorize).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','AUTHORITY_REJECTED','ASSOCIATION_PREPARATION');});
 it('quarantines provider failure before downstream generation or mutation',async()=>{const s=setup();s.enrichment.evaluateAndWriteMemory.mockResolvedValueOnce({decision:'WRITE',type:'GOAL',memoryId:id.execution,evidenceId:`memory:${id.execution}`});s.association.prepare.mockResolvedValueOnce({status:'PREPARED',snapshot:{} as never});s.association.proposeAndAuthorize.mockRejectedValueOnce(new Error('provider failed'));await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_PROVIDER');expect(s.ledger.completeAssociation).not.toHaveBeenCalled();expect(s.enrichment.evaluateGenerationEligibility).not.toHaveBeenCalled();expect(s.enrichment.generateHypothesisCandidatePlan).not.toHaveBeenCalled();expect(s.enrichment.evaluateHypothesisConfidence).not.toHaveBeenCalled();});
 it('persists the exact canonical authorized intent atomically with completion and only then consumes it',async()=>{const s=eligibleRun(setup());s.extraction.extract.mockResolvedValue({status:'AUTHORIZED',intent:intent()} as never);await s.service.dispatch(JSON.stringify(event()));expect(s.extraction.extract).toHaveBeenCalledTimes(1);expect(s.ledger.claim).toHaveBeenCalledWith(id.execution,'INTENT_PROVIDER');expect(s.ledger.completeIntent).toHaveBeenCalledTimes(1);expect(s.ledger.completeIntent).toHaveBeenCalledWith(id.execution,{status:'AUTHORIZED',intent:intent()});expect(s.ledger.complete).not.toHaveBeenCalledWith(id.execution,'INTENT_PROVIDER');expect(s.assembler.assemble).toHaveBeenCalledWith(intent());expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'COMPLETED','COMPLETED','DONE');});
 it('persists a durable NOT_AUTHORIZED before skipping and carries no provider detail',async()=>{const s=eligibleRun(setup());s.extraction.extract.mockResolvedValue({status:'NOT_AUTHORIZED',reason:'PROVIDER_TIMEOUT'} as never);await s.service.dispatch(JSON.stringify(event()));expect(s.extraction.extract).toHaveBeenCalledTimes(1);expect(s.ledger.completeIntent).toHaveBeenCalledWith(id.execution,{status:'NOT_AUTHORIZED',reason:'PROVIDER_TIMEOUT'});expect(s.ledger.completeIntent.mock.invocationCallOrder[0]).toBeLessThan(s.ledger.finish.mock.invocationCallOrder[0]);expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'SKIPPED','INTENT_NOT_AUTHORIZED','INTENT');expect(s.assembler.assemble).not.toHaveBeenCalled();});
 it('recovers a durably completed AUTHORIZED intent on redelivery without recalling the provider or false-skipping',async()=>{const s=eligibleRun(setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'NO_FRESH_EVIDENCE',result_reference:null,result_payload:null},intentEffect()]}));await s.service.dispatch(JSON.stringify(event()));expect(s.extraction.extract).not.toHaveBeenCalled();expect(s.ledger.claim).not.toHaveBeenCalledWith(id.execution,'INTENT_PROVIDER');expect(s.ledger.completeIntent).not.toHaveBeenCalled();expect(s.assembler.assemble).toHaveBeenCalledWith(intent());expect(s.ledger.finish).not.toHaveBeenCalledWith(id.execution,'SKIPPED','INTENT_NOT_AUTHORIZED','INTENT');expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'COMPLETED','COMPLETED','DONE');});
 it('replays a durably completed NOT_AUTHORIZED as a deterministic skip without recalling the provider',async()=>{const s=eligibleRun(setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'NO_FRESH_EVIDENCE',result_reference:null,result_payload:null},intentEffect({result_code:'INTENT_NOT_AUTHORIZED',result_payload:null})]}));await s.service.dispatch(JSON.stringify(event()));expect(s.extraction.extract).not.toHaveBeenCalled();expect(s.assembler.assemble).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'SKIPPED','INTENT_NOT_AUTHORIZED','INTENT');});
 it.each([['a legacy pre-0029 null result',{result_code:null,result_payload:null}],['a malformed authorized payload',{result_payload:{problem:'nope'}}],['a payload recorded for another turn',{result_payload:{...intent(),problem:{...intent().problem,sourceTurnId:'20000000-0000-4000-8000-000000000004'}}}],['an impossible code/payload pairing',{result_code:'INTENT_NOT_AUTHORIZED'}]])('quarantines %s as indeterminate instead of skipping',async(_label,overrides)=>{const s=eligibleRun(setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'NO_FRESH_EVIDENCE',result_reference:null,result_payload:null},intentEffect(overrides as Record<string,unknown>)]}));await s.service.dispatch(JSON.stringify(event()));expect(s.extraction.extract).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','INTENT_RECOVERY');expect(s.ledger.finish).not.toHaveBeenCalledWith(id.execution,'SKIPPED','INTENT_NOT_AUTHORIZED','INTENT');});
 it('reproduces the pre-0029 false skip and refuses to repeat it',async()=>{const legacy={effect_key:'INTENT_PROVIDER' as const,state:'COMPLETED' as const,result_code:null,result_reference:null,result_payload:null};
  // Pre-0029 the generic result-less RPC completed INTENT_PROVIDER, so a redelivery saw a COMPLETED effect, correctly skipped the provider, and found its local intent gone - the exact durable state below yielded a false SKIPPED / INTENT_NOT_AUTHORIZED.
  const preFixOutcome=(localIntent:{status:string}|undefined)=>!localIntent||localIntent.status!=='AUTHORIZED'?'INTENT_NOT_AUTHORIZED':'COMPLETED';
  expect(preFixOutcome({status:'AUTHORIZED'})).toBe('COMPLETED');expect(preFixOutcome(undefined)).toBe('INTENT_NOT_AUTHORIZED');
  expect(recoverDurableIntentProviderResult(legacy,{session_id:id.session,source_turn_id:id.turn})).toEqual({status:'INDETERMINATE'});
  const s=eligibleRun(setup({effects:[{effect_key:'MEMORY_WRITE',state:'COMPLETED',result_code:'NO_FRESH_EVIDENCE',result_reference:null,result_payload:null},legacy]}));await s.service.dispatch(JSON.stringify(event()));
  expect(s.extraction.extract).not.toHaveBeenCalled();expect(s.ledger.finish).not.toHaveBeenCalledWith(id.execution,'SKIPPED','INTENT_NOT_AUTHORIZED','INTENT');expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','INTENT_RECOVERY');});
 it('quarantines an intent provider failure without a durable result',async()=>{const s=eligibleRun(setup());s.extraction.extract.mockRejectedValue(new Error('provider exploded'));await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.completeIntent).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','INTENT_PROVIDER');});
 it('quarantines failed post-provider reauthorization before downstream generation or mutation',async()=>{const s=setup();s.enrichment.evaluateAndWriteMemory.mockResolvedValueOnce({decision:'WRITE',type:'GOAL',memoryId:id.execution,evidenceId:`memory:${id.execution}`});s.association.prepare.mockResolvedValueOnce({status:'PREPARED',snapshot:{} as never});s.association.proposeAndAuthorize.mockResolvedValueOnce({status:'NOT_AUTHORIZED',reason:'TARGET_OUT_OF_UNIVERSE'}as never);await s.service.dispatch(JSON.stringify(event()));expect(s.ledger.complete).not.toHaveBeenCalledWith(id.execution,'ASSOCIATION_PROVIDER');expect(s.ledger.completeAssociation).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','ASSOCIATION_PROVIDER');expect(s.enrichment.evaluateGenerationEligibility).not.toHaveBeenCalled();expect(s.enrichment.generateHypothesisCandidatePlan).not.toHaveBeenCalled();expect(s.enrichment.evaluateHypothesisConfidence).not.toHaveBeenCalled();});

 describe('Finding 08 - durable sequential generation',()=>{
  const secondId='10000000-0000-4000-8000-00000000000b';
  it('persists the exact typed candidate plan, runs the one atomic persistence command, and feeds Confidence the exact IDs in order',async()=>{const s=eligibleRun(setup());s.extraction.extract.mockResolvedValue({status:'AUTHORIZED',intent:intent()} as never);const plan={code:'VALIDATED_CANDIDATES' as const,candidates:[durableCandidate(),durableCandidate({hypothesisId:secondId,statement:'A second distinct statement.'})]};s.enrichment.generateHypothesisCandidatePlan.mockResolvedValue(plan as never);await s.service.dispatch(JSON.stringify(event()));
   expect(s.enrichment.generateHypothesisCandidatePlan).toHaveBeenCalledTimes(1);expect(s.ledger.claim).toHaveBeenCalledWith(id.execution,'CANDIDATE_PROVIDER');expect(s.ledger.completeCandidateProvider).toHaveBeenCalledWith(id.execution,plan);expect(s.ledger.claim).toHaveBeenCalledWith(id.execution,'HYPOTHESIS_PERSISTENCE');expect(s.ledger.persistHypothesisGeneration).toHaveBeenCalledTimes(1);expect(s.ledger.persistHypothesisGeneration).toHaveBeenCalledWith(id.execution);
   // The generic completion is never used for either generation effect, and the application performs no create/attach/link loop of its own.
   expect(s.ledger.complete).not.toHaveBeenCalledWith(id.execution,'CANDIDATE_PROVIDER');expect(s.ledger.complete).not.toHaveBeenCalledWith(id.execution,'HYPOTHESIS_PERSISTENCE');
   expect(s.enrichment.evaluateHypothesisConfidence).toHaveBeenNthCalledWith(1,expect.anything(),plan.candidates[0].hypothesisId);expect(s.enrichment.evaluateHypothesisConfidence).toHaveBeenNthCalledWith(2,expect.anything(),secondId);expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'COMPLETED','COMPLETED','DONE');});
  it('completes a NO_ACCEPTED_CANDIDATES plan through the typed command and still runs the durable no-op persistence',async()=>{const s=eligibleRun(setup());s.extraction.extract.mockResolvedValue({status:'AUTHORIZED',intent:intent()} as never);await s.service.dispatch(JSON.stringify(event()));
   expect(s.ledger.completeCandidateProvider).toHaveBeenCalledWith(id.execution,{code:'NO_ACCEPTED_CANDIDATES'});expect(s.ledger.persistHypothesisGeneration).toHaveBeenCalledWith(id.execution);expect(s.enrichment.evaluateHypothesisConfidence).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'COMPLETED','COMPLETED','DONE');});
  it('quarantines a candidate provider failure after claim without a fabricated result',async()=>{const s=eligibleRun(setup());s.extraction.extract.mockResolvedValue({status:'AUTHORIZED',intent:intent()} as never);s.enrichment.generateHypothesisCandidatePlan.mockRejectedValue(new Error('provider exploded'));await s.service.dispatch(JSON.stringify(event()));
   expect(s.ledger.completeCandidateProvider).not.toHaveBeenCalled();expect(s.ledger.persistHypothesisGeneration).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','CANDIDATE_PROVIDER');});
  it('recovers a completed typed candidate plan and continues to atomic persistence with zero provider calls',async()=>{const s=eligibleRun(setup({effects:[memorySkipEffect(),intentEffect(),candidateEffect()]}));await s.service.dispatch(JSON.stringify(event()));
   expect(s.enrichment.generateHypothesisCandidatePlan).not.toHaveBeenCalled();expect(s.ledger.completeCandidateProvider).not.toHaveBeenCalled();expect(s.ledger.claim).toHaveBeenCalledWith(id.execution,'HYPOTHESIS_PERSISTENCE');expect(s.ledger.persistHypothesisGeneration).toHaveBeenCalledWith(id.execution);expect(s.enrichment.evaluateHypothesisConfidence).toHaveBeenCalledWith(expect.anything(),durableCandidate().hypothesisId);expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'COMPLETED','COMPLETED','DONE');});
  it('recovers a durable NO_ACCEPTED_CANDIDATES without a provider call or a Hypothesis write',async()=>{const s=eligibleRun(setup({effects:[memorySkipEffect(),intentEffect(),candidateEffect({result_code:'NO_ACCEPTED_CANDIDATES',result_payload:null})]}));await s.service.dispatch(JSON.stringify(event()));
   expect(s.enrichment.generateHypothesisCandidatePlan).not.toHaveBeenCalled();expect(s.ledger.persistHypothesisGeneration).toHaveBeenCalledWith(id.execution);expect(s.enrichment.evaluateHypothesisConfidence).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'COMPLETED','COMPLETED','DONE');});
  it.each([['a legacy pre-0033 null candidate result',{result_code:null,result_payload:null}],['a non-array payload',{result_payload:{}}],['a plan bound to another domain',{result_payload:[durableCandidate({domain:'WORK'})]}],['a plan bound to another scope',{result_payload:[durableCandidate({scope:'CONVERSATION_SESSION:20000000-0000-4000-8000-000000000003'})]}],['Evidence outside the durable Intent set',{result_payload:[durableCandidate({supportingEvidenceIds:[`memory:${id.user}`]})]}],['an impossible code/payload pairing',{result_code:'NO_ACCEPTED_CANDIDATES'}]])('quarantines %s as indeterminate without provider replay',async(_label,overrides)=>{const s=eligibleRun(setup({effects:[memorySkipEffect(),intentEffect(),candidateEffect(overrides as Record<string,unknown>)]}));await s.service.dispatch(JSON.stringify(event()));
   expect(s.enrichment.generateHypothesisCandidatePlan).not.toHaveBeenCalled();expect(s.ledger.persistHypothesisGeneration).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','CANDIDATE_RECOVERY');});
  it('reproduces the pre-0033 lost accepted set and refuses to repeat it',async()=>{
   // Pre-0033 both generation effects completed generically with no result, so a redelivery saw them COMPLETED, correctly refused to replay, and found its local accepted IDs gone - Confidence silently received accepted=[].
   const preFixAccepted=(local:readonly{id:string}[]|undefined)=>local??[];
   expect(preFixAccepted(undefined)).toEqual([]);expect(preFixAccepted([{id:secondId}])).toEqual([{id:secondId}]);
   const s=eligibleRun(setup({effects:[memorySkipEffect(),intentEffect(),candidateEffect({result_code:null,result_payload:null}),persistenceEffect({result_code:null,result_payload:null})]}));await s.service.dispatch(JSON.stringify(event()));
   expect(s.enrichment.generateHypothesisCandidatePlan).not.toHaveBeenCalled();expect(s.enrichment.evaluateHypothesisConfidence).not.toHaveBeenCalled();expect(s.ledger.finish).not.toHaveBeenCalledWith(id.execution,'COMPLETED','COMPLETED','DONE');expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','CANDIDATE_RECOVERY');});
  it('recovers the exact persisted Hypothesis IDs on redelivery with zero writes and zero provider calls',async()=>{const s=eligibleRun(setup({effects:[memorySkipEffect(),intentEffect(),candidateEffect(),persistenceEffect()]}));await s.service.dispatch(JSON.stringify(event()));
   expect(s.enrichment.generateHypothesisCandidatePlan).not.toHaveBeenCalled();expect(s.ledger.claim).not.toHaveBeenCalledWith(id.execution,'CANDIDATE_PROVIDER');expect(s.ledger.claim).not.toHaveBeenCalledWith(id.execution,'HYPOTHESIS_PERSISTENCE');expect(s.ledger.persistHypothesisGeneration).not.toHaveBeenCalled();
   // The recovered accepted set is the exact durable persisted-ID list, never an empty fallback.
   expect(s.enrichment.evaluateHypothesisConfidence).toHaveBeenCalledWith(expect.anything(),durableCandidate().hypothesisId);expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'COMPLETED','COMPLETED','DONE');});
  it.each([['a legacy null persistence result',candidateEffect(),{result_code:null,result_payload:null}],['an ID list from another plan',candidateEffect(),{result_payload:[secondId]}],['a reordered ID list',candidateEffect({result_payload:[durableCandidate(),durableCandidate({hypothesisId:secondId,statement:'A second distinct statement.'})]}),{result_payload:[secondId,durableCandidate().hypothesisId]}],['NO_HYPOTHESES_PERSISTED paired with a validated plan',candidateEffect(),{result_code:'NO_HYPOTHESES_PERSISTED',result_payload:null}],['HYPOTHESES_PERSISTED paired with an empty plan',candidateEffect({result_code:'NO_ACCEPTED_CANDIDATES',result_payload:null}),{}]])('quarantines %s as a candidate/persistence mismatch',async(_label,candidateRow,persistenceOverrides)=>{const s=eligibleRun(setup({effects:[memorySkipEffect(),intentEffect(),candidateRow as never,persistenceEffect(persistenceOverrides as Record<string,unknown>)]}));await s.service.dispatch(JSON.stringify(event()));
   expect(s.enrichment.generateHypothesisCandidatePlan).not.toHaveBeenCalled();expect(s.enrichment.evaluateHypothesisConfidence).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','HYPOTHESIS_PERSISTENCE_RECOVERY');});
  it('quarantines a completed persistence whose candidate effect never completed',async()=>{const s=eligibleRun(setup({effects:[memorySkipEffect(),intentEffect(),persistenceEffect()]}));await s.service.dispatch(JSON.stringify(event()));
   expect(s.enrichment.generateHypothesisCandidatePlan).not.toHaveBeenCalled();expect(s.ledger.persistHypothesisGeneration).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','HYPOTHESIS_PERSISTENCE_RECOVERY');});
  it('quarantines an atomic persistence failure and leaves the rollback to the database',async()=>{const s=eligibleRun(setup({effects:[memorySkipEffect(),intentEffect(),candidateEffect()]}));s.ledger.persistHypothesisGeneration.mockRejectedValue(new Error('POST_RESPONSE_DATABASE_UNAVAILABLE'));await s.service.dispatch(JSON.stringify(event()));
   expect(s.enrichment.evaluateHypothesisConfidence).not.toHaveBeenCalled();expect(s.ledger.finish).toHaveBeenCalledWith(id.execution,'QUARANTINED','INDETERMINATE_EFFECT','HYPOTHESIS_PERSISTENCE');});
 });
});
