import{Injectable}from'@nestjs/common';import{createClient,type RedisClientType}from'redis';import type{PostResponseRedisConsumer,RedisRuntimeEventEntry}from'./post-response-intelligence.types';
@Injectable()
export class RedisPostResponseConsumer implements PostResponseRedisConsumer{
 readonly enabled=Boolean(process.env.REDIS_URL);private client:RedisClientType|undefined;private readonly stream=process.env.RUNTIME_EVENT_STREAM??'qandeel:runtime-events:v1';private readonly group=process.env.POST_RESPONSE_CONSUMER_GROUP??'qandeel-post-response-intelligence-v1';private readonly consumer=process.env.POST_RESPONSE_CONSUMER_NAME??`api-${process.pid}`;
 async connect():Promise<void>{if(!process.env.REDIS_URL)throw new Error('REDIS_DISABLED');await this.close();const client=createClient({url:process.env.REDIS_URL});this.client=client;client.on('error',()=>undefined);try{await client.connect();try{await client.xGroupCreate(this.stream,this.group,'0',{MKSTREAM:true});}catch(error){if(!String(error).includes('BUSYGROUP'))throw error;}}catch(error){if(client.isOpen)client.destroy();if(this.client===client)this.client=undefined;throw error;}}
 async read():Promise<readonly RedisRuntimeEventEntry[]>{if(!this.client?.isReady)throw new Error('REDIS_UNAVAILABLE');const streams=await this.client.xReadGroup(this.group,this.consumer,{key:this.stream,id:'>'},{COUNT:10,BLOCK:1000});return streams?.flatMap(stream=>stream.messages.flatMap((message:{id:string;message:Record<string,string>})=>typeof message.message.envelope==='string'?[{id:message.id,envelope:message.message.envelope}]:[]))??[];}
 async reclaim():Promise<readonly RedisRuntimeEventEntry[]>{if(!this.client?.isReady)throw new Error('REDIS_UNAVAILABLE');const claimed=await this.client.xAutoClaim(this.stream,this.group,this.consumer,30000,'0-0',{COUNT:10});return claimed.messages.flatMap(message=>message&&typeof message.message.envelope==='string'?[{id:message.id,envelope:message.message.envelope}]:[]);}
 async ack(id:string):Promise<void>{if(!this.client?.isReady)throw new Error('REDIS_UNAVAILABLE');await this.client.xAck(this.stream,this.group,id);}
 async close():Promise<void>{const client=this.client;this.client=undefined;if(!client?.isOpen)return;try{await client.quit();}catch{if(client.isOpen)client.destroy();}}
}
