import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { decideDispatch } from './push-dispatch-decision';
import { apnsPayload, fcmBody } from './push-transport';
import type { ClaimedAttempt, PlatformMessage } from './push.types';

/**
 * A3-02 — the proof's platform payloads are the SERVER's, not a hand-written copy.
 *
 * The device proof (A301ProofRoot, `qandeel://a301-proof/push/…`) cannot receive a real FCM / APNs message on CI (no
 * credential exists there — record §20 names that as a physical-device Exit Gate). It therefore presents, as a local
 * notification (Android) or a simulator push (iOS), EXACTLY the message this production code renders: the revalidated
 * decision, the disclosure level, the bounded projection, the channel, the collapse id and the data. This test builds
 * that file from production code and fails if the committed file differs; `A302_WRITE_PROOF_PAYLOADS=1` rewrites it.
 *
 * Every sentence below is SYNTHETIC test text (the P3 `FIXTURE_ONLY` class), never Product copy.
 */
const FILE = join(__dirname, '../../../mobile/src/integration/__validation__/a302-platform-payloads.json');
const NOW = Date.parse('2026-10-04T12:00:00.000Z'); // 15:00 in Africa/Cairo: outside the default Quiet Hours

const prefs = (lockAccount: string) => ({
  proactive: 'ALLOW', shared_alerts: true, public_interactions: true, public_discovery: false, introductions_alerts: true,
  account_updates: true, quiet_hours_enabled: true, quiet_hours_start: 1380, quiet_hours_end: 480, snooze_until: null,
  lock_qandeel: 'L1', lock_shared: 'L2', lock_public: 'L2', lock_discovery: 'L1', lock_introductions: 'L0', lock_reminders: 'L2',
  lock_account: lockAccount, lock_security: 'L2',
});

function claim(id: string, lockAccount: string, locale: 'ar' | 'en', sentence: { ar: string; en: string }): ClaimedAttempt {
  const at = new Date(NOW - 60_000).toISOString();
  return {
    attemptId: `proof-${id}`, userId: 'proof-reader', attemptCount: 0, reevaluation: false,
    device: { id: 'proof-device', platform: 'ANDROID', transport: 'FCM', apnsEnvironment: null, token: 'proof', status: 'ACTIVE', osPermission: 'GRANTED', timeZone: 'Africa/Cairo', locale },
    item: {
      id, category: 'SYSTEM', kind: 'ACCOUNT', interruption_class: 2, critical: false, requested: false, context_kind: 'ACCOUNT',
      context_ref: null, context_label_ar: null, context_label_en: null, entry_destination: 'GENERAL_SETTINGS', entry_ref: 'SECURITY',
      speaker: 'PRODUCT', body_ar: sentence.ar, body_en: sentence.en,
      secondary_ar: 'نص اختبار: معاينة المحتوى', secondary_en: 'Fixture: a content preview', actionable: false, disclosure_max: 'L3',
      member_count: 1, occurred_at: at, last_occurred_at: at, expires_at: null, withdrawn_at: null, attention: 'NEW',
      presented_in_app_at: null, interruption_settled_at: null, created_at: at,
    },
    preferences: prefs(lockAccount), muted: false, evidence: [], now: new Date(NOW).toISOString(),
  };
}

/** The proof cases. Their ids are the ones the proof root's validation stand-in answers `open` for (valid / stale / unknown). */
export const PROOF_CASES = Object.freeze({
  valid: { id: 'a3020000-0000-4000-8000-000000000001', lock: 'L2', sentence: { ar: 'نص اختبار: تحديث في الحساب', en: 'Fixture: an account update' } },
  l0: { id: 'a3020000-0000-4000-8000-000000000002', lock: 'L0', sentence: { ar: 'نص اختبار: لا يظهر على شاشة القفل', en: 'Fixture: never on the Lock Screen' } },
  stale: { id: 'a3020000-0000-4000-8000-000000000003', lock: 'L2', sentence: { ar: 'نص اختبار: شيء لم يعد متاحًا', en: 'Fixture: something no longer there' } },
  foreign: { id: 'a3020000-0000-4000-8000-000000000004', lock: 'L2', sentence: { ar: 'نص اختبار: عنصر لحساب آخر', en: 'Fixture: another account item' } },
});

function build() {
  const out: Record<string, unknown> = {
    note: 'GENERATED by apps/api/src/push/push-proof-payloads.spec.ts from production code. VALIDATION ONLY. Do not edit.',
  };
  for (const [name, { id, lock, sentence }] of Object.entries(PROOF_CASES)) {
    const byLocale: Record<string, unknown> = {};
    for (const locale of ['ar', 'en'] as const) {
      const decision = decideDispatch(claim(id, lock, locale, sentence), NOW);
      if (decision.kind !== 'SEND') throw new Error(`proof case ${name} is not sendable: ${JSON.stringify(decision)}`);
      const m: PlatformMessage = decision.message;
      const fcm = fcmBody('<device-token>', m) as { message: { notification: unknown; data: unknown; android: { notification: { channel_id: string } } } };
      byLocale[locale] = {
        level: m.level,
        android: { channelId: fcm.message.android.notification.channel_id, notification: fcm.message.notification, data: fcm.message.data },
        apns: { 'Simulator Target Bundle': 'com.qandeel.mobile', ...apnsPayload(m) },
      };
    }
    out[name] = byLocale;
  }
  return out;
}

describe('A3-02 proof payloads are rendered by production code', () => {
  it('the committed proof payloads equal what the server renders now', () => {
    const expected = `${JSON.stringify(build(), null, 2)}\n`;
    if (process.env.A302_WRITE_PROOF_PAYLOADS === '1') writeFileSync(FILE, expected);
    expect(readFileSync(FILE, 'utf8')).toBe(expected);
  });

  it('L0 says nothing of the account; L2 never carries the L3 preview', () => {
    const built = build() as Record<string, Record<string, { level: string; android: { notification: { title?: string; body: string } } }>>;
    expect(built.l0.en.level).toBe('L0');
    expect(built.l0.en.android.notification).toEqual({ body: 'New notification' });
    expect(built.valid.en.level).toBe('L2');
    expect(built.valid.en.android.notification).toEqual({ title: 'Account', body: 'Fixture: an account update' });
  });
});
