import { RuntimeEventPublisher } from './runtime-event.publisher';
import type { RuntimeEventAdminRepository } from './runtime-event-admin.repository';
import type { RuntimeEventTransport } from './runtime-event-transport';
import type { ClaimedRuntimeEvent } from './runtime-event.types';
import type { TelemetryService } from '../observability/telemetry.service';

const IDS={event:'10000000-0000-4000-8000-000000000001',user:'10000000-0000-4000-8000-000000000002',session:'10000000-0000-4000-8000-000000000003',turn:'10000000-0000-4000-8000-000000000004',claim:'10000000-0000-4000-8000-000000000005'};
const event=(overrides:Partial<ClaimedRuntimeEvent>={}):ClaimedRuntimeEvent=>({event_id:IDS.event,event_type:'ConversationTurnCompleted',event_version:'1.0',occurred_at:'2026-01-01T00:00:00Z',producer:'conversation-service',subject_user_id:IDS.user,subject_session_id:IDS.session,subject_turn_id:IDS.turn,correlation_id:null,causation_id:null,classification:'SENSITIVE',schema_ref:'qandeel.runtime.conversation-turn-completed.v1',payload:{user_id:IDS.user,session_id:IDS.session,source_turn_id:IDS.turn,terminal_status:'COMPLETED',processing_path:'FAST',routing_reason:'FAST_DEFAULT',orchestration_id:null},contains_content:false,retention_class:'OPERATIONAL_EVENT_V1',status:'IN_FLIGHT',attempt_count:1,claim_token:IDS.claim,claimed_at:'2026-01-01T00:00:01Z',lease_expires_at:'2026-01-01T00:00:31Z',...overrides});

describe('RuntimeEventPublisher',()=>{
 const setup=(claimed:ClaimedRuntimeEvent[],publish:jest.Mock=jest.fn().mockResolvedValue('1-0'),telemetry:Partial<TelemetryService>={recordPublisherOperation:jest.fn()})=>{const repository={enabled:true,claim:jest.fn().mockResolvedValue(claimed),ack:jest.fn().mockResolvedValue(true),retry:jest.fn().mockResolvedValue(true),quarantine:jest.fn().mockResolvedValue(true)}as unknown as jest.Mocked<RuntimeEventAdminRepository>,transport={connect:jest.fn(),publish,close:jest.fn()}as unknown as jest.Mocked<RuntimeEventTransport>,publisher=new RuntimeEventPublisher(repository,transport,telemetry as TelemetryService);return{repository,transport,publisher,telemetry};};
 it('is disabled without both configurations and never starts test polling',async()=>{const oldRedis=process.env.REDIS_URL;delete process.env.REDIS_URL;const{publisher,transport}=setup([]);expect(publisher.enabled).toBe(false);await publisher.onModuleInit();expect(transport.connect).not.toHaveBeenCalled();if(oldRedis)process.env.REDIS_URL=oldRedis;});
 it('publishes only the canonical privacy-minimized envelope then acknowledges',async()=>{const s=setup([event()]);await s.publisher.processOnce();expect(s.transport.publish).toHaveBeenCalledWith(expect.not.objectContaining({status:expect.anything(),claim_token:expect.anything(),attempt_count:expect.anything()}));const published=s.transport.publish.mock.calls[0][0]as unknown as Record<string,unknown>,keys=[...Object.keys(published),...Object.keys(published.payload as object)].map(x=>x.toLowerCase());for(const forbidden of ['content','prompt','idempotency_key','authorization','cookie'])expect(keys).not.toContain(forbidden);expect(published.contains_content).toBe(false);expect(s.repository.ack).toHaveBeenCalledWith(IDS.event,IDS.claim,'1-0');});
 it.each([
  ['schema ref',event({schema_ref:'wrong'})],
  ['type/status',event({event_type:'ConversationTurnFailed',schema_ref:'qandeel.runtime.conversation-turn-failed.v1'})],
  ['missing key',event({payload:{user_id:IDS.user,session_id:IDS.session,source_turn_id:IDS.turn,terminal_status:'COMPLETED',processing_path:'FAST',routing_reason:'FAST_DEFAULT'}})],
  ['invalid UUID',event({subject_turn_id:'not-a-uuid'})],
  ['subject mismatch',event({subject_turn_id:'20000000-0000-4000-8000-000000000004'})],
  ['extra key',event({payload:{...event().payload,extra:'forbidden'}})],
 ])('quarantines malformed %s before transport',async(_name,invalid)=>{const s=setup([invalid]);await s.publisher.processOnce();expect(s.repository.quarantine).toHaveBeenCalledWith(IDS.event,IDS.claim,'INVALID_EVENT');expect(s.transport.publish).not.toHaveBeenCalled();});
 it('retries transient failures with the same event ID and bounded telemetry only',async()=>{const s=setup([event()],jest.fn().mockRejectedValue(new Error('raw secret')));await s.publisher.processOnce();expect(s.repository.retry).toHaveBeenCalledWith(IDS.event,IDS.claim,'TRANSPORT_UNAVAILABLE',expect.any(Date));expect(s.repository.quarantine).not.toHaveBeenCalled();expect((s.telemetry.recordPublisherOperation as jest.Mock).mock.calls.flat()).not.toEqual(expect.arrayContaining([IDS.event,IDS.user,IDS.session,IDS.turn]));});
 it('quarantines max-attempt events without publishing',async()=>{const max=event({attempt_count:6});const s=setup([max]);await s.publisher.processOnce();expect(s.repository.quarantine).toHaveBeenCalledWith(IDS.event,IDS.claim,'MAX_ATTEMPTS_EXCEEDED');expect(s.transport.publish).not.toHaveBeenCalled();});
 it('keeps delivery behavior authoritative when operational telemetry throws',async()=>{const telemetry={recordPublisherOperation:jest.fn(()=>{throw new Error('telemetry unavailable');})},s=setup([event()],undefined,telemetry);await s.publisher.processOnce();expect(s.transport.publish).toHaveBeenCalledTimes(1);expect(s.repository.ack).toHaveBeenCalledWith(IDS.event,IDS.claim,'1-0');expect(s.repository.retry).not.toHaveBeenCalled();});
 it('does not double-run overlapping polling iterations',async()=>{let release!:()=>void;const pending=new Promise<ClaimedRuntimeEvent[]>(resolve=>{release=()=>resolve([]);}),s=setup([]);s.repository.claim.mockReturnValue(pending);const first=s.publisher.processOnce(),second=s.publisher.processOnce();release();await Promise.all([first,second]);expect(s.repository.claim).toHaveBeenCalledTimes(1);});
});
