import { BackgroundIntelligenceAuthorityService, BackgroundIntelligenceExecutionContext, type BackgroundIntelligenceExecutionContext as ExecutionContext } from './background-intelligence-authority.service';
import { BackgroundIntelligenceContextFactory, BackgroundIntelligenceEventContext } from './background-intelligence-context.factory';
import { BackgroundIntelligenceDataApiService, type BackgroundConversationSessionState, type BackgroundConversationTurnState } from './background-intelligence-data-api.service';
import type { RuntimeEventEnvelope } from '../runtime-events/runtime-event.types';

const IDS={event:'10000000-0000-4000-8000-000000000001',user:'10000000-0000-4000-8000-000000000002',session:'10000000-0000-4000-8000-000000000003',turn:'10000000-0000-4000-8000-000000000004'};
const event:RuntimeEventEnvelope={event_id:IDS.event,event_type:'ConversationTurnCompleted',event_version:'1.0',occurred_at:'2026-01-01T00:00:00Z',producer:'conversation-service',subject_user_id:IDS.user,subject_session_id:IDS.session,subject_turn_id:IDS.turn,correlation_id:null,causation_id:null,classification:'SENSITIVE',schema_ref:'qandeel.runtime.conversation-turn-completed.v1',payload:{user_id:IDS.user,session_id:IDS.session,source_turn_id:IDS.turn,terminal_status:'COMPLETED',processing_path:'FAST',routing_reason:'FAST_DEFAULT',orchestration_id:null},contains_content:false,retention_class:'OPERATIONAL_EVENT_V1'};
const factory=new BackgroundIntelligenceContextFactory(),ownership=factory.create(event) as BackgroundIntelligenceEventContext;
const session:BackgroundConversationSessionState={id:IDS.session,status:'ACTIVE',channel:'TEXT'},source:BackgroundConversationTurnState={id:IDS.turn,session_id:IDS.session,role:'USER',status:'COMPLETED',source_turn_id:null},assistant:BackgroundConversationTurnState={id:'10000000-0000-4000-8000-000000000005',session_id:IDS.session,role:'ASSISTANT',status:'COMPLETED',source_turn_id:IDS.turn};
async function authorize():Promise<ExecutionContext>{const dataApi={findSession:jest.fn().mockResolvedValue(session),findSourceTurn:jest.fn().mockResolvedValue(source),findCompletedAssistant:jest.fn().mockResolvedValue(assistant)}as unknown as jest.Mocked<BackgroundIntelligenceDataApiService>,result=await new BackgroundIntelligenceAuthorityService(factory,dataApi).authorize(event);if(result.outcome!=='AUTHORIZED'||!result.context)throw new Error('test authority issuance failed');return result.context;}

describe('BackgroundIntelligenceDataApiService',()=>{
 const saved={url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY};
 beforeEach(()=>{process.env.SUPABASE_URL='https://database.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='SENTINEL_SERVICE_ROLE';jest.spyOn(global,'fetch').mockResolvedValue({ok:true,status:200,json:async()=>[]}as Response);});
 afterEach(()=>{jest.restoreAllMocks();if(saved.url===undefined)delete process.env.SUPABASE_URL;else process.env.SUPABASE_URL=saved.url;if(saved.key===undefined)delete process.env.SUPABASE_SERVICE_ROLE_KEY;else process.env.SUPABASE_SERVICE_ROLE_KEY=saved.key;});
 it('accepts the validated event context only for explicitly scoped ownership reads',async()=>{const service=new BackgroundIntelligenceDataApiService();await service.findSession(ownership);await service.findSourceTurn(ownership);await service.findCompletedAssistant(ownership);for(const[url]of(fetch as jest.Mock).mock.calls)expect(new URL(url).searchParams.get('user_id')).toBe(`eq.${ownership.userId}`);expect(new URL((fetch as jest.Mock).mock.calls[1][0]).searchParams.get('session_id')).toBe(`eq.${ownership.sessionId}`);expect(new URL((fetch as jest.Mock).mock.calls[1][0]).searchParams.get('id')).toBe(`eq.${ownership.sourceTurnId}`);expect(new URL((fetch as jest.Mock).mock.calls[2][0]).searchParams.get('source_turn_id')).toBe(`eq.${ownership.sourceTurnId}`);});
 it('allows an authority-issued execution context to force the owner on the Memory write',async()=>{(fetch as jest.Mock).mockResolvedValueOnce({ok:true,status:200,json:async()=>[{id:'memory-a'}]}as Response);const service=new BackgroundIntelligenceDataApiService(),context=await authorize();await service.createMemory(context,{id:'memory-a',type:'GOAL',content:'private',source:'USER_STATED',confidence:1,importance:1,status:'ACTIVE',user_id:'user-b'}as never);const init=(fetch as jest.Mock).mock.calls[0][1]as RequestInit;expect(JSON.parse(init.body as string)).toMatchObject({id:'memory-a',user_id:context.userId,scope:'USER'});expect(JSON.parse(init.body as string).user_id).not.toBe('user-b');});
 it('rejects pre-authorization context, spread copies, and prototype forgeries for writes',async()=>{const service=new BackgroundIntelligenceDataApiService(),authorized=await authorize();for(const forged of [ownership,{...authorized},Object.create(BackgroundIntelligenceExecutionContext.prototype)])await expect(service.createMemory(forged as ExecutionContext,{ }as never)).rejects.toThrow('BACKGROUND_INTELLIGENCE_AUTHORITY_REQUIRED');expect(fetch).not.toHaveBeenCalled();});
 it('rejects spread copies and prototype forgeries for ownership reads',async()=>{const service=new BackgroundIntelligenceDataApiService();for(const forged of [{...ownership},Object.create(BackgroundIntelligenceEventContext.prototype)])await expect(service.findSession(forged as BackgroundIntelligenceEventContext)).rejects.toThrow('BACKGROUND_INTELLIGENCE_EVENT_CONTEXT_REQUIRED');expect(fetch).not.toHaveBeenCalled();});
 it('keeps service-role credentials internal and failures sanitized',async()=>{const service=new BackgroundIntelligenceDataApiService();(fetch as jest.Mock).mockRejectedValueOnce(new Error('raw secret'));await expect(service.findSession(ownership)).rejects.toThrow('BACKGROUND_INTELLIGENCE_DATABASE_UNAVAILABLE');expect(JSON.stringify(ownership)).not.toContain('SENTINEL_SERVICE_ROLE');});
});
