import { BackgroundIntelligenceAuthorityService,BackgroundIntelligenceExecutionContext } from'./background-intelligence-authority.service';import{BackgroundIntelligenceContextFactory}from'./background-intelligence-context.factory';import{BackgroundIntelligenceEnrichmentService}from'./background-intelligence-enrichment.service';import type{BackgroundIntelligenceDataApiService}from'./background-intelligence-data-api.service';import{MemoryWriteEvaluatorService}from'../memory/memory-write-evaluator.service';import{HypothesisGenerationTriggerClassificationService}from'../hypothesis/hypothesis-generation-trigger-classification.service';import type{RuntimeEventEnvelope}from'../runtime-events/runtime-event.types';
import{BackgroundIntelligenceModule}from'./background-intelligence.module';import{BackgroundIntelligenceDataApiService as RawDataApi}from'./background-intelligence-data-api.service';
const ids={event:'10000000-0000-4000-8000-000000000001',user:'10000000-0000-4000-8000-000000000002',session:'10000000-0000-4000-8000-000000000003',turn:'10000000-0000-4000-8000-000000000004'},event:RuntimeEventEnvelope={event_id:ids.event,event_type:'ConversationTurnCompleted',event_version:'1.0',occurred_at:'2026-01-01T00:00:00Z',producer:'conversation-service',subject_user_id:ids.user,subject_session_id:ids.session,subject_turn_id:ids.turn,correlation_id:null,causation_id:null,classification:'SENSITIVE',schema_ref:'qandeel.runtime.conversation-turn-completed.v1',payload:{user_id:ids.user,session_id:ids.session,source_turn_id:ids.turn,terminal_status:'COMPLETED',processing_path:'FAST',routing_reason:'FAST_DEFAULT',orchestration_id:null},contains_content:false,retention_class:'OPERATIONAL_EVENT_V1'};
async function context(){const ownership={findSession:jest.fn().mockResolvedValue({id:ids.session,status:'ACTIVE',channel:'TEXT'}),findSourceTurn:jest.fn().mockResolvedValue({id:ids.turn,session_id:ids.session,role:'USER',status:'COMPLETED',source_turn_id:null}),findCompletedAssistant:jest.fn().mockResolvedValue({id:'a',session_id:ids.session,role:'ASSISTANT',status:'COMPLETED',source_turn_id:ids.turn})}as unknown as BackgroundIntelligenceDataApiService,result=await new BackgroundIntelligenceAuthorityService(new BackgroundIntelligenceContextFactory(),ownership).authorize(event);if(!result.context)throw new Error('authority failed');return result.context;}
const memory=(overrides:Record<string,unknown>={})=>({id:'20000000-0000-4000-8000-000000000001',user_id:ids.user,scope:'USER',type:'GOAL',content:'My goal is ship.',source:'USER_STATED',confidence:.95,importance:.85,status:'ACTIVE',version:1,created_at:'2026-01-01T00:00:00Z',updated_at:'2026-01-02T00:00:00Z',expires_at:null,supersedes_memory_id:null,...overrides});
describe('BackgroundIntelligenceEnrichmentService',()=>{const setup=(overrides:Record<string,unknown>={})=>{const data={readCanonicalSourceTurn:jest.fn(),listActiveMemories:jest.fn().mockResolvedValue([]),createMemory:jest.fn().mockResolvedValue(memory()),listActiveHypotheses:jest.fn().mockResolvedValue([]),findHypothesis:jest.fn(),createSystemHypothesis:jest.fn(),attachHypothesisEvidence:jest.fn(),linkCompetingHypotheses:jest.fn(),createConfidenceEvaluation:jest.fn(),...overrides}as unknown as jest.Mocked<BackgroundIntelligenceDataApiService>;return{data,service:new BackgroundIntelligenceEnrichmentService(data,new MemoryWriteEvaluatorService(),new HypothesisGenerationTriggerClassificationService())};};
 it('rejects pre-authorization, spread, and prototype-forged contexts before repository use',async()=>{const{service,data}=setup(),valid=await context(),pre=new BackgroundIntelligenceContextFactory().create(event);for(const forged of[pre,{...valid},Object.create(BackgroundIntelligenceExecutionContext.prototype)])await expect(service.listEligibleEvidence(forged as never)).rejects.toThrow('BACKGROUND_INTELLIGENCE_AUTHORITY_REQUIRED');expect(data.listActiveMemories).not.toHaveBeenCalled();});
 it('shares Memory evaluator and normalized duplicate behavior',async()=>{const valid=await context(),skip=setup();await expect(skip.service.evaluateAndWriteMemory(valid,'hello')).resolves.toEqual({decision:'SKIP',reason:'NO_SUPPORTED_EXPLICIT_PATTERN'});const duplicate=setup({listActiveMemories:jest.fn().mockResolvedValue([memory({content:'my GOAL is ship!'})])});await expect(duplicate.service.evaluateAndWriteMemory(valid,'My goal is ship.')).resolves.toMatchObject({decision:'SKIP',reason:'EXACT_NORMALIZED_DUPLICATE'});expect(duplicate.data.createMemory).not.toHaveBeenCalled();});
 it('projects Evidence with the canonical pure projection',async()=>{const valid=await context(),{service}=setup({listActiveMemories:jest.fn().mockResolvedValue([memory()])});await expect(service.listEligibleEvidence(valid,new Date('2026-02-01T00:00:00Z'))).resolves.toEqual([expect.objectContaining({evidenceId:`memory:${memory().id}`,statement:'My goal is ship.'})]);});
 it('uses the shared trigger classifier without a provider',async()=>{const valid=await context(),{service}=setup({listActiveMemories:jest.fn().mockResolvedValue([memory()])});const result=await service.evaluateGenerationEligibility(valid,'Why do I always give up?','ALLOW');expect(result.eligibility.status).toBe('ELIGIBLE');});
 it('sends only authoritative minimal inputs to Confidence RPC',async()=>{const valid=await context(),hypothesis={id:'30000000-0000-4000-8000-000000000001',version:7},createConfidenceEvaluation=jest.fn().mockResolvedValue({id:'x'}),{service}=setup({findHypothesis:jest.fn().mockResolvedValue(hypothesis),createConfidenceEvaluation});await service.evaluateHypothesisConfidence(valid,hypothesis.id);expect(createConfidenceEvaluation).toHaveBeenCalledWith(valid,expect.any(String),hypothesis.id,7);});
 it('exports only authority and the narrow enrichment facade',()=>{const exports=Reflect.getMetadata('exports',BackgroundIntelligenceModule);expect(exports).toEqual([BackgroundIntelligenceAuthorityService,BackgroundIntelligenceEnrichmentService]);expect(exports).not.toContain(RawDataApi);});
});
