BEGIN;

ALTER TABLE public.him_metric_definitions
  ADD COLUMN hif_owner text,
  ADD COLUMN calculation_status text;

ALTER TABLE public.him_metric_definitions
  ALTER COLUMN hif_owner SET NOT NULL,
  ALTER COLUMN calculation_status SET NOT NULL,
  ADD CONSTRAINT him_definition_hif_owner_check CHECK(hif_owner=ANY(ARRAY['HSE','HBS','HRS','HGS'])),
  ADD CONSTRAINT him_definition_calculation_status_check CHECK(calculation_status=ANY(ARRAY['UNCALIBRATED','CALIBRATED']));

INSERT INTO public.him_metric_definitions
  (metric_key,definition_version,canonical_name,canonical_definition,canonical_source,hif_owner,semantic_type,calculation_status,scale_reference,valid_context_kinds,required_input_contract,confidence_requirement_reference,consumers,source_metadata,dependency_ids)
VALUES
('hse.stress',1,'Stress','Canonical HIF Part 8 HSE metric identity: Stress. No quantitative interpretation is approved.','HIF Part 8 — Human Intelligence Metrics v0.1 / HSE','HSE','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['SITUATION','CONVERSATION_SESSION'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hse.energy',1,'Energy','Canonical HIF Part 8 HSE metric identity: Energy. No quantitative interpretation is approved.','HIF Part 8 — Human Intelligence Metrics v0.1 / HSE','HSE','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['SITUATION','CONVERSATION_SESSION'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hse.motivation',1,'Motivation','Canonical HIF Part 8 HSE metric identity: Motivation. No quantitative interpretation is approved.','HIF Part 8 — Human Intelligence Metrics v0.1 / HSE','HSE','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['SITUATION','GOAL'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hse.self-confidence',1,'Confidence','Canonical HIF Part 8 HSE metric identity: Confidence. Human self-confidence in context; not Hypothesis Confidence Runtime.','HIF Part 8 — Human Intelligence Metrics v0.1 / HSE','HSE','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['SITUATION','DECISION'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hse.attention',1,'Attention','Canonical HIF Part 8 HSE metric identity: Attention. No quantitative interpretation is approved.','HIF Part 8 — Human Intelligence Metrics v0.1 / HSE','HSE','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['SITUATION','CONVERSATION_SESSION','DECISION'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hbs.avoidance',1,'Avoidance','Canonical HIF Part 8 HBS metric identity: Avoidance. Context-bound behavior representation; not a permanent trait.','HIF Part 8 — Human Intelligence Metrics v0.1 / HBS','HBS','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['SITUATION','GOAL'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hbs.consistency',1,'Consistency','Canonical HIF Part 8 HBS metric identity: Consistency. Context-bound behavior representation; not a permanent trait.','HIF Part 8 — Human Intelligence Metrics v0.1 / HBS','HBS','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['SITUATION','GOAL'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hbs.initiative',1,'Initiative','Canonical HIF Part 8 HBS metric identity: Initiative. Context-bound behavior representation; not a permanent trait.','HIF Part 8 — Human Intelligence Metrics v0.1 / HBS','HBS','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['SITUATION','GOAL'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hbs.reflection',1,'Reflection','Canonical HIF Part 8 HBS metric identity: Reflection. Context-bound behavior representation; not a permanent trait.','HIF Part 8 — Human Intelligence Metrics v0.1 / HBS','HBS','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['SITUATION','CONVERSATION_SESSION'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hrs.relationship-trust',1,'Trust','Canonical HIF Part 8 HRS metric identity: Trust. Relationship-bound human trust; not SENA, provider, epistemic, or global trust.','HIF Part 8 — Human Intelligence Metrics v0.1 / HRS','HRS','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['RELATIONSHIP'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hrs.communication',1,'Communication','Canonical HIF Part 8 HRS metric identity: Communication. Relationship-bound representation only.','HIF Part 8 — Human Intelligence Metrics v0.1 / HRS','HRS','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['RELATIONSHIP'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hrs.repair',1,'Repair','Canonical HIF Part 8 HRS metric identity: Repair. Relationship-bound representation only.','HIF Part 8 — Human Intelligence Metrics v0.1 / HRS','HRS','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['RELATIONSHIP'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hrs.emotional-safety',1,'Emotional Safety','Canonical HIF Part 8 HRS metric identity: Emotional Safety. Relationship-bound representation only.','HIF Part 8 — Human Intelligence Metrics v0.1 / HRS','HRS','STATE','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['RELATIONSHIP'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hgs.self-awareness',1,'Self-awareness','Canonical HIF Part 8 HGS metric identity: Self-awareness. Capability tag only; no score or growth trajectory is defined.','HIF Part 8 — Human Intelligence Metrics v0.1 / HGS','HGS','CAPABILITY','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['GOAL','SITUATION'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hgs.resilience',1,'Resilience','Canonical HIF Part 8 HGS metric identity: Resilience. Capability tag only; no score or growth trajectory is defined.','HIF Part 8 — Human Intelligence Metrics v0.1 / HGS','HGS','CAPABILITY','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['GOAL','SITUATION'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hgs.purpose-alignment',1,'Purpose Alignment','Canonical HIF Part 8 HGS metric identity: Purpose Alignment. Goal-bound alignment only; no score is defined.','HIF Part 8 — Human Intelligence Metrics v0.1 / HGS','HGS','ALIGNMENT','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['GOAL'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}'),
('hgs.habit-strength',1,'Habit Strength','Canonical HIF Part 8 HGS metric identity: Habit Strength. Capability tag only; no score or growth trajectory is defined.','HIF Part 8 — Human Intelligence Metrics v0.1 / HGS','HGS','CAPABILITY','UNCALIBRATED','UNCALIBRATED_NO_PRODUCTION_SCALE',ARRAY['GOAL','SITUATION'],'APPROVED_MEASUREMENT_MODEL_REQUIRED','UNRESOLVED_METRIC_CONFIDENCE_MODEL','{}',ARRAY['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],'{}')
ON CONFLICT (metric_key,definition_version) DO NOTHING;

CREATE OR REPLACE FUNCTION public.create_him_metric_snapshot(p_observation jsonb)
RETURNS SETOF public.him_metric_snapshots LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE canonical_user uuid := (SELECT auth.uid()); definition public.him_metric_definitions; next_version integer;
DECLARE supporting text[]; contradicting text[]; descriptive_reference_ids text[]; value_number double precision;
DECLARE window_start timestamptz; window_end timestamptz;
BEGIN
  IF canonical_user IS NULL THEN RETURN; END IF;
  IF EXISTS(SELECT 1 FROM jsonb_object_keys(p_observation) key WHERE key<>ALL(ARRAY['id','metricKey','definitionVersion','valueState','numericValue','supportingEvidenceIds','contradictingEvidenceIds','contextKind','contextId','scope','temporalWindowStart','temporalWindowEnd','validityStatus','descriptiveUpdateReason','descriptiveUpdateReferenceIds'])) THEN RAISE EXCEPTION 'Observation contains forbidden fields' USING ERRCODE='22023'; END IF;
  SELECT * INTO definition FROM public.him_metric_definitions WHERE metric_key=p_observation->>'metricKey' AND definition_version=(p_observation->>'definitionVersion')::integer;
  IF NOT FOUND THEN RAISE EXCEPTION 'Unknown HIM definition identity/version' USING ERRCODE='22023'; END IF;
  IF NOT (p_observation->>'contextKind'=ANY(definition.valid_context_kinds)) THEN RAISE EXCEPTION 'Unsupported exact context kind' USING ERRCODE='22023'; END IF;
  supporting:=ARRAY(SELECT jsonb_array_elements_text(coalesce(p_observation->'supportingEvidenceIds','[]'::jsonb))); contradicting:=ARRAY(SELECT jsonb_array_elements_text(coalesce(p_observation->'contradictingEvidenceIds','[]'::jsonb))); descriptive_reference_ids:=ARRAY(SELECT jsonb_array_elements_text(coalesce(p_observation->'descriptiveUpdateReferenceIds','[]'::jsonb)));
  IF NOT public.bounded_nonempty_text_array(supporting,32,64) OR NOT public.bounded_nonempty_text_array(contradicting,32,64) OR supporting&&contradicting OR NOT public.bounded_nonempty_text_array(descriptive_reference_ids,32,64) THEN RAISE EXCEPTION 'Invalid bounded HIM evidence metadata' USING ERRCODE='22023'; END IF;
  IF EXISTS(SELECT 1 FROM unnest(supporting||contradicting||descriptive_reference_ids) ref WHERE ref!~'^memory:[0-9a-fA-F-]{36}$' OR NOT EXISTS(SELECT 1 FROM public.memories m WHERE m.id=substring(ref from 8)::uuid AND m.user_id=canonical_user AND m.status='ACTIVE' AND (m.expires_at IS NULL OR m.expires_at>CURRENT_TIMESTAMP))) THEN RAISE EXCEPTION 'Ineligible or cross-user HIM evidence reference' USING ERRCODE='22023'; END IF;
  IF p_observation->>'contextKind'='GLOBAL' THEN IF p_observation->>'contextId'<>'GLOBAL' THEN RAISE EXCEPTION 'Invalid exact GLOBAL context identity' USING ERRCODE='22023'; END IF; ELSIF p_observation->>'contextKind'=ANY(ARRAY['RELATIONSHIP','DECISION','GOAL','CONVERSATION_SESSION']) THEN IF p_observation->>'contextId'!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' THEN RAISE EXCEPTION 'Invalid exact UUID context identity' USING ERRCODE='22023'; END IF; ELSIF p_observation->>'contextKind'='SITUATION' THEN IF length(p_observation->>'contextId') NOT BETWEEN 1 AND 128 OR p_observation->>'contextId'<>btrim(p_observation->>'contextId') OR p_observation->>'contextId'='GLOBAL' THEN RAISE EXCEPTION 'Invalid exact SITUATION context identity' USING ERRCODE='22023'; END IF; ELSE RAISE EXCEPTION 'Invalid HIM context kind' USING ERRCODE='22023'; END IF;
  IF p_observation->>'valueState'='UNASSESSED' THEN IF p_observation?'numericValue' THEN RAISE EXCEPTION 'Unassessed HIM value cannot carry numeric value' USING ERRCODE='22023'; END IF; value_number:=NULL; ELSIF p_observation->>'valueState'='ASSESSED' THEN IF definition.calculation_status<>'CALIBRATED' THEN RAISE EXCEPTION 'HIM metric has no approved calibrated calculation model' USING ERRCODE='22023'; END IF; value_number:=(p_observation->>'numericValue')::double precision; IF value_number IS NULL OR value_number<='-Infinity'::double precision OR value_number>='Infinity'::double precision OR value_number<>value_number THEN RAISE EXCEPTION 'Assessed HIM value requires finite numeric value' USING ERRCODE='22023'; END IF; ELSE RAISE EXCEPTION 'Invalid HIM value state' USING ERRCODE='22023'; END IF;
  IF (p_observation?'temporalWindowStart')<>(p_observation?'temporalWindowEnd') THEN RAISE EXCEPTION 'Incomplete temporal window' USING ERRCODE='22023'; END IF; IF p_observation?'temporalWindowStart' THEN window_start:=(p_observation->>'temporalWindowStart')::timestamptz;window_end:=(p_observation->>'temporalWindowEnd')::timestamptz;IF window_start>window_end THEN RAISE EXCEPTION 'Invalid temporal window' USING ERRCODE='22023'; END IF;END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(canonical_user::text||definition.metric_key||(p_observation->>'contextKind')||(p_observation->>'contextId'),0));SELECT coalesce(max(snapshot_version),0)+1 INTO next_version FROM public.him_metric_snapshots WHERE user_id=canonical_user AND metric_key=definition.metric_key AND context_kind=p_observation->>'contextKind' AND context_id=p_observation->>'contextId';
  RETURN QUERY INSERT INTO public.him_metric_snapshots(id,user_id,metric_key,definition_version,semantic_type,value_state,numeric_value,confidence_state,confidence_reference,supporting_evidence_ids,contradicting_evidence_ids,source_engines,context_kind,context_id,scope,observed_at,temporal_window_start,temporal_window_end,validity_status,snapshot_version,descriptive_update_reason,descriptive_update_reference_ids,canonical_provenance,created_at) VALUES((p_observation->>'id')::uuid,canonical_user,definition.metric_key,definition.definition_version,definition.semantic_type,p_observation->>'valueState',value_number,'UNASSESSED',NULL,supporting,contradicting,ARRAY['QANDEEL_HIM_RUNTIME'],p_observation->>'contextKind',p_observation->>'contextId',p_observation->>'scope',CURRENT_TIMESTAMP,window_start,window_end,p_observation->>'validityStatus',next_version,p_observation->>'descriptiveUpdateReason',descriptive_reference_ids,'QANDEEL_HIM_RUNTIME_FOUNDATION_V1',CURRENT_TIMESTAMP) RETURNING *;
END; $$;

REVOKE ALL ON FUNCTION public.create_him_metric_snapshot(jsonb) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.create_him_metric_snapshot(jsonb) TO authenticated;
COMMIT;

