BEGIN;
ALTER TABLE public.him_measurement_targets DROP CONSTRAINT him_measurement_targets_context_kind_check;
ALTER TABLE public.him_measurement_targets ADD CONSTRAINT him_measurement_targets_context_kind_check CHECK(context_kind=ANY(ARRAY['GOAL','SITUATION','DECISION']));
ALTER TABLE public.him_measurement_events DROP CONSTRAINT him_measurement_event_context_kind_check;
ALTER TABLE public.him_measurement_events ADD CONSTRAINT him_measurement_event_context_kind_check CHECK(context_kind=ANY(ARRAY['CONVERSATION_SESSION','GOAL','SITUATION','DECISION']));
ALTER TABLE public.him_measurement_observations DROP CONSTRAINT him_structured_observation_contract;
ALTER TABLE public.him_measurement_observations ADD CONSTRAINT him_structured_observation_contract CHECK(
 (metric_key='hse.energy' AND definition_version=1 AND context_kind='CONVERSATION_SESSION' AND instrument_id='hse.energy.ar-eg.right-now' AND instrument_version=1 AND scale_contract_reference='hse.energy.ordinal-5.v1' AND scale_version=1 AND canonical_provenance='QANDEEL_HSE_ENERGY_MEASUREMENT_V1' AND target_label IS NULL AND target_context_kind IS NULL AND target_context_id IS NULL)
 OR (metric_key='hse.motivation' AND definition_version=1 AND context_kind=ANY(ARRAY['GOAL','SITUATION']) AND instrument_id='hse.motivation.direct-self-report' AND instrument_version=1 AND scale_contract_reference='hse.motivation.ordinal-5.v1' AND scale_version=1 AND canonical_provenance='QANDEEL_HSE_MOTIVATION_MEASUREMENT_V1' AND length(target_label) BETWEEN 1 AND 256 AND target_label=btrim(target_label) AND target_context_kind=context_kind AND target_context_id::text=context_id)
 OR (metric_key='hse.attention' AND definition_version=1 AND context_kind='CONVERSATION_SESSION' AND instrument_id='hse.attention.direct-self-report' AND instrument_version=1 AND scale_contract_reference='hse.attention.ordinal-5.v1' AND scale_version=1 AND canonical_provenance='QANDEEL_HSE_ATTENTION_MEASUREMENT_V1' AND target_label IS NULL AND target_context_kind IS NULL AND target_context_id IS NULL)
 OR (metric_key='hse.attention' AND definition_version=1 AND context_kind=ANY(ARRAY['SITUATION','DECISION']) AND instrument_id='hse.attention.direct-self-report' AND instrument_version=1 AND scale_contract_reference='hse.attention.ordinal-5.v1' AND scale_version=1 AND canonical_provenance='QANDEEL_HSE_ATTENTION_MEASUREMENT_V1' AND length(target_label) BETWEEN 1 AND 256 AND target_label=btrim(target_label) AND target_context_kind=context_kind AND target_context_id::text=context_id)
);
ALTER TABLE public.him_canonical_model_bindings DROP CONSTRAINT him_structured_binding_contract;
ALTER TABLE public.him_canonical_model_bindings ADD CONSTRAINT him_structured_binding_contract CHECK(
 (metric_key='hse.energy' AND definition_version=1 AND context_kind='CONVERSATION_SESSION' AND instrument_id='hse.energy.ar-eg.right-now' AND instrument_version=1 AND scale_contract_reference='hse.energy.ordinal-5.v1' AND scale_version=1)
 OR (metric_key='hse.motivation' AND definition_version=1 AND context_kind=ANY(ARRAY['GOAL','SITUATION']) AND instrument_id='hse.motivation.direct-self-report' AND instrument_version=1 AND scale_contract_reference='hse.motivation.ordinal-5.v1' AND scale_version=1)
 OR (metric_key='hse.attention' AND definition_version=1 AND context_kind=ANY(ARRAY['SITUATION','CONVERSATION_SESSION','DECISION']) AND instrument_id='hse.attention.direct-self-report' AND instrument_version=1 AND scale_contract_reference='hse.attention.ordinal-5.v1' AND scale_version=1)
);

INSERT INTO public.him_scale_contracts VALUES('14000000-0000-4000-8000-000000000001','hse.attention.ordinal-5.v1',1,'ORDINAL',true,false,false,ARRAY[1,2,3,4,5],'{"VERY_LOW":1,"LOW":2,"MODERATE":3,"HIGH":4,"VERY_HIGH":5}'::jsonb,'2026-08-23T00:00:00Z');
INSERT INTO public.him_calculation_models(id,model_id,model_version,target_metric_key,target_definition_version,lifecycle,environment,canonical_owner,canonical_source,method_type,scale_contract_reference,required_input_contract,required_evidence_contract,supported_context_kinds,missing_data_behavior,contradiction_behavior,confidence_contract,implementation_id,created_at,versioned_at)
VALUES('14000000-0000-4000-8000-000000000002','hse.attention.direct-structured-self-report',1,'hse.attention',1,'CALIBRATED','PRODUCTION','QANDEEL_HIM_GOVERNANCE','ISSUE_60_HSE_ATTENTION_MEASUREMENT_MODEL_V1','DIRECT_STRUCTURED_SELF_REPORT','hse.attention.ordinal-5.v1','{"required":["measurementObservation","authorizedContext"]}'::jsonb,'FIRST_CLASS_AUTHORIZED_CONTEXT_HIM_MEASUREMENT_OBSERVATION_V1',ARRAY['SITUATION','CONVERSATION_SESSION','DECISION'],'UNASSESSED','UNASSESSED_PRESERVE_CONFLICT','UNRESOLVED_METRIC_CONFIDENCE','hse-attention-direct-structured-v1','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z');
INSERT INTO public.him_governance_approvals(id,approval_id,approval_version,authority_id,authority_version,model_id,model_version,approval_basis,external_validation_claimed,approved_at,canonical_source)
VALUES('14000000-0000-4000-8000-000000000003','qandeel.him.attention.foundation-approval',1,'QANDEEL_FOUNDATION_GOVERNANCE',1,'hse.attention.direct-structured-self-report',1,'["HSE_ATTENTION_STATE","DIRECT_REPORT","RIGHT_NOW","THREE_AUTHORIZED_CONTEXTS","ORDINAL_5","FOUNDER_TESTED_AR_EG","DETERMINISTIC","CORRECTION_IDEMPOTENCY_CONCURRENCY","SECURITY_BINDING","NO_EXTERNAL_VALIDATION_CLAIM"]'::jsonb,false,'2026-08-23T00:00:00Z','ISSUE_60_CANONICAL_APPROVAL');
ALTER TABLE public.him_canonical_model_bindings DISABLE TRIGGER him_energy_binding_validate;
INSERT INTO public.him_canonical_model_bindings(id,metric_key,definition_version,context_kind,binding_version,status,model_id,model_version,instrument_id,instrument_version,scale_contract_reference,scale_version,approval_id,approval_version,effective_at) VALUES
('14000000-0000-4000-8000-000000000004','hse.attention',1,'SITUATION',1,'ACTIVE','hse.attention.direct-structured-self-report',1,'hse.attention.direct-self-report',1,'hse.attention.ordinal-5.v1',1,'qandeel.him.attention.foundation-approval',1,'2026-08-23T00:00:00Z'),
('14000000-0000-4000-8000-000000000005','hse.attention',1,'CONVERSATION_SESSION',1,'ACTIVE','hse.attention.direct-structured-self-report',1,'hse.attention.direct-self-report',1,'hse.attention.ordinal-5.v1',1,'qandeel.him.attention.foundation-approval',1,'2026-08-23T00:00:00Z'),
('14000000-0000-4000-8000-000000000006','hse.attention',1,'DECISION',1,'ACTIVE','hse.attention.direct-structured-self-report',1,'hse.attention.direct-self-report',1,'hse.attention.ordinal-5.v1',1,'qandeel.him.attention.foundation-approval',1,'2026-08-23T00:00:00Z');
UPDATE public.him_metric_definitions SET calculation_status='CALIBRATED',scale_reference='hse.attention.ordinal-5.v1',required_input_contract='DIRECT_STRUCTURED_AUTHORIZED_CONTEXT_USER_REPORT_RIGHT_NOW_V1' WHERE metric_key='hse.attention' AND definition_version=1;

CREATE OR REPLACE FUNCTION public.validate_him_canonical_binding() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$DECLARE m public.him_calculation_models;a public.him_governance_approvals;BEGIN SELECT * INTO m FROM public.him_calculation_models WHERE model_id=NEW.model_id AND model_version=NEW.model_version;SELECT * INTO a FROM public.him_governance_approvals WHERE approval_id=NEW.approval_id AND approval_version=NEW.approval_version;IF a.id IS NULL OR a.model_id<>NEW.model_id OR a.model_version<>NEW.model_version THEN RAISE EXCEPTION 'Canonical binding approval does not approve its exact model version' USING ERRCODE='23514';END IF;IF m.id IS NULL OR m.lifecycle<>'CALIBRATED' OR m.environment<>'PRODUCTION' OR m.target_metric_key<>NEW.metric_key OR m.target_definition_version<>NEW.definition_version OR NOT(NEW.context_kind=ANY(m.supported_context_kinds)) OR m.scale_contract_reference<>NEW.scale_contract_reference THEN RAISE EXCEPTION 'Canonical binding model lifecycle, environment, metric, definition, context, or scale mismatch' USING ERRCODE='23514';END IF;IF NOT((NEW.metric_key='hse.energy' AND NEW.context_kind='CONVERSATION_SESSION' AND NEW.instrument_id='hse.energy.ar-eg.right-now' AND NEW.scale_contract_reference='hse.energy.ordinal-5.v1') OR (NEW.metric_key='hse.motivation' AND NEW.context_kind=ANY(ARRAY['GOAL','SITUATION']) AND NEW.instrument_id='hse.motivation.direct-self-report' AND NEW.scale_contract_reference='hse.motivation.ordinal-5.v1') OR (NEW.metric_key='hse.attention' AND NEW.context_kind=ANY(ARRAY['SITUATION','CONVERSATION_SESSION','DECISION']) AND NEW.instrument_id='hse.attention.direct-self-report' AND NEW.scale_contract_reference='hse.attention.ordinal-5.v1')) OR NEW.definition_version<>1 OR NEW.instrument_version<>1 OR NEW.scale_version<>1 THEN RAISE EXCEPTION 'Canonical binding instrument or scale contract mismatch' USING ERRCODE='23514';END IF;IF(NEW.status='RETIRED')<>(NEW.retired_at IS NOT NULL)THEN RAISE EXCEPTION 'Canonical binding retirement state is inconsistent' USING ERRCODE='23514';END IF;RETURN NEW;END$$;
ALTER TABLE public.him_canonical_model_bindings ENABLE TRIGGER him_energy_binding_validate;

CREATE OR REPLACE FUNCTION public.calculate_hse_structured_measurement(p_observation_id uuid,p_expected_metric text) RETURNS public.him_metric_snapshots LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$DECLARE u uuid:=auth.uid();o public.him_measurement_observations;b public.him_canonical_model_bindings;r public.him_calculation_results;score double precision;state text;next_version integer;s public.him_metric_snapshots;BEGIN
 PERFORM pg_advisory_xact_lock(hashtextextended(p_expected_metric||'.observation:'||p_observation_id::text,0));SELECT * INTO o FROM public.him_measurement_observations WHERE id=p_observation_id AND user_id=u AND metric_key=p_expected_metric;
 IF NOT FOUND OR EXISTS(SELECT 1 FROM public.him_measurement_observations x WHERE x.supersedes_observation_id=o.id) THEN RAISE EXCEPTION 'Unknown, cross-user, cross-metric, or superseded structured observation' USING ERRCODE='42501';END IF;
 IF o.metric_key='hse.motivation' AND(o.target_label IS NULL OR o.target_context_kind<>o.context_kind OR o.target_context_id::text<>o.context_id OR NOT EXISTS(SELECT 1 FROM public.him_measurement_targets t WHERE t.id=o.target_context_id AND t.user_id=o.user_id AND t.context_kind=o.context_kind AND t.display_text=o.target_label))THEN RAISE EXCEPTION 'Motivation target/context mismatch' USING ERRCODE='22023';END IF;
 IF o.metric_key='hse.attention' AND NOT((o.context_kind='CONVERSATION_SESSION' AND EXISTS(SELECT 1 FROM public.conversation_sessions c WHERE c.id::text=o.context_id AND c.user_id=o.user_id) AND o.target_context_id IS NULL) OR (o.context_kind=ANY(ARRAY['SITUATION','DECISION']) AND o.target_context_kind=o.context_kind AND o.target_context_id::text=o.context_id AND EXISTS(SELECT 1 FROM public.him_measurement_targets t WHERE t.id=o.target_context_id AND t.user_id=o.user_id AND t.context_kind=o.context_kind AND t.display_text=o.target_label)))THEN RAISE EXCEPTION 'Attention authoritative context mismatch' USING ERRCODE='22023';END IF;
 SELECT cb.* INTO b FROM public.him_canonical_model_bindings cb JOIN public.him_calculation_models m ON(m.model_id,m.model_version)=(cb.model_id,cb.model_version) JOIN public.him_governance_approvals a ON(a.approval_id,a.approval_version)=(cb.approval_id,cb.approval_version) WHERE cb.metric_key=o.metric_key AND cb.definition_version=o.definition_version AND cb.context_kind=o.context_kind AND cb.status='ACTIVE' AND m.lifecycle='CALIBRATED' AND m.environment='PRODUCTION' AND(a.model_id,a.model_version)=(m.model_id,m.model_version) AND cb.instrument_id=o.instrument_id AND cb.instrument_version=o.instrument_version AND cb.scale_contract_reference=o.scale_contract_reference AND cb.scale_version=o.scale_version;IF NOT FOUND THEN RAISE EXCEPTION 'No exact active canonical structured binding' USING ERRCODE='22023';END IF;
 SELECT s0.* INTO s FROM public.him_metric_snapshots s0 JOIN public.him_calculation_results r0 ON r0.id=s0.calculation_result_id WHERE r0.measurement_observation_id=o.id AND r0.canonical_binding_id=b.id;IF FOUND THEN RETURN s;END IF;
 score:=CASE o.response_code WHEN'VERY_LOW'THEN 1 WHEN'LOW'THEN 2 WHEN'MODERATE'THEN 3 WHEN'HIGH'THEN 4 WHEN'VERY_HIGH'THEN 5 ELSE NULL END;state:=CASE WHEN score IS NULL THEN'UNASSESSED'ELSE'ASSESSED'END;
 INSERT INTO public.him_calculation_results(id,user_id,metric_key,definition_version,model_id,model_version,context_kind,context_id,result_state,numeric_value,missing_input_keys,contradiction_state,supporting_evidence_refs,contradictory_evidence_refs,provenance,confidence_state,confidence_reference,trace_id,update_reason,measurement_event_id,measurement_observation_id,canonical_binding_id,scale_contract_reference,scale_version)VALUES(gen_random_uuid(),u,o.metric_key,o.definition_version,b.model_id,b.model_version,o.context_kind,o.context_id,state,score,CASE WHEN score IS NULL THEN ARRAY['scoredResponse']ELSE ARRAY[]::text[]END,'NONE',ARRAY['measurement-observation:'||o.id::text],ARRAY[]::text[],'QANDEEL_HIM_CALCULATION_RUNTIME_V1','UNASSESSED',NULL,gen_random_uuid()::text,'DIRECT_STRUCTURED_USER_REPORT',o.measurement_event_id,o.id,b.id,o.scale_contract_reference,o.scale_version)RETURNING*INTO r;
 PERFORM pg_advisory_xact_lock(hashtextextended(u::text||o.metric_key||o.context_kind||o.context_id,0));SELECT coalesce(max(snapshot_version),0)+1 INTO next_version FROM public.him_metric_snapshots WHERE user_id=u AND metric_key=o.metric_key AND context_kind=o.context_kind AND context_id=o.context_id;
 INSERT INTO public.him_metric_snapshots(id,user_id,metric_key,definition_version,semantic_mapping_status,semantic_type,value_state,numeric_value,confidence_state,confidence_reference,supporting_evidence_ids,contradicting_evidence_ids,source_engines,context_kind,context_id,scope,observed_at,validity_status,snapshot_version,descriptive_update_reason,descriptive_update_reference_ids,canonical_provenance,created_at,calculation_result_id,measurement_event_id,measurement_observation_id,canonical_binding_id,scale_contract_reference,scale_version)VALUES(gen_random_uuid(),u,o.metric_key,o.definition_version,'RESOLVED','STATE',state,score,'UNASSESSED',NULL,ARRAY[]::text[],ARRAY[]::text[],ARRAY['QANDEEL_HIM_RUNTIME'],o.context_kind,o.context_id,'exact measurement event',o.reported_at,'VALID',next_version,'DIRECT_STRUCTURED_USER_REPORT',ARRAY[]::text[],'QANDEEL_HIM_RUNTIME_FOUNDATION_V1',CURRENT_TIMESTAMP,r.id,o.measurement_event_id,o.id,b.id,o.scale_contract_reference,o.scale_version)RETURNING*INTO s;RETURN s;END$$;

CREATE FUNCTION public.create_him_attention_measurement_context(p_context_kind text,p_display_text text) RETURNS public.him_measurement_targets LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$DECLARE u uuid:=auth.uid();t public.him_measurement_targets;BEGIN IF u IS NULL THEN RAISE EXCEPTION'Authentication required'USING ERRCODE='42501';END IF;IF p_context_kind<>ALL(ARRAY['SITUATION','DECISION']) OR p_display_text IS NULL OR length(p_display_text)NOT BETWEEN 1 AND 256 OR p_display_text<>btrim(p_display_text)THEN RAISE EXCEPTION'Invalid Attention measurement context'USING ERRCODE='22023';END IF;INSERT INTO public.him_measurement_targets(id,user_id,context_kind,display_text,canonical_provenance)VALUES(gen_random_uuid(),u,p_context_kind,p_display_text,'QANDEEL_HIM_MEASUREMENT_TARGET_V1')RETURNING*INTO t;RETURN t;END$$;
CREATE FUNCTION public.create_hse_attention_measurement(p_context_kind text,p_context_id uuid,p_response_code text,p_client_reported_at_untrusted timestamptz) RETURNS public.him_measurement_observations LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$DECLARE u uuid:=auth.uid();e uuid:=gen_random_uuid();canonical_now timestamptz:=clock_timestamp();owned public.him_measurement_targets;o public.him_measurement_observations;BEGIN IF u IS NULL THEN RAISE EXCEPTION'Authentication required'USING ERRCODE='42501';END IF;IF p_context_kind='CONVERSATION_SESSION'THEN IF NOT EXISTS(SELECT 1 FROM public.conversation_sessions c WHERE c.id=p_context_id AND c.user_id=u)THEN RAISE EXCEPTION'Unknown or cross-user conversation session'USING ERRCODE='42501';END IF;ELSIF p_context_kind=ANY(ARRAY['SITUATION','DECISION'])THEN SELECT*INTO owned FROM public.him_measurement_targets WHERE id=p_context_id AND user_id=u AND context_kind=p_context_kind;IF NOT FOUND THEN RAISE EXCEPTION'Unknown, cross-user, or mismatched Attention measurement context'USING ERRCODE='42501';END IF;ELSE RAISE EXCEPTION'Unsupported Attention context'USING ERRCODE='22023';END IF;IF p_response_code<>ALL(ARRAY['VERY_LOW','LOW','MODERATE','HIGH','VERY_HIGH','NOT_SURE'])THEN RAISE EXCEPTION'Invalid Attention response'USING ERRCODE='22023';END IF;INSERT INTO public.him_measurement_events(id,user_id,context_kind,context_id,created_at)VALUES(e,u,p_context_kind,p_context_id::text,canonical_now);INSERT INTO public.him_measurement_observations(id,user_id,measurement_event_id,metric_key,definition_version,instrument_id,instrument_version,scale_contract_reference,scale_version,context_kind,context_id,response_code,reported_at,client_reported_at_untrusted,locale,source,canonical_provenance,created_at,target_label,target_context_kind,target_context_id)VALUES(gen_random_uuid(),u,e,'hse.attention',1,'hse.attention.direct-self-report',1,'hse.attention.ordinal-5.v1',1,p_context_kind,p_context_id::text,p_response_code,canonical_now,p_client_reported_at_untrusted,'ar-EG','DIRECT_STRUCTURED_USER_REPORT','QANDEEL_HSE_ATTENTION_MEASUREMENT_V1',canonical_now,owned.display_text,owned.context_kind,owned.id)RETURNING*INTO o;RETURN o;END$$;
CREATE FUNCTION public.correct_hse_attention_measurement(uuid,text,timestamptz) RETURNS public.him_measurement_observations LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$SELECT public.correct_hse_structured_measurement($1,'hse.attention',$2,$3)$$;
CREATE FUNCTION public.calculate_hse_attention_measurement(uuid) RETURNS public.him_metric_snapshots LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$SELECT public.calculate_hse_structured_measurement($1,'hse.attention')$$;
CREATE OR REPLACE VIEW public.him_current_structured_measurements WITH(security_invoker=true)AS SELECT s.* FROM public.him_measurement_observations o JOIN public.him_metric_snapshots s ON s.measurement_observation_id=o.id WHERE o.metric_key=ANY(ARRAY['hse.energy','hse.motivation','hse.attention'])AND NOT EXISTS(SELECT 1 FROM public.him_measurement_observations newer WHERE newer.supersedes_observation_id=o.id)AND NOT EXISTS(SELECT 1 FROM public.him_energy_calculation_supersessions x WHERE x.snapshot_id=s.id);
REVOKE ALL ON FUNCTION public.create_him_attention_measurement_context(text,text),public.create_hse_attention_measurement(text,uuid,text,timestamptz),public.correct_hse_attention_measurement(uuid,text,timestamptz),public.calculate_hse_attention_measurement(uuid)FROM PUBLIC,anon;GRANT EXECUTE ON FUNCTION public.create_him_attention_measurement_context(text,text),public.create_hse_attention_measurement(text,uuid,text,timestamptz),public.correct_hse_attention_measurement(uuid,text,timestamptz),public.calculate_hse_attention_measurement(uuid)TO authenticated;
DO $$BEGIN IF(SELECT count(*)FROM public.him_metric_definitions WHERE calculation_status='CALIBRATED')<>3 OR(SELECT count(*)FROM public.him_metric_definitions WHERE calculation_status='UNCALIBRATED')<>14 THEN RAISE EXCEPTION'Energy, Motivation and Attention calibration invariant failed';END IF;END$$;
COMMIT;
