BEGIN;
-- HIM Runtime Consumption v1. One internal canonical snapshot core carries the
-- EXACT migration-0018 source-row semantics with an explicit trusted owner and
-- no auth.uid(); the authenticated function becomes a narrow wrapper around it
-- with unchanged application-visible behavior; one CONVERSATION_SESSION-only
-- service-role wrapper gives the background intelligence runtime a safe
-- canonical read without any user JWT, request claims, or claim reconstruction.
-- No table, no backfill, no persisted snapshot, no new effect key.
CREATE FUNCTION public.read_him_intelligence_snapshot_core_v1(p_user_id uuid,p_context_kind text,p_context_id text)
RETURNS TABLE(generated_at timestamptz,slot_order integer,metric_key text,definition_version integer,semantic_type text,context_kind text,context_id text,active_binding_id uuid,active_instrument_id text,active_instrument_version integer,active_scale_reference text,active_scale_version integer,active_model_id text,active_model_version integer,measurement_event_id uuid,event_observed_at timestamptz,measurement_observation_id uuid,response_code text,observation_instrument_id text,observation_instrument_version integer,observation_scale_reference text,observation_scale_version integer,snapshot_id uuid,value_state text,numeric_value double precision,validity_status text,snapshot_provenance text,calculation_result_id uuid,canonical_binding_id uuid,snapshot_scale_reference text,snapshot_scale_version integer,result_state text,result_numeric_value double precision,result_model_id text,result_model_version integer,result_provenance text,result_confidence_state text,result_confidence_reference text,source_binding_status text,source_instrument_id text,source_instrument_version integer,source_scale_reference text,source_scale_version integer,source_model_id text,source_model_version integer)
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path='' AS $$
DECLARE u uuid:=p_user_id;owned boolean:=false;expected integer;configured integer;
BEGIN
 IF u IS NULL THEN RAISE EXCEPTION 'HIM Intelligence Snapshot trusted user identity required' USING ERRCODE='42501';END IF;
 IF p_context_kind='CONVERSATION_SESSION' THEN SELECT EXISTS(SELECT 1 FROM public.conversation_sessions c WHERE c.id::text=p_context_id AND c.user_id=u) INTO owned;
 ELSIF p_context_kind=ANY(ARRAY['SITUATION','DECISION','GOAL']) THEN SELECT EXISTS(SELECT 1 FROM public.him_measurement_targets t WHERE t.id::text=p_context_id AND t.user_id=u AND t.context_kind=p_context_kind) INTO owned;
 ELSE RAISE EXCEPTION 'Unsupported HIM Intelligence Snapshot context' USING ERRCODE='22023';END IF;
 IF NOT owned THEN RAISE EXCEPTION 'Unknown or unowned HIM Intelligence Snapshot context' USING ERRCODE='42501';END IF;
 WITH slots(slot_order,metric_key,definition_version,context_kind)AS(VALUES(1,'hse.stress',1,'SITUATION'),(3,'hse.motivation',1,'SITUATION'),(4,'hse.self-confidence',1,'SITUATION'),(5,'hse.attention',1,'SITUATION'),(1,'hse.stress',1,'CONVERSATION_SESSION'),(2,'hse.energy',1,'CONVERSATION_SESSION'),(5,'hse.attention',1,'CONVERSATION_SESSION'),(4,'hse.self-confidence',1,'DECISION'),(5,'hse.attention',1,'DECISION'),(3,'hse.motivation',1,'GOAL'))SELECT count(*)::integer INTO expected FROM slots s WHERE s.context_kind=p_context_kind;
 WITH slots(metric_key,definition_version,context_kind)AS(VALUES('hse.stress',1,'SITUATION'),('hse.motivation',1,'SITUATION'),('hse.self-confidence',1,'SITUATION'),('hse.attention',1,'SITUATION'),('hse.stress',1,'CONVERSATION_SESSION'),('hse.energy',1,'CONVERSATION_SESSION'),('hse.attention',1,'CONVERSATION_SESSION'),('hse.self-confidence',1,'DECISION'),('hse.attention',1,'DECISION'),('hse.motivation',1,'GOAL'))
 SELECT count(*)::integer INTO configured FROM slots s JOIN public.him_canonical_model_bindings b ON b.metric_key=s.metric_key AND b.definition_version=s.definition_version AND b.context_kind=s.context_kind AND b.status='ACTIVE' JOIN public.him_metric_definitions d ON(d.metric_key,d.definition_version)=(b.metric_key,b.definition_version)AND d.calculation_status='CALIBRATED' AND d.semantic_type='STATE' JOIN public.him_calculation_models m ON(m.model_id,m.model_version)=(b.model_id,b.model_version)AND(m.target_metric_key,m.target_definition_version)=(b.metric_key,b.definition_version)AND m.lifecycle='CALIBRATED' AND m.environment='PRODUCTION' AND b.context_kind=ANY(m.supported_context_kinds)AND m.scale_contract_reference=b.scale_contract_reference JOIN public.him_governance_approvals a ON(a.approval_id,a.approval_version)=(b.approval_id,b.approval_version)AND(a.model_id,a.model_version)=(b.model_id,b.model_version) JOIN public.him_scale_contracts sc ON(sc.scale_contract_id,sc.scale_version)=(b.scale_contract_reference,b.scale_version)AND sc.scale_kind='ORDINAL' AND sc.ordered AND NOT sc.interval_operations AND NOT sc.ratio_operations AND sc.allowed_codes=ARRAY[1,2,3,4,5] WHERE s.context_kind=p_context_kind;
 IF expected=0 OR configured<>expected THEN RAISE EXCEPTION 'HIM Intelligence Snapshot active binding integrity failure' USING ERRCODE='23514';END IF;
 RETURN QUERY WITH slots(slot_order,metric_key,definition_version,context_kind)AS(VALUES(1,'hse.stress',1,'SITUATION'),(3,'hse.motivation',1,'SITUATION'),(4,'hse.self-confidence',1,'SITUATION'),(5,'hse.attention',1,'SITUATION'),(1,'hse.stress',1,'CONVERSATION_SESSION'),(2,'hse.energy',1,'CONVERSATION_SESSION'),(5,'hse.attention',1,'CONVERSATION_SESSION'),(4,'hse.self-confidence',1,'DECISION'),(5,'hse.attention',1,'DECISION'),(3,'hse.motivation',1,'GOAL'))
 SELECT statement_timestamp(),s.slot_order,s.metric_key,s.definition_version,'STATE'::text,s.context_kind,p_context_id,ab.id,ab.instrument_id,ab.instrument_version,ab.scale_contract_reference,ab.scale_version,ab.model_id,ab.model_version,e.id,e.created_at,o.id,o.response_code,o.instrument_id,o.instrument_version,o.scale_contract_reference,o.scale_version,cs.id,cs.value_state,cs.numeric_value,cs.validity_status,cs.canonical_provenance,cs.calculation_result_id,cs.canonical_binding_id,cs.scale_contract_reference,cs.scale_version,r.result_state,r.numeric_value,r.model_id,r.model_version,r.provenance,r.confidence_state,r.confidence_reference,sb.status,sb.instrument_id,sb.instrument_version,sb.scale_contract_reference,sb.scale_version,sb.model_id,sb.model_version
 FROM slots s JOIN public.him_canonical_model_bindings ab ON ab.metric_key=s.metric_key AND ab.definition_version=s.definition_version AND ab.context_kind=s.context_kind AND ab.status='ACTIVE'
 LEFT JOIN LATERAL(SELECT me.id,me.created_at FROM public.him_measurement_events me WHERE me.user_id=u AND me.context_kind=s.context_kind AND me.context_id=p_context_id AND EXISTS(SELECT 1 FROM public.him_measurement_observations eo WHERE eo.measurement_event_id=me.id AND eo.user_id=u AND eo.metric_key=s.metric_key AND eo.definition_version=s.definition_version)ORDER BY me.created_at DESC,me.id DESC LIMIT 1)e ON true
 LEFT JOIN LATERAL(SELECT mo.* FROM public.him_measurement_observations mo WHERE mo.measurement_event_id=e.id AND mo.user_id=u AND mo.metric_key=s.metric_key AND mo.definition_version=s.definition_version AND NOT EXISTS(SELECT 1 FROM public.him_measurement_observations newer WHERE newer.supersedes_observation_id=mo.id)ORDER BY mo.created_at DESC,mo.id DESC LIMIT 1)o ON true
 LEFT JOIN public.him_current_structured_measurements cs ON cs.measurement_observation_id=o.id
 LEFT JOIN public.him_calculation_results r ON r.id=cs.calculation_result_id
 LEFT JOIN public.him_canonical_model_bindings sb ON sb.id=cs.canonical_binding_id
 WHERE s.context_kind=p_context_kind ORDER BY s.slot_order;
END$$;
REVOKE ALL ON FUNCTION public.read_him_intelligence_snapshot_core_v1(uuid,text,text) FROM PUBLIC,anon,authenticated,service_role;

CREATE OR REPLACE FUNCTION public.read_him_intelligence_snapshot_v1(p_context_kind text,p_context_id text)
RETURNS TABLE(generated_at timestamptz,slot_order integer,metric_key text,definition_version integer,semantic_type text,context_kind text,context_id text,active_binding_id uuid,active_instrument_id text,active_instrument_version integer,active_scale_reference text,active_scale_version integer,active_model_id text,active_model_version integer,measurement_event_id uuid,event_observed_at timestamptz,measurement_observation_id uuid,response_code text,observation_instrument_id text,observation_instrument_version integer,observation_scale_reference text,observation_scale_version integer,snapshot_id uuid,value_state text,numeric_value double precision,validity_status text,snapshot_provenance text,calculation_result_id uuid,canonical_binding_id uuid,snapshot_scale_reference text,snapshot_scale_version integer,result_state text,result_numeric_value double precision,result_model_id text,result_model_version integer,result_provenance text,result_confidence_state text,result_confidence_reference text,source_binding_status text,source_instrument_id text,source_instrument_version integer,source_scale_reference text,source_scale_version integer,source_model_id text,source_model_version integer)
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path='' AS $$
DECLARE u uuid:=auth.uid();
BEGIN
 IF u IS NULL THEN RAISE EXCEPTION 'Authentication required' USING ERRCODE='42501';END IF;
 RETURN QUERY SELECT * FROM public.read_him_intelligence_snapshot_core_v1(u,p_context_kind,p_context_id);
END$$;
REVOKE ALL ON FUNCTION public.read_him_intelligence_snapshot_v1(text,text) FROM PUBLIC,anon,service_role;
GRANT EXECUTE ON FUNCTION public.read_him_intelligence_snapshot_v1(text,text) TO authenticated;

CREATE FUNCTION public.background_read_him_conversation_snapshot_v1(p_user_id uuid,p_session_id uuid)
RETURNS TABLE(generated_at timestamptz,slot_order integer,metric_key text,definition_version integer,semantic_type text,context_kind text,context_id text,active_binding_id uuid,active_instrument_id text,active_instrument_version integer,active_scale_reference text,active_scale_version integer,active_model_id text,active_model_version integer,measurement_event_id uuid,event_observed_at timestamptz,measurement_observation_id uuid,response_code text,observation_instrument_id text,observation_instrument_version integer,observation_scale_reference text,observation_scale_version integer,snapshot_id uuid,value_state text,numeric_value double precision,validity_status text,snapshot_provenance text,calculation_result_id uuid,canonical_binding_id uuid,snapshot_scale_reference text,snapshot_scale_version integer,result_state text,result_numeric_value double precision,result_model_id text,result_model_version integer,result_provenance text,result_confidence_state text,result_confidence_reference text,source_binding_status text,source_instrument_id text,source_instrument_version integer,source_scale_reference text,source_scale_version integer,source_model_id text,source_model_version integer)
LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path='' AS $$
BEGIN
 IF p_user_id IS NULL OR p_session_id IS NULL THEN RAISE EXCEPTION 'Background HIM conversation snapshot identity required' USING ERRCODE='22023';END IF;
 RETURN QUERY SELECT * FROM public.read_him_intelligence_snapshot_core_v1(p_user_id,'CONVERSATION_SESSION',p_session_id::text);
END$$;
REVOKE ALL ON FUNCTION public.background_read_him_conversation_snapshot_v1(uuid,uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.background_read_him_conversation_snapshot_v1(uuid,uuid) TO service_role;
COMMIT;
