-- W3-MEGA-A — Account & Identity Completion + Security v1 (E2E-D-03 Name, E2E-D-05 Login ID, E2E-D-08 Shared ID
-- format backend).
--
-- Additive and forward-only. Migrations 0001–0128 are untouched: no table, trigger, grant or function of theirs is
-- dropped, replaced or re-granted. Every new privileged part lives in the non-exposed `account_private` schema that
-- 0125 created; every new function in the exposed `public` schema is SECURITY INVOKER.
--
-- ## What this adds
--
--   1. The owner's own account identity read: Name and Login ID (P1 §8.1), under the owner's own row-level security.
--   2. The owner's Name change (P1 §2.3): the one canonical Name, normalized exactly as sign-up stores it (0123:
--      trimmed, 1–80 characters, no control characters). No First / Last split.
--   3. The owner's Login ID change (P1 §2.1): private, unique, case-insensitive, no cooldown and no lifetime limit;
--      the old Login ID stops resolving at the commit (0124 resolves the CURRENT value only). It needs appropriate
--      identity verification, and the DATABASE demands it: the caller's token must carry a password authentication
--      made within the last minute (`amr` method `password`, the provider's own claim). That token exists only
--      after the provider itself validated the password (W2-01's password grant), so the reauthentication is the
--      provider's proof, checked where the write happens — never a flag a client can set.
--   4. The Shared ID's human-facing format (W3-PDG-01 §4): 12 random characters grouped 3 × 4 (`K7QM-4XWD-P9TR` is a
--      pattern), case-insensitive, generated by the server. Only its opaque derived reference is stored (0081's representation
--      boundary); the value itself is stored nowhere. A generated regeneration command reuses 0081's frozen
--      rotation unchanged, so the epoch law (PENDING invitations of an older epoch become INVALIDATED; born Worlds
--      untouched) is 0081's own. NO client role may execute it: the Shared ID has no surface before W6.
--
-- ## Implementation details (not Product authority)
--
--   * The Shared ID alphabet is Crockford base-32 (digits and upper-case letters without I, L, O, U). A typed value
--     is upper-cased, spaces and hyphens are ignored, O reads as 0 and I / L read as 1, and it is regrouped. The
--     randomness is `gen_random_uuid()` (PostgreSQL's strong random source): 60 random bits per Shared ID.
--   * The Login ID change keeps an idempotency ledger of command identities and a SHA-256 digest of the requested
--     value — never the value itself — so a replayed command is answered with its committed truth and a late
--     duplicate can never re-apply an old value. The ledger rows go with the account (ON DELETE CASCADE).
--   * The one-minute proof window is an engineering bound on "just proved", not a Product rule: the API spends a proof
--     within milliseconds of earning it. A device session whose password sign-in is under a minute old also carries
--     such a claim; that is itself a password authentication by the provider (W3-MEGA-A record §13).
BEGIN;

-- ---------------------------------------------------------------------------------------------------------------
-- 1. The owner's own identity read. No Email (the provider holds it), no Public ID (0125 reads it), no id.
-- ---------------------------------------------------------------------------------------------------------------
CREATE FUNCTION public.read_own_account_identity_v1()
RETURNS TABLE (name text, login_id text)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
    SELECT u.name, u.login_id
      FROM public.users u
     WHERE u.id = (SELECT auth.uid());
$$;

-- ---------------------------------------------------------------------------------------------------------------
-- 2. The owner's Name change. Bounded outcomes, each with the caller's resulting Name:
--      CHANGED    committed (a repeat of the same value is UNCHANGED, which is the same truth);
--      UNCHANGED  the normalized value is the current Name: nothing is written;
--      INVALID    empty after trimming, over 80 characters, a control character, or an account that has no
--                 sign-up identity (0123's pair rule keeps Name and Login ID together): nothing is written.
-- Setting a value is naturally idempotent, so a lost answer is reconciled by reading the Name again.
-- ---------------------------------------------------------------------------------------------------------------
CREATE FUNCTION account_private.change_own_account_name_v1(p_name text)
RETURNS TABLE (outcome text, current_name text)
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_user uuid := (SELECT auth.uid());
    v_requested text := btrim(p_name);
    v_account public.users;
BEGIN
    IF v_user IS NULL THEN
        RAISE EXCEPTION 'an authenticated caller is required' USING ERRCODE = '42501';
    END IF;

    SELECT * INTO v_account FROM public.users u WHERE u.id = v_user FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'account was not found' USING ERRCODE = 'P0002';
    END IF;

    IF v_account.login_id IS NULL
       OR v_requested IS NULL
       OR char_length(v_requested) NOT BETWEEN 1 AND 80
       OR v_requested ~ '[[:cntrl:]]' THEN
        RETURN QUERY SELECT 'INVALID'::text, v_account.name;
        RETURN;
    END IF;

    IF v_requested = v_account.name THEN
        RETURN QUERY SELECT 'UNCHANGED'::text, v_account.name;
        RETURN;
    END IF;

    UPDATE public.users
       SET name = v_requested,
           updated_at = CURRENT_TIMESTAMP
     WHERE id = v_user;

    RETURN QUERY SELECT 'CHANGED'::text, v_requested;
END;
$$;

CREATE FUNCTION public.change_own_account_name_v1(p_name text)
RETURNS TABLE (outcome text, current_name text)
LANGUAGE sql
VOLATILE
SECURITY INVOKER
SET search_path = ''
AS $$
    SELECT c.outcome, c.current_name
      FROM account_private.change_own_account_name_v1(p_name) c;
$$;

-- ---------------------------------------------------------------------------------------------------------------
-- 3. The owner's Login ID change.
-- ---------------------------------------------------------------------------------------------------------------

-- The idempotency ledger: which command changed which account to which (digested) value. Not exposed, no client
-- privilege, and it holds no Login ID in clear.
CREATE TABLE account_private.login_id_change_commands (
    command_id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    requested_digest text NOT NULL,
    committed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT login_id_change_commands_digest_check CHECK (requested_digest ~ '^[0-9a-f]{64}$')
);
ALTER TABLE account_private.login_id_change_commands ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE account_private.login_id_change_commands FROM PUBLIC;

-- Whether the caller's token carries a password authentication made within the last minute. It reads the
-- request's own verified claims (PostgREST sets them from the provider-signed token), so no caller can assert it.
CREATE FUNCTION account_private.has_recent_password_proof_v1()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1
          FROM jsonb_array_elements(
                   CASE WHEN jsonb_typeof(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'amr') = 'array'
                        THEN nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'amr'
                        ELSE '[]'::jsonb END) AS a(entry)
         WHERE jsonb_typeof(a.entry) = 'object'
           AND a.entry ->> 'method' = 'password'
           -- The cast is reached only for a JSON number: AND gives no evaluation order, CASE does.
           AND CASE WHEN jsonb_typeof(a.entry -> 'timestamp') = 'number'
                    THEN (a.entry ->> 'timestamp')::numeric BETWEEN extract(epoch FROM clock_timestamp()) - 60
                                                              AND extract(epoch FROM clock_timestamp()) + 60
                    ELSE false END
    );
$$;

-- Bounded outcomes, each with the caller's resulting Login ID:
--   CHANGED      committed now — or the SAME command replayed after it committed;
--   UNCHANGED    the normalized value is the current Login ID: nothing is written;
--   INVALID      not a well-formed Login ID (0123's grammar), the caller's OWN Public ID (0125's same-row rule), or
--                an account without a sign-up identity: nothing is written;
--   UNAVAILABLE  another account holds it: nothing is written, and nothing about that account is returned.
-- Without a recent password proof nothing is read or written (42501 LOGIN_ID_REAUTHENTICATION_REQUIRED). A command
-- identity reused for another value, or by another account, is refused (23505 LOGIN_ID_COMMAND_CONFLICT).
-- The caller's own row is the serialization point; two accounts racing for one value meet the unique index.
CREATE FUNCTION account_private.change_own_login_id_v1(p_command_id uuid, p_login_id text)
RETURNS TABLE (outcome text, current_login_id text)
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_user uuid := (SELECT auth.uid());
    v_requested text := lower(btrim(p_login_id));
    v_digest text;
    v_account public.users;
    v_committed account_private.login_id_change_commands;
    v_conflict text;
BEGIN
    IF v_user IS NULL THEN
        RAISE EXCEPTION 'an authenticated caller is required' USING ERRCODE = '42501';
    END IF;
    IF NOT account_private.has_recent_password_proof_v1() THEN
        RAISE EXCEPTION 'LOGIN_ID_REAUTHENTICATION_REQUIRED' USING ERRCODE = '42501';
    END IF;
    IF p_command_id IS NULL THEN
        RAISE EXCEPTION 'LOGIN_ID_COMMAND_INVALID' USING ERRCODE = '22023';
    END IF;
    v_digest := encode(sha256(convert_to(coalesce(v_requested, ''), 'UTF8')), 'hex');

    SELECT * INTO v_account FROM public.users u WHERE u.id = v_user FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'account was not found' USING ERRCODE = 'P0002';
    END IF;

    -- The same command again: its committed truth, or a refusal if it now asks for something else.
    SELECT * INTO v_committed FROM account_private.login_id_change_commands c WHERE c.command_id = p_command_id;
    IF FOUND THEN
        IF v_committed.user_id = v_user AND v_committed.requested_digest = v_digest THEN
            RETURN QUERY SELECT 'CHANGED'::text, v_account.login_id;
            RETURN;
        END IF;
        RAISE EXCEPTION 'LOGIN_ID_COMMAND_CONFLICT' USING ERRCODE = '23505';
    END IF;

    IF v_account.login_id IS NULL
       OR v_requested IS NULL
       OR char_length(v_requested) NOT BETWEEN 3 AND 30
       OR v_requested !~ '^[a-z0-9]+([._-][a-z0-9]+)*$' THEN
        RETURN QUERY SELECT 'INVALID'::text, v_account.login_id;
        RETURN;
    END IF;

    IF v_requested = v_account.login_id THEN
        RETURN QUERY SELECT 'UNCHANGED'::text, v_account.login_id;
        RETURN;
    END IF;

    -- The caller's OWN Public ID, from the caller's own locked row — never any other account's.
    IF v_requested = v_account.public_id THEN
        RETURN QUERY SELECT 'INVALID'::text, v_account.login_id;
        RETURN;
    END IF;

    BEGIN
        UPDATE public.users
           SET login_id = v_requested,
               updated_at = CURRENT_TIMESTAMP
         WHERE id = v_user;
    EXCEPTION WHEN unique_violation THEN
        GET STACKED DIAGNOSTICS v_conflict = CONSTRAINT_NAME;
        IF v_conflict = 'users_login_id_key' THEN
            RETURN QUERY SELECT 'UNAVAILABLE'::text, v_account.login_id;
            RETURN;
        END IF;
        RAISE;
    END;

    INSERT INTO account_private.login_id_change_commands (command_id, user_id, requested_digest)
    VALUES (p_command_id, v_user, v_digest);

    RETURN QUERY SELECT 'CHANGED'::text, v_requested;
END;
$$;

CREATE FUNCTION public.change_own_login_id_v1(p_command_id uuid, p_login_id text)
RETURNS TABLE (outcome text, current_login_id text)
LANGUAGE sql
VOLATILE
SECURITY INVOKER
SET search_path = ''
AS $$
    SELECT c.outcome, c.current_login_id
      FROM account_private.change_own_login_id_v1(p_command_id, p_login_id) c;
$$;

-- ---------------------------------------------------------------------------------------------------------------
-- 4. The Shared ID format — backend only; no client role may execute any of it before W6.
-- ---------------------------------------------------------------------------------------------------------------

-- A typed Shared ID in its canonical form `XXXX-XXXX-XXXX`, or NULL when it cannot be one. Case-insensitive;
-- spaces and hyphens are ignored; O reads as 0, and I / L read as 1.
CREATE FUNCTION account_private.normalize_shared_id_v1(p_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SECURITY INVOKER
SET search_path = ''
AS $$
    SELECT CASE WHEN v.compact ~ '^[0-9A-HJKMNP-TV-Z]{12}$'
                THEN substr(v.compact, 1, 4) || '-' || substr(v.compact, 5, 4) || '-' || substr(v.compact, 9, 4)
           END
      FROM (SELECT translate(regexp_replace(upper(coalesce(p_value, '')), '[[:space:]-]', '', 'g'), 'OIL', '011') AS compact) v;
$$;

-- A fresh Shared ID: 12 characters, each five random bits from the strong random source. It reads no account data.
CREATE FUNCTION account_private.generate_shared_id_v1()
RETURNS text
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
    v_alphabet constant text := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
    v_hex text := replace(gen_random_uuid()::text, '-', '');
    -- The first 12 hex digits of a v4 UUID and 3 of its last 12 are fully random: 60 bits.
    v_bits bit(60) := ('x' || substr(v_hex, 1, 12) || substr(v_hex, 21, 3))::bit(60);
    v_out text := '';
    v_index integer;
BEGIN
    FOR v_index IN 0..11 LOOP
        v_out := v_out || substr(v_alphabet, 1 + substring(v_bits FROM v_index * 5 + 1 FOR 5)::integer, 1);
        IF v_index IN (3, 7) THEN
            v_out := v_out || '-';
        END IF;
    END LOOP;
    RETURN v_out;
END;
$$;

-- 0081's REPRESENTATION BOUNDARY: persistence holds only an opaque derived `credential_lookup_ref`, never the
-- human-facing secret ("A later reviewed adapter may change how a human secret becomes this reference"). This is that
-- adapter: a versioned SHA-256 of the canonical Shared ID, or NULL when the typed value cannot be one. Submitting a
-- typed Shared ID means submitting this reference; so a typed value resolves case-insensitively, with or without
-- separators, and no Shared ID — current or past — is ever stored in clear.
CREATE FUNCTION account_private.shared_id_lookup_ref_v1(p_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SECURITY INVOKER
SET search_path = ''
AS $$
    SELECT 'sid1:' || encode(sha256(convert_to(n.canonical, 'UTF8')), 'hex')
      FROM (SELECT account_private.normalize_shared_id_v1(p_value) AS canonical) n
     WHERE n.canonical IS NOT NULL;
$$;

-- The owner's Shared ID, generated by the server: first setup or regeneration. It takes ONLY a command identity —
-- never a value — and hands the generated value's derived reference to 0081's frozen rotation, which locks the
-- credential state, advances the epoch and invalidates every PENDING direct invitation of an older epoch in the same
-- transaction. A generated value whose reference happens to be held is drawn again.
--
-- The new Shared ID itself is returned ONCE, to this privileged caller, and stored nowhere. A replayed command answers
-- its committed epoch with a NULL Shared ID (the value is not kept). How the owner later reads a current Shared ID is
-- the W6 surface's decision, as is granting this command to any role.
CREATE FUNCTION account_private.regenerate_own_shared_id_v1(p_command_id uuid)
RETURNS TABLE (command_id uuid, credential_epoch bigint, shared_id text)
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_user uuid := (SELECT auth.uid());
    v_epoch bigint;
    v_attempt integer := 0;
    v_value text;
    v_result record;
BEGIN
    IF v_user IS NULL THEN
        RAISE EXCEPTION 'an authenticated caller is required' USING ERRCODE = '42501';
    END IF;
    IF p_command_id IS NULL THEN
        RAISE EXCEPTION 'SHARED_ID_COMMAND_INVALID' USING ERRCODE = '22023';
    END IF;

    -- A committed regeneration answers with its own result, whatever has happened since.
    SELECT c.resulting_credential_epoch INTO v_epoch
      FROM public.shared_world_invitation_commands c
     WHERE c.id = p_command_id AND c.actor_user_id = v_user AND c.command_type = 'CREDENTIAL_ROTATION';
    IF FOUND THEN
        RETURN QUERY SELECT p_command_id, v_epoch, NULL::text;
        RETURN;
    END IF;

    SELECT s.epoch INTO v_epoch FROM public.shared_world_invite_credential_state s WHERE s.user_id = v_user;
    LOOP
        v_attempt := v_attempt + 1;
        v_value := account_private.generate_shared_id_v1();
        BEGIN
            SELECT r.command_id, r.credential_epoch INTO v_result
              FROM public.rotate_shared_world_invite_credential_v1(p_command_id, account_private.shared_id_lookup_ref_v1(v_value), v_epoch) r;
            RETURN QUERY SELECT v_result.command_id, v_result.credential_epoch, v_value;
            RETURN;
        EXCEPTION WHEN unique_violation THEN
            -- Only a held value is drawn again; a command conflict is the caller's to see.
            IF SQLERRM <> 'SHARED_INVITE_CREDENTIAL_REF_UNAVAILABLE' OR v_attempt >= 5 THEN
                RAISE;
            END IF;
        END;
    END LOOP;
END;
$$;

-- ---------------------------------------------------------------------------------------------------------------
-- Privileges. Default-deny by name (a hosted project's default privileges can grant a new function to `anon` and
-- `authenticated`, and PUBLIC holds EXECUTE on every new function), then the exact grants.
-- ---------------------------------------------------------------------------------------------------------------
REVOKE ALL ON FUNCTION public.read_own_account_identity_v1() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION account_private.change_own_account_name_v1(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.change_own_account_name_v1(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION account_private.has_recent_password_proof_v1() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION account_private.change_own_login_id_v1(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.change_own_login_id_v1(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION account_private.normalize_shared_id_v1(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION account_private.generate_shared_id_v1() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION account_private.shared_id_lookup_ref_v1(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION account_private.regenerate_own_shared_id_v1(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE account_private.login_id_change_commands FROM anon, authenticated;
DO $$BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
  EXECUTE 'REVOKE ALL ON FUNCTION public.read_own_account_identity_v1(), account_private.change_own_account_name_v1(text), public.change_own_account_name_v1(text), account_private.has_recent_password_proof_v1(), account_private.change_own_login_id_v1(uuid, text), public.change_own_login_id_v1(uuid, text), account_private.normalize_shared_id_v1(text), account_private.generate_shared_id_v1(), account_private.shared_id_lookup_ref_v1(text), account_private.regenerate_own_shared_id_v1(uuid) FROM service_role';
  EXECUTE 'REVOKE ALL ON TABLE account_private.login_id_change_commands FROM service_role';
END IF; END$$;
-- The INVOKER Product wrappers run as `authenticated`, which already holds USAGE on `account_private` (0125).
GRANT EXECUTE ON FUNCTION public.read_own_account_identity_v1() TO authenticated;
GRANT EXECUTE ON FUNCTION account_private.change_own_account_name_v1(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.change_own_account_name_v1(text) TO authenticated;
GRANT EXECUTE ON FUNCTION account_private.change_own_login_id_v1(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.change_own_login_id_v1(uuid, text) TO authenticated;

COMMIT;
