import { BadRequestException } from '@nestjs/common';
import { HimCalculationModelRegistry } from './him-calculation.registry';
import { HimCalculationService } from './him-calculation.service';
import type { HimCalculationModel, HimMetricCalculationInput } from './him-calculation.types';

const definition={metricKey:'test.synthetic.signal',definitionVersion:1,validContextKinds:['SITUATION']};
const definitions={get:(k:string,v:number)=>k===definition.metricKey&&v===v?definition:undefined} as never;
const model=(changes:Partial<HimCalculationModel>={}):HimCalculationModel=>({modelId:'test.synthetic.deterministic',modelVersion:1,targetMetricKey:'test.synthetic.signal',targetDefinitionVersion:1,lifecycle:'VALIDATED',environment:'TEST_ONLY',canonicalOwner:'HIM_TEST_FIXTURE',canonicalSource:'ARCHITECTURE_TEST_ONLY',methodType:'SYNTHETIC_REQUIRED_INPUT',scaleContractReference:'TEST_ONLY_BOOLEAN_V1',requiredInputKeys:['signal'],requiredEvidenceContract:'OWNED_EVIDENCE_REFS_V1',supportedContextKinds:['SITUATION'],missingDataBehavior:'UNASSESSED',contradictionBehavior:'UNASSESSED_PRESERVE_CONFLICT',confidenceContract:'UNRESOLVED_METRIC_CONFIDENCE',implementationId:'test.synthetic.v1',createdAt:'2026-08-18T00:00:00.000Z',versionedAt:'2026-08-18T00:00:00.000Z',...changes});
const input=(changes:Partial<HimMetricCalculationInput>={}):HimMetricCalculationInput=>({metricKey:'test.synthetic.signal',definitionVersion:1,modelId:'test.synthetic.deterministic',modelVersion:1,context:{kind:'SITUATION',id:'fixture-1'},inputs:{},supportingEvidenceRefs:['memory:00000000-0000-4000-8000-000000000001'],contradictoryEvidenceRefs:[],provenance:'HIM_CALCULATION_RUNTIME_V1',traceId:'trace-1',updateReason:'ARCHITECTURE_TEST',...changes});

describe('HIM calculation/calibration runtime',()=>{
  it('bounds identity, version, lifecycle, and target',()=>{const r=new HimCalculationModelRegistry(definitions);expect(()=>r.register(model({modelId:'BAD ID'}))).toThrow(BadRequestException);expect(()=>r.register(model({modelVersion:0}))).toThrow();expect(()=>r.register(model({lifecycle:'OTHER' as never}))).toThrow();expect(()=>r.register(model({targetMetricKey:'missing.metric'}))).toThrow();});
  it('isolates test-only models from production metrics and promotion',()=>{const productionDefinitions={get:()=>({...definition,metricKey:'hse.stress',validContextKinds:['SITUATION','CONVERSATION_SESSION']})} as never;const r=new HimCalculationModelRegistry(productionDefinitions);expect(()=>r.register(model({targetMetricKey:'hse.stress'}))).toThrow(/Test-only/);const isolated=new HimCalculationModelRegistry(definitions);isolated.register(model());expect(()=>isolated.promote('test.synthetic.deterministic',1,{approvalId:'a',modelId:'test.synthetic.deterministic',modelVersion:1,authorityId:'internal',authorityVersion:1,approvedAt:new Date().toISOString(),canonicalSource:'fixture'})).toThrow(/eligible/);});
  it('returns UNASSESSED/null for missing input and preserves contradictions separately',async()=>{const r=new HimCalculationModelRegistry(definitions);r.register(model());const s=new HimCalculationService(r);const missing=await s.calculate(input());expect(missing.resultState).toBe('UNASSESSED');expect(missing.numericValue).toBeNull();expect(missing.missingInputKeys).toEqual(['signal']);const conflict=await s.calculate(input({inputs:{signal:true},contradictoryEvidenceRefs:['memory:00000000-0000-4000-8000-000000000002']}));expect(conflict.contradictionState).toBe('PRESENT_UNRESOLVED');expect(conflict.supportingEvidenceRefs).not.toEqual(conflict.contradictoryEvidenceRefs);expect(conflict.numericValue).toBeNull();});
  it('enforces exact context and model/result identity without hypothesis confidence substitution',async()=>{const r=new HimCalculationModelRegistry(definitions);r.register(model());const s=new HimCalculationService(r);await expect(s.calculate(input({context:{kind:'GOAL',id:'00000000-0000-4000-8000-000000000003'}}))).rejects.toThrow(/context/);const result=await s.calculate(input());expect(result.confidenceState).toBe('UNASSESSED');expect(result.confidenceReference).toBeNull();expect(()=>s.validateResult(input(),{...result,modelVersion:2})).toThrow(/identity/);});
});

