import type { HimContextKind } from './him.types';

export type HimTrendAssessmentState='ASSESSED'|'UNASSESSED';
export type HimTrendDirection='INCREASING'|'DECREASING'|'UNCHANGED'|'MIXED';
export type HimTrendUnassessedReason='INSUFFICIENT_COMPARABLE_OBSERVATIONS'|'UNSUPPORTED_METRIC'|'UNSUPPORTED_CONTEXT'|'INVALID_OR_UNOWNED_CONTEXT'|'WINDOW_REQUIRED'|'WINDOW_OVERFLOW'|'INCOMPATIBLE_MEASUREMENT_VERSIONS'|'INTEGRITY_FAILURE';
export type HimOrdinalCategory='VERY_LOW'|'LOW'|'MODERATE'|'HIGH'|'VERY_HIGH';

export interface HimTrendRequest {metricKey:string;definitionVersion:number;contextKind:HimContextKind;contextId:string;windowStart?:string;windowEnd?:string;}
export interface HimTrendSourcePoint {id:string;user_id:string;metric_key:string;definition_version:number;context_kind:HimContextKind;context_id:string;observed_at:string;value_state:string;numeric_value:number|null;validity_status:string;canonical_provenance:string;measurement_event_id:string|null;measurement_observation_id:string|null;calculation_result_id:string|null;canonical_binding_id:string|null;scale_contract_reference:string|null;scale_version:number|null;instrument_id:string|null;instrument_version:number|null;model_id:string|null;model_version:number|null;binding_metric_key:string|null;binding_definition_version:number|null;binding_context_kind:string|null;}
export interface HimTrendSource {points:HimTrendSourcePoint[];excludedObservationCount:number;activeBinding:{id:string;metricKey:string;definitionVersion:number;contextKind:HimContextKind;instrumentId:string;instrumentVersion:number;scaleReference:string;scaleVersion:number;modelId:string;modelVersion:number;}|null;}
export interface HimTrendResult {trendAssessmentState:HimTrendAssessmentState;trendDirection:HimTrendDirection|null;unassessedReason:HimTrendUnassessedReason|null;metricKey:string;definitionVersion:number;contextKind:HimContextKind;contextId:string;windowStart:string;windowEnd:string;eligibleObservationCount:number;excludedObservationCount:number;firstCategory:HimOrdinalCategory|null;latestCategory:HimOrdinalCategory|null;firstObservedAt:string|null;latestObservedAt:string|null;instrumentId:string|null;instrumentVersion:number|null;scaleReference:string|null;scaleVersion:number|null;modelId:string|null;modelVersion:number|null;sourceMeasurementEventIds:string[];confidenceState:'UNASSESSED';confidenceReference:null;trendContractVersion:1;calculatedAt:string;}
