import { HimTrendService,HIM_TREND_CONTEXTS } from './him-trend.service';
import type { HimTrendRequest,HimTrendSourcePoint } from './him-trend.types';
const context='00000000-0000-4000-8000-000000000010',user='00000000-0000-4000-8000-000000000001';
const request:HimTrendRequest={metricKey:'hse.stress',definitionVersion:1,contextKind:'SITUATION',contextId:context,windowStart:'2026-01-01T00:00:00.000Z',windowEnd:'2026-02-01T00:00:00.000Z'};
const binding={id:'binding',metricKey:'hse.stress',definitionVersion:1,contextKind:'SITUATION' as const,instrumentId:'instrument',instrumentVersion:1,scaleReference:'scale',scaleVersion:1,modelId:'model',modelVersion:1};
const point=(n:number,i:number):HimTrendSourcePoint=>({id:`p${String(i).padStart(3,'0')}`,user_id:user,metric_key:'hse.stress',definition_version:1,context_kind:'SITUATION',context_id:context,observed_at:`2026-01-${String(i+1).padStart(2,'0')}T00:00:00.000Z`,value_state:'ASSESSED',numeric_value:n,validity_status:'VALID',canonical_provenance:'QANDEEL_HIM_RUNTIME_FOUNDATION_V1',measurement_event_id:`e${i}`,measurement_observation_id:`o${i}`,calculation_result_id:`r${i}`,canonical_binding_id:'binding',scale_contract_reference:'scale',scale_version:1,instrument_id:'instrument',instrument_version:1,model_id:'model',model_version:1,binding_metric_key:'hse.stress',binding_definition_version:1,binding_context_kind:'SITUATION'});
const service=(values:number[],excluded=0)=>new HimTrendService({readTrendSource:jest.fn().mockResolvedValue({points:values.map(point),excludedObservationCount:excluded,activeBinding:binding})} as never);
describe('HIM ordinal trend v1',()=>{
 it('admits exactly five calibrated metrics and exact context allowlists',()=>{expect(Object.keys(HIM_TREND_CONTEXTS).sort()).toEqual(['hse.attention','hse.energy','hse.motivation','hse.self-confidence','hse.stress']);expect(HIM_TREND_CONTEXTS).toEqual({'hse.energy':['CONVERSATION_SESSION'],'hse.motivation':['GOAL','SITUATION'],'hse.attention':['SITUATION','CONVERSATION_SESSION','DECISION'],'hse.self-confidence':['SITUATION','DECISION'],'hse.stress':['SITUATION','CONVERSATION_SESSION']});});
 it.each(['hbs.avoidance','hbs.consistency','hbs.initiative','hbs.reflection','hrs.relationship-trust','hrs.communication','hrs.repair','hrs.emotional-safety','hgs.self-awareness','hgs.resilience','hgs.purpose-alignment','hgs.habit-strength'])('fails closed for %s',async metricKey=>expect((await service([]).assess(user,'t',{...request,metricKey})).unassessedReason).toBe('UNSUPPORTED_METRIC'));
 it('requires an explicit valid half-open window',async()=>{expect((await service([]).assess(user,'t',{...request,windowStart:undefined})).unassessedReason).toBe('WINDOW_REQUIRED');});
 it.each([[[1,1,1],'UNCHANGED'],[[1,2,2,5],'INCREASING'],[[5,4,4,1],'DECREASING'],[[1,4,2],'MIXED']] as const)('classifies %j as %s',async(values,direction)=>expect((await service([...values]).assess(user,'t',request)).trendDirection).toBe(direction));
 it('requires two points and preserves unresolved confidence',async()=>{const r=await service([1],2).assess(user,'t',request);expect(r).toMatchObject({trendAssessmentState:'UNASSESSED',unassessedReason:'INSUFFICIENT_COMPARABLE_OBSERVATIONS',eligibleObservationCount:1,excludedObservationCount:2,confidenceState:'UNASSESSED',confidenceReference:null});});
 it('allows 128 and rejects 129 without truncation',async()=>{expect((await service(Array(128).fill(1)).assess(user,'t',request)).trendAssessmentState).toBe('ASSESSED');expect((await service(Array(129).fill(1)).assess(user,'t',request)).unassessedReason).toBe('WINDOW_OVERFLOW');});
 it('fails incompatible bindings and malformed provenance closed',async()=>{const repo={readTrendSource:jest.fn().mockResolvedValue({points:[point(1,0),{...point(2,1),canonical_binding_id:'other'}],excludedObservationCount:0,activeBinding:binding})};expect((await new HimTrendService(repo as never).assess(user,'t',request)).unassessedReason).toBe('INCOMPATIBLE_MEASUREMENT_VERSIONS');const malformed={readTrendSource:jest.fn().mockResolvedValue({points:[point(1,0),{...point(2,1),measurement_event_id:null}],excludedObservationCount:0,activeBinding:binding})};expect((await new HimTrendService(malformed as never).assess(user,'t',request)).unassessedReason).toBe('INTEGRITY_FAILURE');});
 it('returns only bounded ordered event ids and no prohibited arithmetic fields',async()=>{const r=await service([1,2]).assess(user,'t',request);expect(r.sourceMeasurementEventIds).toEqual(['e0','e1']);for(const key of['average','delta','percentage','slope','velocity','confidenceScore'])expect(key in r).toBe(false);});
});
