import type { HimContextKind,HimValidityStatus } from './him.types';

export type HimSnapshotContextKind=Extract<HimContextKind,'SITUATION'|'CONVERSATION_SESSION'|'DECISION'|'GOAL'>;
export type HimSnapshotCoverageState='FULL'|'PARTIAL'|'EMPTY';
export type HimSnapshotUnassessedReason='NO_MEASUREMENT_EVENT'|'LATEST_EVENT_UNASSESSED'|'LATEST_EVENT_INVALIDATED'|'INCOMPATIBLE_ACTIVE_BINDING';
export type HimSnapshotOrdinalCategory='VERY_LOW'|'LOW'|'MODERATE'|'HIGH'|'VERY_HIGH';

export interface HimIntelligenceSnapshotRequest {contextKind:HimContextKind;contextId:string;}
export interface HimIntelligenceSnapshotMetric {metricKey:string;definitionVersion:1;semanticType:'STATE';valueState:'ASSESSED'|'UNASSESSED';unassessedReason:HimSnapshotUnassessedReason|null;ordinalCategory:HimSnapshotOrdinalCategory|null;scaleReference:string|null;scaleVersion:number|null;observedAt:string|null;freshnessState:'UNASSESSED';freshnessReference:null;confidenceState:'UNASSESSED';confidenceReference:null;validityStatus:HimValidityStatus|null;measurementEventId:string|null;measurementObservationId:string|null;calculationResultId:string|null;canonicalBindingId:string|null;instrumentId:string|null;instrumentVersion:number|null;modelId:string|null;modelVersion:number|null;}
export interface HimIntelligenceSnapshot {snapshotContractVersion:1;contextKind:HimSnapshotContextKind;contextId:string;generatedAt:string;coverageState:HimSnapshotCoverageState;eligibleMetricCount:number;assessedMetricCount:number;unassessedMetricCount:number;metrics:HimIntelligenceSnapshotMetric[];}

export interface HimSnapshotSourceRow {generated_at:string;slot_order:number;metric_key:string;definition_version:number;semantic_type:string;context_kind:string;context_id:string;active_binding_id:string|null;active_instrument_id:string|null;active_instrument_version:number|null;active_scale_reference:string|null;active_scale_version:number|null;active_model_id:string|null;active_model_version:number|null;measurement_event_id:string|null;event_observed_at:string|null;measurement_observation_id:string|null;response_code:string|null;observation_instrument_id:string|null;observation_instrument_version:number|null;observation_scale_reference:string|null;observation_scale_version:number|null;snapshot_id:string|null;value_state:string|null;numeric_value:number|null;validity_status:string|null;snapshot_provenance:string|null;calculation_result_id:string|null;canonical_binding_id:string|null;snapshot_scale_reference:string|null;snapshot_scale_version:number|null;result_state:string|null;result_numeric_value:number|null;result_model_id:string|null;result_model_version:number|null;result_provenance:string|null;result_confidence_state:string|null;result_confidence_reference:string|null;source_binding_status:string|null;source_instrument_id:string|null;source_instrument_version:number|null;source_scale_reference:string|null;source_scale_version:number|null;source_model_id:string|null;source_model_version:number|null;}
