import { Injectable } from '@nestjs/common';
import { MemoryDataApiService } from '../memory/memory-data-api.service';
import type { CreateHimMetricObservation,HimMetricDefinition,HimMetricSnapshot } from './him.types';
@Injectable()
export class HimRepository {
  constructor(private readonly dataApi:MemoryDataApiService){}
  async getDefinition(token:string,key:string,version:number):Promise<HimMetricDefinition|undefined>{const rows=await this.dataApi.request<Record<string,unknown>[]>(token,'rpc/get_him_metric_definition',{method:'POST',body:JSON.stringify({p_metric_key:key,p_definition_version:version})});return rows[0]?this.definition(rows[0]):undefined;}
  async listDefinitions(token:string):Promise<HimMetricDefinition[]>{return(await this.dataApi.request<Record<string,unknown>[]>(token,'rpc/list_him_metric_definitions',{method:'POST',body:'{}'})).map(r=>this.definition(r));}
  async createObservation(token:string,value:CreateHimMetricObservation):Promise<HimMetricSnapshot>{return(await this.dataApi.request<HimMetricSnapshot[]>(token,'rpc/create_him_metric_snapshot',{method:'POST',body:JSON.stringify({p_observation:value})}))[0];}
  async getLatest(token:string,userId:string,key:string,kind:string,id:string){const q=new URLSearchParams({select:'*',user_id:`eq.${userId}`,metric_key:`eq.${key}`,context_kind:`eq.${kind}`,context_id:`eq.${id}`,order:'snapshot_version.desc',limit:'1'});return(await this.dataApi.request<HimMetricSnapshot[]>(token,`him_metric_snapshots?${q}`))[0];}
  listForContext(token:string,userId:string,kind:string,id:string){const q=new URLSearchParams({select:'*',user_id:`eq.${userId}`,context_kind:`eq.${kind}`,context_id:`eq.${id}`,order:'created_at.desc,id.asc',limit:'128'});return this.dataApi.request<HimMetricSnapshot[]>(token,`him_metric_snapshots?${q}`);}
  history(token:string,userId:string,key:string,kind:string,id:string){const q=new URLSearchParams({select:'*',user_id:`eq.${userId}`,metric_key:`eq.${key}`,context_kind:`eq.${kind}`,context_id:`eq.${id}`,order:'snapshot_version.asc',limit:'128'});return this.dataApi.request<HimMetricSnapshot[]>(token,`him_metric_snapshots?${q}`);}
  private definition(r:Record<string,unknown>):HimMetricDefinition{return{metricKey:r.metric_key as string,canonicalName:r.canonical_name as string,canonicalDefinition:r.canonical_definition as string,canonicalSource:r.canonical_source as string,hifOwner:r.hif_owner as HimMetricDefinition['hifOwner'],semanticMappingStatus:r.semantic_mapping_status as HimMetricDefinition['semanticMappingStatus'],semanticType:r.semantic_type as HimMetricDefinition['semanticType'],definitionVersion:r.definition_version as number,calculationStatus:r.calculation_status as HimMetricDefinition['calculationStatus'],scaleReference:r.scale_reference as string,validContextKinds:r.valid_context_kinds as HimMetricDefinition['validContextKinds'],requiredInputContract:r.required_input_contract as string,confidenceRequirementReference:r.confidence_requirement_reference as string,consumers:r.consumers as string[],sourceMetadata:r.source_metadata as string[],dependencyIds:r.dependency_ids as string[]};}
}

