import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { HIM_CONTEXT_KINDS,HIM_VALIDITY_STATUSES,HIM_VALUE_STATES,MAX_HIM_CONTEXT_ID_LENGTH,MAX_HIM_EVIDENCE_PER_ROLE,type CreateHimMetricObservation,type HimContextKind } from './him.types';
import { HimRepository } from './him.repository';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const boundedUnique=(v:string[],max:number,f:string,memory=false):void=>{if(!Array.isArray(v)||v.length>max||new Set(v).size!==v.length||v.some(x=>typeof x!=='string'||x.length===0||x.length>128||(memory&&!/^memory:[0-9a-f-]{36}$/i.test(x))))throw new BadRequestException(`Invalid ${f}.`);};
@Injectable()
export class HimService {
  constructor(private readonly repository:HimRepository){}
  async observe(userId:string,token:string,o:Omit<CreateHimMetricObservation,'id'>){
    this.validateObservation(o);const definition=await this.repository.getDefinition(token,o.metricKey,o.definitionVersion);if(!definition)throw new NotFoundException('HIM metric definition not found.');
    if(!definition.validContextKinds.includes(o.contextKind))throw new BadRequestException('Metric definition does not support this exact context kind.');
    if(o.valueState==='ASSESSED'&&definition.calculationStatus!=='CALIBRATED')throw new BadRequestException('HIM metric has no approved calibrated calculation model.');
    return this.repository.createObservation(token,{id:randomUUID(),metricKey:o.metricKey,definitionVersion:o.definitionVersion,valueState:o.valueState,...(o.valueState==='ASSESSED'?{numericValue:o.numericValue}:{}),supportingEvidenceIds:o.supportingEvidenceIds??[],contradictingEvidenceIds:o.contradictingEvidenceIds??[],contextKind:o.contextKind,contextId:o.contextId,scope:o.scope,...(o.temporalWindowStart?{temporalWindowStart:o.temporalWindowStart,temporalWindowEnd:o.temporalWindowEnd}:{}),validityStatus:o.validityStatus,descriptiveUpdateReason:o.descriptiveUpdateReason,descriptiveUpdateReferenceIds:o.descriptiveUpdateReferenceIds??[]});
  }
  async getLatest(userId:string,token:string,key:string,definitionVersion:number,kind:HimContextKind,id:string){
    this.validateContext(kind,id);
    if(typeof key!=='string'||key.length===0||key.length>128||!Number.isSafeInteger(definitionVersion)||definitionVersion<1)throw new BadRequestException('Invalid definition identity.');
    const definition=await this.repository.getDefinition(token,key,definitionVersion);if(!definition)throw new NotFoundException('HIM metric definition not found.');
    if(!definition.validContextKinds.includes(kind))throw new BadRequestException('Metric definition does not support this exact context kind.');
    return this.repository.getLatest(token,userId,key,definitionVersion,kind,id);
  }
  listForContext(userId:string,token:string,kind:HimContextKind,id:string){this.validateContext(kind,id);return this.repository.listForContext(token,userId,kind,id);} history(userId:string,token:string,key:string,kind:HimContextKind,id:string){this.validateContext(kind,id);return this.repository.history(token,userId,key,kind,id);}
  private validateObservation(v:Omit<CreateHimMetricObservation,'id'>):void{if(!HIM_VALUE_STATES.includes(v.valueState)||!HIM_VALIDITY_STATUSES.includes(v.validityStatus))throw new BadRequestException('Invalid HIM state.');if(v.valueState==='UNASSESSED'&&v.numericValue!==undefined)throw new BadRequestException('Unassessed metrics cannot carry a value.');if(v.valueState==='ASSESSED'&&(typeof v.numericValue!=='number'||!Number.isFinite(v.numericValue)))throw new BadRequestException('Assessed metrics require a finite numeric value.');if(!Number.isSafeInteger(v.definitionVersion)||v.definitionVersion<1||typeof v.metricKey!=='string'||v.metricKey.length>128)throw new BadRequestException('Invalid definition identity.');this.validateContext(v.contextKind,v.contextId);if(typeof v.scope!=='string'||v.scope.trim()!==v.scope||v.scope.length===0||v.scope.length>256||typeof v.descriptiveUpdateReason!=='string'||v.descriptiveUpdateReason.trim()!==v.descriptiveUpdateReason||v.descriptiveUpdateReason.length===0||v.descriptiveUpdateReason.length>500)throw new BadRequestException('Invalid scope or descriptive update reason.');boundedUnique(v.supportingEvidenceIds??[],MAX_HIM_EVIDENCE_PER_ROLE,'supportingEvidenceIds',true);boundedUnique(v.contradictingEvidenceIds??[],MAX_HIM_EVIDENCE_PER_ROLE,'contradictingEvidenceIds',true);boundedUnique(v.descriptiveUpdateReferenceIds??[],MAX_HIM_EVIDENCE_PER_ROLE,'descriptiveUpdateReferenceIds',true);if((v.supportingEvidenceIds??[]).some(id=>(v.contradictingEvidenceIds??[]).includes(id)))throw new BadRequestException('Invalid HIM evidence roles.');if((v.temporalWindowStart===undefined)!==(v.temporalWindowEnd===undefined)||(v.temporalWindowStart&&(!Number.isFinite(Date.parse(v.temporalWindowStart))||!Number.isFinite(Date.parse(v.temporalWindowEnd!))||Date.parse(v.temporalWindowStart)>Date.parse(v.temporalWindowEnd!))))throw new BadRequestException('Invalid temporal window.');}
  private validateContext(kind:HimContextKind,id:string):void{if(!HIM_CONTEXT_KINDS.includes(kind)||typeof id!=='string'||id.trim()!==id||id.length===0||id.length>MAX_HIM_CONTEXT_ID_LENGTH)throw new BadRequestException('Invalid exact HIM context.');if(kind==='GLOBAL'?id!=='GLOBAL':id==='GLOBAL'||(!UUID.test(id)&&kind!=='SITUATION'))throw new BadRequestException('Context identity does not match its kind.');}
}

