import { BadRequestException, NotFoundException } from '@nestjs/common';
import { HimService } from './him.service';

const user='11111111-1111-4111-8111-111111111111', decision='22222222-2222-4222-8222-222222222222';
const base={ metricKey:'test.metric',definitionVersion:3,valueState:'UNASSESSED' as const,sourceEngines:['HIM_INTEGRATION'],contextKind:'DECISION' as const,contextId:decision,scope:'exact decision',validityStatus:'VALID' as const,updateReason:'test observation' };
const setup=()=>{ const repository={getDefinition:jest.fn().mockResolvedValue({metricKey:'test.metric',definitionVersion:3,semanticType:'STATE',validContextKinds:['DECISION']}),createObservation:jest.fn().mockImplementation(async(_:string,value:object)=>value),getLatest:jest.fn(),listForContext:jest.fn(),history:jest.fn()}; return {service:new HimService(repository as never),repository}; };

describe('HimService',()=>{
  it('preserves missingness instead of substituting numeric zero',async()=>{ const {service,repository}=setup(); const result=await service.observe(user,'token',base); expect(result).not.toHaveProperty('numericValue'); expect(repository.createObservation).toHaveBeenCalledWith('token',expect.objectContaining({valueState:'UNASSESSED',definitionVersion:3})); });
  it('allows assessed numeric zero and enforces the assessed structure',async()=>{ const {service}=setup(); await expect(service.observe(user,'token',{...base,valueState:'ASSESSED',numericValue:0})).resolves.toEqual(expect.objectContaining({numericValue:0})); await expect(service.observe(user,'token',{...base,valueState:'ASSESSED'})).rejects.toBeInstanceOf(BadRequestException); });
  it('rejects fabricated values on unassessed observations',async()=>{ const {service}=setup(); await expect(service.observe(user,'token',{...base,numericValue:0})).rejects.toBeInstanceOf(BadRequestException); });
  it('keeps metric confidence absent and never substitutes hypothesis confidence',async()=>{ const {service,repository}=setup(); await service.observe(user,'token',base); expect(repository.createObservation.mock.calls[0][1]).not.toHaveProperty('confidence'); expect(repository.createObservation.mock.calls[0][1]).not.toHaveProperty('confidenceEvaluationId'); });
  it('requires an exact supported context and cannot silently generalize to GLOBAL',async()=>{ const {service,repository}=setup(); await service.getLatest(user,'token','test.metric','DECISION',decision); expect(repository.getLatest).toHaveBeenCalledWith('token',user,'test.metric','DECISION',decision); await expect(service.observe(user,'token',{...base,contextKind:'GLOBAL',contextId:'GLOBAL'})).rejects.toBeInstanceOf(BadRequestException); });
  it('fails closed on unknown definition identity/version',async()=>{ const {service,repository}=setup(); repository.getDefinition.mockResolvedValue(undefined); await expect(service.observe(user,'token',base)).rejects.toBeInstanceOf(NotFoundException); });
  it.each([{...base,diagnosis:'x'},{...base,personality:'x'},{...base,formula:'x'},{...base,trend:'up'}])('persists no diagnosis, personality, formula, or trend fields',async(value)=>{ const {service,repository}=setup(); await service.observe(user,'token',value); expect(repository.createObservation.mock.calls[0][1]).toEqual(expect.not.objectContaining({diagnosis:expect.anything(),personality:expect.anything(),formula:expect.anything(),trend:expect.anything()})); });
});
