import { BadRequestException } from '@nestjs/common';
import type { HimCalculationModel,HimMetricCalculationInput,HimMetricCalculationResult } from './him-calculation.types';
export const HSE_STRESS_MODEL_ID='hse.stress.direct-structured-self-report';
export const HSE_STRESS_MODEL_VERSION=1;
export const HSE_STRESS_INSTRUMENT_ID='hse.stress.direct-self-report';
export const HSE_STRESS_SCALE_REFERENCE='hse.stress.ordinal-5.v1';
export const HSE_STRESS_RESPONSES=['VERY_LOW','LOW','MODERATE','HIGH','VERY_HIGH','NOT_SURE'] as const;
type Response=(typeof HSE_STRESS_RESPONSES)[number];
interface Observation{observationId:string;measurementEventId:string;userId:string;metricKey:'hse.stress';definitionVersion:1;contextKind:'SITUATION'|'CONVERSATION_SESSION';contextId:string;instrumentId:typeof HSE_STRESS_INSTRUMENT_ID;instrumentVersion:1;scaleContractReference:typeof HSE_STRESS_SCALE_REFERENCE;scaleVersion:1;responseCode:Response;reportTimestamp:string;source:'DIRECT_STRUCTURED_USER_REPORT';superseded:boolean;}
export const HSE_STRESS_MODEL=Object.freeze<HimCalculationModel>({modelId:HSE_STRESS_MODEL_ID,modelVersion:1,targetMetricKey:'hse.stress',targetDefinitionVersion:1,lifecycle:'CALIBRATED',environment:'PRODUCTION',canonicalOwner:'QANDEEL_HIM_GOVERNANCE',canonicalSource:'ISSUE_66_HSE_STRESS_MEASUREMENT_MODEL_V1',methodType:'DIRECT_STRUCTURED_SELF_REPORT',scaleContractReference:HSE_STRESS_SCALE_REFERENCE,requiredInputKeys:['observation'],requiredEvidenceContract:'FIRST_CLASS_AUTHORIZED_CONTEXT_HIM_MEASUREMENT_OBSERVATION_V1',supportedContextKinds:['SITUATION','CONVERSATION_SESSION'],missingDataBehavior:'UNASSESSED',contradictionBehavior:'UNASSESSED_PRESERVE_CONFLICT',confidenceContract:'UNRESOLVED_METRIC_CONFIDENCE',implementationId:'hse-stress-direct-structured-v1',createdAt:'2026-08-23T00:00:00.000Z',versionedAt:'2026-08-23T00:00:00.000Z'});
const SCORES:Readonly<Record<Exclude<Response,'NOT_SURE'>,number>>=Object.freeze({VERY_LOW:1,LOW:2,MODERATE:3,HIGH:4,VERY_HIGH:5});
export function calculateHseStress(input:HimMetricCalculationInput):HimMetricCalculationResult{const o=input.inputs.observation as Observation|undefined;const base={metricKey:input.metricKey,definitionVersion:input.definitionVersion,modelId:input.modelId,modelVersion:input.modelVersion,context:{...input.context},missingInputKeys:o?[]:['observation'],supportingEvidenceRefs:[...input.supportingEvidenceRefs],contradictoryEvidenceRefs:[...input.contradictoryEvidenceRefs],calculatedAt:new Date().toISOString(),provenance:input.provenance,confidenceState:'UNASSESSED' as const,confidenceReference:null,traceId:input.traceId,updateReason:input.updateReason};if(!o)return{...base,resultState:'UNASSESSED',numericValue:null,contradictionState:'NONE'};if(!['SITUATION','CONVERSATION_SESSION'].includes(input.context.kind)||o.contextKind!==input.context.kind||o.contextId!==input.context.id)throw new BadRequestException('Stress exact context mismatch.');if(o.metricKey!=='hse.stress'||o.definitionVersion!==1||o.instrumentId!==HSE_STRESS_INSTRUMENT_ID||o.instrumentVersion!==1||o.scaleContractReference!==HSE_STRESS_SCALE_REFERENCE||o.scaleVersion!==1||o.source!=='DIRECT_STRUCTURED_USER_REPORT'||!Number.isFinite(Date.parse(o.reportTimestamp))||!HSE_STRESS_RESPONSES.includes(o.responseCode))throw new BadRequestException('Stress observation contract mismatch.');if(o.superseded)throw new BadRequestException('Superseded Stress observation cannot be calculated.');if(input.contradictoryEvidenceRefs.length)return{...base,resultState:'UNASSESSED',numericValue:null,contradictionState:'PRESENT_UNRESOLVED'};if(o.responseCode==='NOT_SURE')return{...base,resultState:'UNASSESSED',numericValue:null,contradictionState:'NONE'};return{...base,resultState:'ASSESSED',numericValue:SCORES[o.responseCode],contradictionState:'NONE'};}


