import { BadRequestException } from '@nestjs/common';
import { calculateHseEnergy,HSE_ENERGY_INSTRUMENT_ID,HSE_ENERGY_MODEL_ID,HSE_ENERGY_SCALE_REFERENCE } from './hse-energy.model';
import type { HimMetricCalculationInput } from './him-calculation.types';
const session='11111111-1111-4111-8111-111111111111',user='22222222-2222-4222-8222-222222222222';
const observation=(responseCode:string,changes:Record<string,unknown>={})=>({observationId:'33333333-3333-4333-8333-333333333333',measurementEventId:'44444444-4444-4444-8444-444444444444',userId:user,metricKey:'hse.energy',definitionVersion:1,contextKind:'CONVERSATION_SESSION',contextId:session,instrumentId:HSE_ENERGY_INSTRUMENT_ID,instrumentVersion:1,scaleContractReference:HSE_ENERGY_SCALE_REFERENCE,scaleVersion:1,responseCode,reportTimestamp:'2026-08-22T12:00:00.000Z',locale:'ar-EG',source:'DIRECT_STRUCTURED_USER_REPORT',superseded:false,...changes});
const input=(responseCode='LOW',changes:Partial<HimMetricCalculationInput>={}):HimMetricCalculationInput=>({metricKey:'hse.energy',definitionVersion:1,modelId:HSE_ENERGY_MODEL_ID,modelVersion:1,context:{kind:'CONVERSATION_SESSION',id:session},inputs:{observation:observation(responseCode)},supportingEvidenceRefs:['measurement-observation:33333333-3333-4333-8333-333333333333'],contradictoryEvidenceRefs:[],provenance:'QANDEEL_HIM_CALCULATION_RUNTIME_V1',traceId:'trace-energy-1',updateReason:'DIRECT_STRUCTURED_USER_REPORT',...changes});
describe('HSE Energy direct structured report v1',()=>{
 it.each([['VERY_LOW',1],['LOW',2],['MODERATE',3],['HIGH',4],['VERY_HIGH',5]])('maps %s to %i',(response,score)=>expect(calculateHseEnergy(input(response)).numericValue).toBe(score));
 it('keeps NOT_SURE and missing input unassessed',()=>{expect(calculateHseEnergy(input('NOT_SURE'))).toEqual(expect.objectContaining({resultState:'UNASSESSED',numericValue:null}));expect(calculateHseEnergy(input('LOW',{inputs:{}}))).toEqual(expect.objectContaining({resultState:'UNASSESSED',numericValue:null,missingInputKeys:['observation']}));});
 it('rejects SITUATION, wrong instrument/scale/locale/source/context and out-of-contract values',()=>{expect(()=>calculateHseEnergy(input('LOW',{context:{kind:'SITUATION',id:'work'}}))).toThrow();for(const change of [{instrumentId:'other'},{scaleContractReference:'other'},{locale:'en'},{source:'MODEL_INFERENCE'},{contextId:'other'},{responseCode:'3.5'}])expect(()=>calculateHseEnergy(input('LOW',{inputs:{observation:observation('LOW',change)}}))).toThrow(BadRequestException);});
 it('rejects superseded observations and preserves unresolved conflict/confidence separation',()=>{expect(()=>calculateHseEnergy(input('LOW',{inputs:{observation:observation('LOW',{superseded:true})}}))).toThrow(/Superseded/);const r=calculateHseEnergy(input('HIGH',{contradictoryEvidenceRefs:['measurement-observation:55555555-5555-4555-8555-555555555555']}));expect(r).toEqual(expect.objectContaining({resultState:'UNASSESSED',numericValue:null,contradictionState:'PRESENT_UNRESOLVED',confidenceState:'UNASSESSED',confidenceReference:null}));});
});
