import type { HimMetricDefinition } from './him.types';

const common = {
  definitionVersion: 1,
  calculationStatus: 'UNCALIBRATED' as const,
  scaleReference: 'UNCALIBRATED_NO_PRODUCTION_SCALE',
  requiredInputContract: 'APPROVED_MEASUREMENT_MODEL_REQUIRED',
  confidenceRequirementReference: 'UNRESOLVED_METRIC_CONFIDENCE_MODEL',
  consumers: [] as string[],
  sourceMetadata: ['HIF_PART_8_HUMAN_INTELLIGENCE_METRICS_V0_1'],
  dependencyIds: [] as string[],
};

const metric = (
  metricKey: string, canonicalName: string, hifOwner: HimMetricDefinition['hifOwner'],
  semanticType: HimMetricDefinition['semanticType'], validContextKinds: HimMetricDefinition['validContextKinds'],
  note: string,
): HimMetricDefinition => ({
  ...common, metricKey, canonicalName, hifOwner, semanticType,
  semanticMappingStatus: semanticType === null ? 'UNRESOLVED' : 'RESOLVED', validContextKinds,
  canonicalDefinition: `Canonical HIF Part 8 ${hifOwner} metric identity: ${canonicalName}. ${note}`,
  canonicalSource: `HIF Part 8 — Human Intelligence Metrics v0.1 / ${hifOwner}`,
});

/** The single application catalog; migration 0010 is its integrity-enforced persisted projection. */
export const INITIAL_HIM_METRICS = Object.freeze([
  {...metric('hse.stress','Stress','HSE','STATE',['SITUATION','CONVERSATION_SESSION'],'Direct structured RIGHT_NOW subjective psychological-pressure self-report is approved for exact owned contexts only.'),calculationStatus:'CALIBRATED',scaleReference:'hse.stress.ordinal-5.v1',requiredInputContract:'DIRECT_STRUCTURED_AUTHORIZED_CONTEXT_USER_REPORT_RIGHT_NOW_V1'},
  {...metric('hse.energy','Energy','HSE','STATE',['CONVERSATION_SESSION'],'Direct structured ar-EG RIGHT_NOW self-report is approved for CONVERSATION_SESSION only.'),calculationStatus:'CALIBRATED',scaleReference:'hse.energy.ordinal-5.v1',requiredInputContract:'DIRECT_STRUCTURED_USER_REPORT_AR_EG_RIGHT_NOW_V1'},
  {...metric('hse.motivation','Motivation','HSE','STATE',['SITUATION','GOAL'],'Direct structured RIGHT_NOW target-bound self-report is approved for GOAL and SITUATION only.'),calculationStatus:'CALIBRATED',scaleReference:'hse.motivation.ordinal-5.v1',requiredInputContract:'DIRECT_STRUCTURED_TARGET_BOUND_USER_REPORT_RIGHT_NOW_V1'},
  {...metric('hse.self-confidence','Confidence','HSE','STATE',['SITUATION','DECISION'],'Direct structured RIGHT_NOW self-report is approved for exact owned SITUATION and DECISION contexts only; not Hypothesis Confidence Runtime.'),calculationStatus:'CALIBRATED',scaleReference:'hse.self-confidence.ordinal-5.v1',requiredInputContract:'DIRECT_STRUCTURED_AUTHORIZED_CONTEXT_USER_REPORT_RIGHT_NOW_V1'},
  {...metric('hse.attention','Attention','HSE','STATE',['SITUATION','CONVERSATION_SESSION','DECISION'],'Direct structured RIGHT_NOW self-report is approved for exact owned contexts only.'),calculationStatus:'CALIBRATED',scaleReference:'hse.attention.ordinal-5.v1',requiredInputContract:'DIRECT_STRUCTURED_AUTHORIZED_CONTEXT_USER_REPORT_RIGHT_NOW_V1'},
  {...metric('hbs.avoidance','Avoidance','HBS',null,['SITUATION','GOAL'],'Direct structured target-bound seven-day retrospective behavioral-frequency self-report is approved for exact owned GOAL and SITUATION targets only; semantic mapping remains unresolved and it is not a permanent trait.'),calculationStatus:'CALIBRATED',scaleReference:'hbs.avoidance.frequency-5.v1',requiredInputContract:'DIRECT_STRUCTURED_TARGET_BOUND_PERIOD_USER_REPORT_SEVEN_DAY_V1'},
  {...metric('hbs.consistency','Consistency','HBS',null,['SITUATION','GOAL'],'Direct structured target-bound seven-day retrospective follow-through-frequency self-report is approved for exact owned GOAL and SITUATION targets only; semantic mapping remains unresolved, it is not a permanent trait, and it is independent of Initiative and Avoidance.'),calculationStatus:'CALIBRATED',scaleReference:'hbs.consistency.frequency-5.v1',requiredInputContract:'DIRECT_STRUCTURED_TARGET_BOUND_PERIOD_USER_REPORT_SEVEN_DAY_V1'},
  {...metric('hbs.initiative','Initiative','HBS',null,['SITUATION','GOAL'],'Direct structured target-bound seven-day retrospective self-initiated-start-frequency self-report is approved for exact owned GOAL and SITUATION targets only; semantic mapping remains unresolved, it is not a permanent trait, and it is independent of Consistency and Avoidance.'),calculationStatus:'CALIBRATED',scaleReference:'hbs.initiative.frequency-5.v1',requiredInputContract:'DIRECT_STRUCTURED_TARGET_BOUND_PERIOD_USER_REPORT_SEVEN_DAY_V1'},
  {...metric('hbs.reflection','Reflection','HBS',null,['SITUATION','CONVERSATION_SESSION'],'Direct structured context-bound at-report deliberate reflective-engagement self-report is approved for exactly one owned SITUATION or CONVERSATION_SESSION context only; semantic mapping remains unresolved, no temporal window exists, and it is not a permanent trait, rumination, self-awareness, or insight accuracy.'),calculationStatus:'CALIBRATED',scaleReference:'hbs.reflection.engagement-5.v1',requiredInputContract:'DIRECT_STRUCTURED_AUTHORIZED_CONTEXT_REFLECTIVE_ENGAGEMENT_REPORT_V1'},
  {...metric('hrs.relationship-trust','Trust','HRS',null,['RELATIONSHIP'],'Direct structured relationship-bound current reliance-trust self-report is approved for exactly one owned RELATIONSHIP measurement target only; semantic mapping remains unresolved, no temporal window exists, and it is not SENA, provider, epistemic, or global trust, not objective trustworthiness, not love or closeness, and not Emotional Safety, Communication, or Repair.'),calculationStatus:'CALIBRATED',scaleReference:'hrs.relationship-trust.reliance-5.v1',requiredInputContract:'DIRECT_STRUCTURED_RELATIONSHIP_BOUND_CURRENT_RELIANCE_REPORT_V1'},
  {...metric('hrs.communication','Communication','HRS',null,['RELATIONSHIP'],'Direct structured relationship-bound current communication-workability self-report is approved for exactly one owned RELATIONSHIP measurement target only; semantic mapping remains unresolved, no temporal window exists, and it is not talking frequency, agreement, satisfaction, love or closeness, Trust, Repair, or Emotional Safety.'),calculationStatus:'CALIBRATED',scaleReference:'hrs.communication.workability-5.v1',requiredInputContract:'DIRECT_STRUCTURED_RELATIONSHIP_BOUND_CURRENT_COMMUNICATION_WORKABILITY_REPORT_V1'},
  {...metric('hrs.repair','Repair','HRS',null,['RELATIONSHIP'],'Direct structured relationship-bound current repair-effectiveness-after-rupture self-report is approved for exactly one owned RELATIONSHIP measurement target only; semantic mapping remains unresolved, no temporal window exists, and it is not absence of conflict, forgiveness, reconciliation, Communication quality, Trust, or Emotional Safety.'),calculationStatus:'CALIBRATED',scaleReference:'hrs.repair.effectiveness-5.v1',requiredInputContract:'DIRECT_STRUCTURED_RELATIONSHIP_BOUND_CURRENT_REPAIR_EFFECTIVENESS_REPORT_V1'},
  {...metric('hrs.emotional-safety','Emotional Safety','HRS',null,['RELATIONSHIP'],'Direct structured relationship-bound current emotional-openness-safety self-report is approved for exactly one owned RELATIONSHIP measurement target only; semantic mapping remains unresolved, no temporal window exists, and it is subjective perceived safety of emotional exposure only - not objective/physical/abuse safety, not an abuse or danger classifier, not relationship health, not Trust, Communication, or Repair, and never Safety Runtime authority.'),calculationStatus:'CALIBRATED',scaleReference:'hrs.emotional-safety.openness-safety-5.v1',requiredInputContract:'DIRECT_STRUCTURED_RELATIONSHIP_BOUND_CURRENT_EMOTIONAL_OPENNESS_SAFETY_REPORT_V1'},
  {...metric('hgs.self-awareness','Self-awareness','HGS',null,['GOAL','SITUATION'],'Direct structured target-bound current self-understanding-clarity self-report is approved for exactly one owned GOAL or SITUATION target only; semantic mapping remains unresolved, no temporal window or growth trajectory exists, and it is perceived clarity only - not Reflection, rumination, Self-Confidence, objective insight accuracy, or growth outcome.'),calculationStatus:'CALIBRATED',scaleReference:'hgs.self-awareness.clarity-5.v1',requiredInputContract:'DIRECT_STRUCTURED_TARGET_BOUND_CURRENT_SELF_UNDERSTANDING_CLARITY_REPORT_V1'},
  {...metric('hgs.resilience','Resilience','HGS',null,['GOAL','SITUATION'],'Direct structured target-bound current adaptive-recovery self-report under actually experienced challenge is approved for exactly one owned GOAL or SITUATION target only; semantic mapping remains unresolved, no temporal window, recovery-time score, or growth trajectory exists, and it is perceived adaptive continuity/recovery only - not low Stress, Motivation, Self-Confidence, Consistency, Habit Strength, grit, goal success, HRS Repair, or a global resilience trait.'),calculationStatus:'CALIBRATED',scaleReference:'hgs.resilience.adaptive-recovery-5.v1',requiredInputContract:'DIRECT_STRUCTURED_TARGET_BOUND_CURRENT_ADAPTIVE_RECOVERY_REPORT_V1'},
  {...metric('hgs.purpose-alignment','Purpose Alignment','HGS','ALIGNMENT',['GOAL'],'Direct structured goal-bound current perceived purpose-congruence self-report is approved for exactly one owned GOAL target only; the resolved ALIGNMENT semantic mapping is preserved, no temporal window, motive-subscale weighting, or value hierarchy exists, and it is perceived congruence with personally meaningful values/priorities/direction only - not Motivation, Self-Awareness, Resilience, Consistency, Habit Strength, goal importance, goal success, or moral/safety approval.'),calculationStatus:'CALIBRATED',scaleReference:'hgs.purpose-alignment.congruence-5.v1',requiredInputContract:'DIRECT_STRUCTURED_GOAL_BOUND_CURRENT_PURPOSE_CONGRUENCE_REPORT_V1'},
  {...metric('hgs.habit-strength','Habit Strength','HGS',null,['GOAL','SITUATION'],'Direct structured target-bound current cue-linked-automaticity self-report grounded in sufficient repeated experience is approved for exactly one owned GOAL or SITUATION target only; semantic mapping remains unresolved, no temporal window, streak, repetition count, or time-to-habit score exists, and it is perceived cue-linked automaticity of one specific recurring action only - not Consistency, follow-through frequency, Initiative, Motivation, Purpose Alignment, discipline, grit, compulsion, or addiction.'),calculationStatus:'CALIBRATED',scaleReference:'hgs.habit-strength.automaticity-5.v1',requiredInputContract:'DIRECT_STRUCTURED_TARGET_BOUND_CURRENT_CUE_LINKED_AUTOMATICITY_REPORT_V1'},
] satisfies readonly HimMetricDefinition[]);

