/**
 * GENERATED by apps/mobile/scripts/generate-p2-production.mjs — do not edit by hand.
 *
 * VPORT-02: the production geometry of the frozen P2 machines (Temporal Spine + Aperture C "Parting"; Call Rail A
 * "Keyed Seam") and the Call Rail glyphs, produced by executing the merged P2-A package's own functions and
 * source-locking its frozen lines. The aperture, notch, terminal and discontinuity dimensions are P2-A reference
 * CRAFT values (P2 closure §7), not Product law. Regenerate after any source changes; the VPORT-02 contract fails on
 * drift.
 *
 * Sources (sha256):
 *   docs/design/p2-iconography/QANDEEL_P2-A_FINAL_ICONOGRAPHY_INTEGRATED_VISUAL_PROOF/source/src/app.js  bcbd688ccb0bc23a3b2c8800065e462633e67328e1e454aa0a61d73bc8111edd
 *   docs/design/p2-iconography/QANDEEL_P2-A_FINAL_ICONOGRAPHY_INTEGRATED_VISUAL_PROOF/source/src/machines.mjs  6360e8c0959f049c7186487a26473466fb07573b7cff1d111276526ab44c807c
 *   docs/design/p2-iconography/QANDEEL_P2-A_FINAL_ICONOGRAPHY_INTEGRATED_VISUAL_PROOF/source/src/sig.mjs  960ecd84edd75da91ee6a7c391504bb0ee4f15b92c8bea120847289caca4dde2
 */
export const P2_SPINE = {
  "provenance": "P2-A Temporal Spine block, variant C \"Parting\" (accepted); reference CRAFT values, not Product law",
  "stepPoints": 48,
  "bandPoints": 44,
  "axisY": 22,
  "spine": {
    "strokeWidth": 1,
    "opacity": 0.55
  },
  "notch": {
    "restHeight": 6,
    "targetHeight": 12,
    "restStrokeWidth": 1,
    "targetStrokeWidth": 1.5,
    "restOpacity": 0.85
  },
  "aperture": {
    "halfWidth": 17,
    "frameWidth": 34,
    "committed": {
      "d": "M0.00 22C7.50 22 8.00 14 17.00 14C26.00 14 26.50 22 34.00 22M0.00 22C7.50 22 8.00 30 17.00 30C26.00 30 26.50 22 34.00 22",
      "strokeWidth": 1.5,
      "mark": {
        "x": 16,
        "y": 18,
        "width": 2,
        "height": 8,
        "r": 1
      }
    },
    "preview": {
      "d": "M0.00 22C7.50 22 8.00 14 17.00 14C26.00 14 26.50 22 34.00 22M0.00 22C7.50 22 8.00 30 17.00 30C26.00 30 26.50 22 34.00 22",
      "strokeWidth": 1
    },
    "settleScale": 0.09
  },
  "terminal": {
    "frame": 44,
    "stop": {
      "d": "M8 13V31",
      "strokeWidth": 1.5
    },
    "present": {
      "d": "M14.5 22H29",
      "availableStrokeWidth": 1.25,
      "engagedStrokeWidth": 3
    }
  },
  "discontinuity": {
    "inset": 6,
    "spacing": 4,
    "radius": 1,
    "opacity": 0.7,
    "count": 3
  }
} as const;

export const P2_CALL_RAIL = {
  "provenance": "P2-A machines.mjs railArt(\"A\") — Call Rail A \"Keyed Seam\" (accepted)",
  "lineHeight": 64,
  "slots": {
    "end": {
      "end": 12,
      "width": 44
    },
    "mic": {
      "end": 78,
      "width": 44
    },
    "route": {
      "end": 122,
      "width": 44
    }
  },
  "group": {
    "end": 70,
    "width": 104,
    "height": 48,
    "top": 8,
    "d": "M16 .5H103.5L95.5 47.5H16A15.5 15.5 0 0 1 .5 32V16A15.5 15.5 0 0 1 16 .5Z",
    "strokeWidth": 1
  },
  "terminal": {
    "end": 6,
    "width": 68,
    "height": 48,
    "top": 8,
    "d": "M10.5 .5H52A15.5 15.5 0 0 1 67.5 16V32A15.5 15.5 0 0 1 52 47.5H2.5Z",
    "strokeWidth": 1
  },
  "glyphPx": {
    "mic": 24,
    "route": 24,
    "end": 27
  }
} as const;

export const P2_CALL_GLYPHS = {
  "provenance": "P2-A sig.mjs, nuance N1 \"Open\", at the frozen render sizes",
  "grid": 24,
  "mic": {
    "size": 24,
    "strokeWidth": 1.6,
    "capsule": {
      "x": 9,
      "y": 3,
      "width": 6,
      "height": 11.2,
      "r": 3
    },
    "cradle": "M5.6 11.2a6.4 6.4 0 0 0 12.8 0M12 17.6v3",
    "slash": "M4.2 3.6 19.8 20.4",
    "cutbandWidth": 4.2
  },
  "route": {
    "size": 24,
    "strokeWidth": 1.6,
    "body": "M3.6 10.2c0-.7.5-1.2 1.2-1.2h2.4l4-3.5c.5-.4 1.2-.1 1.2.6v11.8c0 .7-.7 1-1.2.6l-4-3.5H4.8c-.7 0-1.2-.5-1.2-1.2z",
    "innerWave": "M14.809 9.325A3.6 3.6 0 0 1 14.809 14.675",
    "outerWave": "M16.956 6.169A7.4 7.4 0 0 1 16.956 17.831"
  },
  "endCall": {
    "size": 27,
    "d": "M3.4 14.6c-.1-1.5.3-2.8 1.5-3.7C6.8 9.5 9.3 8.8 12 8.8s5.2.7 7.1 2.1c1.2.9 1.6 2.2 1.5 3.7l-.1.8c-.1.8-.8 1.3-1.6 1.2l-2.7-.5c-.7-.1-1.2-.7-1.2-1.4v-1.5c-1-.4-2-.6-3-.6s-2 .2-3 .6v1.5c0 .7-.5 1.3-1.2 1.4l-2.7.5c-.8.1-1.5-.4-1.6-1.2z"
  }
} as const;
