/**
 * GENERATED by apps/mobile/scripts/generate-p3-production.mjs — do not edit by hand.
 *
 * A3-01: the production geometry of the two P3 glyph members — Open Ledger (the «النشاط» / Activity entry) and Open
 * Link (the Introductions Activity-row source mark) — produced by executing the merged P3-A package's own
 * `p3glyphs.mjs` on P2's unchanged `sig.mjs`. The A3-01 contract fails on drift.
 *
 * Sources (sha256):
 *   docs/design/p3-notifications/QANDEEL_P3-A_NOTIFICATION_ACTIVITY_INTEGRATED_VISUAL_PROOF/source/src/p3glyphs.mjs  f636ddd5c3de049d3203f8d9ae640bbf7e91918b4e3381b923aa0c263c920d1e
 *   docs/design/p3-notifications/QANDEEL_P3-A_NOTIFICATION_ACTIVITY_INTEGRATED_VISUAL_PROOF/source/src/sig.mjs  960ecd84edd75da91ee6a7c391504bb0ee4f15b92c8bea120847289caca4dde2
 *   docs/design/p2-iconography/QANDEEL_P2-A_FINAL_ICONOGRAPHY_INTEGRATED_VISUAL_PROOF/source/src/sig.mjs  960ecd84edd75da91ee6a7c391504bb0ee4f15b92c8bea120847289caca4dde2
 */
export const P3_GLYPHS = {
  "provenance": "P3-A source/src/p3glyphs.mjs on P2-A sig.mjs (byte-identical); frozen by the P3 closure §5",
  "ledger": {
    "size": 22,
    "grid": 24,
    "mirrorsInRtl": false,
    "strokes": [
      {
        "d": "M20 14.8V6A2 2 0 0 0 18 4H6A2 2 0 0 0 4 6V18A2 2 0 0 0 6 20H14.8",
        "strokeWidth": 1.66
      },
      {
        "d": "M8 9.2H16M8 13.2H16",
        "strokeWidth": 1.66
      }
    ],
    "dots": []
  },
  "link": {
    "size": 20,
    "grid": 24,
    "mirrorsInRtl": false,
    "strokes": [
      {
        "d": "M5.3 5.3L10.462 10.462M18.7 18.7L13.538 13.538",
        "strokeWidth": 1.75
      }
    ],
    "dots": [
      {
        "cx": 5.3,
        "cy": 5.3,
        "r": 1.886
      },
      {
        "cx": 18.7,
        "cy": 18.7,
        "r": 1.886
      }
    ]
  }
} as const;
