import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
const sql=readFileSync(new URL('../migrations/0012_hse_energy_measurement_model_v1.sql',import.meta.url),'utf8');
test('defines exact ar-EG RIGHT_NOW instrument and ordinal scale',()=>{assert.match(sql,/hse\.energy\.ar-eg\.right-now/);assert.match(sql,/DIRECT_STRUCTURED_USER_REPORT/);assert.match(sql,/locale='ar-EG'/);assert.match(sql,/allowed_codes=ARRAY\[1,2,3,4,5\]/);assert.match(sql,/CHECK\(NOT interval_operations\)/);assert.match(sql,/CHECK\(NOT ratio_operations\)/);});
test('separates events from context and preserves correction history',()=>{assert.match(sql,/CREATE TABLE public\.him_measurement_events/);assert.match(sql,/CREATE TABLE public\.him_measurement_observations/);assert.match(sql,/context_kind='CONVERSATION_SESSION'/);assert.match(sql,/supersedes_observation_id/);assert.match(sql,/observation_immutable BEFORE UPDATE OR DELETE/);});
test('activates exactly one approved Energy binding',()=>{assert.match(sql,/him_one_active_canonical_binding/);assert.match(sql,/hse\.energy\.direct-structured-user-report/);assert.match(sql,/QANDEEL_FOUNDATION_GOVERNANCE/);assert.match(sql,/external_validation_claimed boolean NOT NULL CHECK\(NOT external_validation_claimed\)/);assert.match(sql,/calculation_status='CALIBRATED'.*metric_key='hse\.energy'/s);});
test('blocks direct assessed forgery and protects canonical writes',()=>{assert.match(sql,/Assessed HIM snapshots require trusted calculation provenance/);assert.match(sql,/SECURITY DEFINER/g);assert.match(sql,/REVOKE ALL ON public\.him_scale_contracts.*authenticated/s);assert.match(sql,/GRANT EXECUTE ON FUNCTION public\.create_hse_energy_measurement/);});
test('enforces server time, supersession, idempotency, and protected binding lifecycle',()=>{assert.match(sql,/client_reported_at_untrusted/);assert.match(sql,/canonical_now timestamptz:=clock_timestamp\(\)/);assert.match(sql,/him_energy_calculation_supersessions/);assert.match(sql,/him_current_energy_measurements/);assert.match(sql,/him_energy_one_result_per_observation_binding/);assert.match(sql,/activate_him_canonical_model_binding/);assert.match(sql,/REVOKE ALL ON FUNCTION public\.activate_him_canonical_model_binding\(uuid\) FROM PUBLIC,anon,authenticated/);assert.match(sql,/Canonical binding approval does not approve its exact model version/);});
test('serializes correction and calculation on the observation before currentness validation',()=>{const locks=sql.match(/pg_advisory_xact_lock\(hashtextextended\('hse\.energy\.observation:'\|\|p_(?:supersedes_)?observation_id::text,0\)\)/g)??[];assert.equal(locks.length,2);assert.ok(sql.indexOf("'hse.energy.observation:'||p_observation_id::text")<sql.indexOf('SELECT * INTO o FROM public.him_measurement_observations'));});
test('does not add providers, inference, memory, confidence, trends or arithmetic',()=>{assert.doesNotMatch(sql,/openai|claude|gemini|embedding|INSERT INTO public\.memories|UPDATE public\.hypotheses|UPDATE public\.confidence|trend|average|percentage/i);});

