import { HealthService } from './health.service';import type{HealthProbe}from'./health.types';
const probe=(status:string):HealthProbe=>({check:jest.fn().mockResolvedValue(status)}as HealthProbe);
describe('HealthService readiness aggregation',()=>{
 it('is ready when required dependencies pass and optional dependencies are absent',async()=>{const service=new HealthService(probe('available')as never,probe('configured')as never,probe('not_configured')as never,probe('not_configured')as never);await expect(service.readiness()).resolves.toEqual({status:'ready',service:'qandeel-api',dependencies:{database:{requirement:'required',status:'available'},model_provider:{requirement:'required',status:'configured'},runtime_events:{requirement:'optional',status:'not_configured'},observability:{requirement:'optional',status:'not_configured'}}});});
 it.each(['unavailable','timeout','not_configured'])('makes required database %s not ready',async status=>{const result=await new HealthService(probe(status)as never,probe('configured')as never,probe('available')as never,probe('configured')as never).readiness();expect(result.status).toBe('not_ready');expect(result.dependencies.database.status).toBe(status);});
 it('keeps configured-but-degraded Redis and observability optional',async()=>{const result=await new HealthService(probe('available')as never,probe('configured')as never,probe('degraded')as never,probe('degraded')as never).readiness();expect(result.status).toBe('ready');expect(result.dependencies.runtime_events).toEqual({requirement:'optional',status:'degraded'});expect(result.dependencies.observability).toEqual({requirement:'optional',status:'degraded'});});
 it('keeps optional failures degraded while preserving a simultaneous required failure',async()=>{const result=await new HealthService({check:jest.fn().mockRejectedValue(new Error('DB_SECRET'))}as never,probe('configured')as never,{check:jest.fn().mockRejectedValue(new Error('REDIS_SECRET'))}as never,{check:jest.fn().mockRejectedValue(new Error('OTEL_SECRET'))}as never).readiness();expect(result.status).toBe('not_ready');expect(result.dependencies).toMatchObject({database:{status:'unavailable'},runtime_events:{status:'degraded'},observability:{status:'degraded'}});expect(JSON.stringify(result)).not.toMatch(/DB_SECRET|REDIS_SECRET|OTEL_SECRET/);});
 it('runs independent probes concurrently',async()=>{let releases=0;const slow={check:jest.fn(()=>new Promise<string>(resolve=>setTimeout(()=>{releases++;resolve('available');},15)))}as never,service=new HealthService(slow,probe('configured')as never,probe('not_configured')as never,probe('not_configured')as never);await service.readiness();expect(releases).toBe(1);});
});
