import { BadRequestException, NotFoundException } from '@nestjs/common';
import { QuestionService } from './question.service';
import type { InformationGapRecord, QuestionCandidateGenerator } from './question.types';

const user='11111111-1111-4111-8111-111111111111', gapId='22222222-2222-4222-8222-222222222222', hypothesisId='33333333-3333-4333-8333-333333333333';
const gap: InformationGapRecord={ id:gapId,user_id:user,information_needed:'which account is accurate',why_it_matters:'it discriminates between hypotheses',related_hypothesis_ids:[hypothesisId],confidence_evaluation_id:null,user_answerability:'UNASSESSED',preferred_question_type:null,status:'OPEN',version:1,provenance:'QANDEEL_QUESTION_RUNTIME',created_at:'now',updated_at:'now' };
const proposal={ questionText:'What happened first?',questionType:'DISCRIMINATING' as const,informationGapId:gapId,targetHypothesisIds:[hypothesisId],informationNeeded:'event order',answerFormat:'FREE_TEXT' as const };
const setup=()=>{ const hypotheses={find:jest.fn().mockResolvedValue({id:hypothesisId})}; const confidence={find:jest.fn()}; const repository={createGap:jest.fn().mockResolvedValue(gap),findGap:jest.fn().mockResolvedValue(gap),createCandidate:jest.fn().mockImplementation(async(_:string,id:string,p:any)=>({id,user_id:user,question_text:p.questionText,status:'VALIDATED',expected_information_gain:null,question_utility:null,ranking_state:'UNASSESSED'}))}; return {service:new QuestionService(hypotheses as never,confidence as never,repository as never),hypotheses,confidence,repository}; };

describe('QuestionService',()=>{
 it('creates an owned gap only after validating hypothesis ownership',async()=>{ const {service,hypotheses,repository}=setup(); await service.createGap(user,'token',{informationNeeded:'unknown',whyItMatters:'material',relatedHypothesisIds:[hypothesisId]}); expect(hypotheses.find).toHaveBeenCalledWith(user,'token',hypothesisId); expect(repository.createGap).toHaveBeenCalled(); });
 it('fails closed on a cross-user or absent gap',async()=>{ const {service,repository}=setup(); repository.findGap.mockResolvedValue(undefined); await expect(service.generateValidated(user,'token',gapId,{generate:jest.fn()})).rejects.toBeInstanceOf(NotFoundException); });
 it('uses a provider-neutral generator and persists only validated candidates',async()=>{ const {service,repository}=setup(); const generator:QuestionCandidateGenerator={generate:jest.fn().mockResolvedValue([proposal])}; const rows=await service.generateValidated(user,'token',gapId,generator); expect(generator.generate).toHaveBeenCalled(); expect(repository.createCandidate).toHaveBeenCalledTimes(1); expect(rows[0].status).toBe('VALIDATED'); });
 it.each([{...proposal,questionType:'UNKNOWN'}, {...proposal,informationGapId:user}, {...proposal,scratchpad:'secret'}, {...proposal,questionText:' '.repeat(1001)}])('rejects malformed or forbidden proposals',async(bad)=>{ const {service,repository}=setup(); const generator={generate:jest.fn().mockResolvedValue([bad])}; await expect(service.generateValidated(user,'token',gapId,generator as never)).rejects.toBeInstanceOf(BadRequestException); expect(repository.createCandidate).not.toHaveBeenCalled(); });
 it('rejects direct requests for credentials without inventing a sensitivity classifier',async()=>{ const {service,repository}=setup(); const generator={generate:jest.fn().mockResolvedValue([{...proposal,questionText:'What is your password?'}])}; await expect(service.generateValidated(user,'token',gapId,generator)).rejects.toBeInstanceOf(BadRequestException); expect(repository.createCandidate).not.toHaveBeenCalled(); });
 it('rejects normalized duplicates for one gap before any persistence',async()=>{ const {service,repository}=setup(); const generator={generate:jest.fn().mockResolvedValue([proposal,{...proposal,questionText:'  what   happened FIRST? '}])}; await expect(service.generateValidated(user,'token',gapId,generator)).rejects.toBeInstanceOf(BadRequestException); expect(repository.createCandidate).not.toHaveBeenCalled(); });
 it('does not turn model calibration alone into a user gap',async()=>{ const {service,confidence}=setup(); confidence.find.mockResolvedValue({target_type:'HYPOTHESIS',target_id:hypothesisId,missing_information_codes:['CONFIDENCE_MODEL_UNCALIBRATED']}); await expect(service.createGap(user,'token',{informationNeeded:'calibration',whyItMatters:'confidence',relatedHypothesisIds:[hypothesisId],confidenceEvaluationId:gapId})).rejects.toBeInstanceOf(BadRequestException); });
 // QIR-006 compatibility: the migration-0063 durable lifecycle makes closure
 // real, so a closed gap is no longer a valid candidate generation target -
 // and the generator is never even invoked against one.
 it.each(['RESOLVED','SUPERSEDED'] as const)('fails closed on candidate generation against a %s gap without invoking the generator',async(status)=>{ const {service,repository}=setup(); repository.findGap.mockResolvedValue({...gap,status}); const generator={generate:jest.fn()}; await expect(service.generateValidated(user,'token',gapId,generator as never)).rejects.toBeInstanceOf(BadRequestException); expect(generator.generate).not.toHaveBeenCalled(); expect(repository.createCandidate).not.toHaveBeenCalled(); });
 it('still generates validated candidates against an OPEN gap after the lifecycle widening',async()=>{ const {service,repository}=setup(); const generator:QuestionCandidateGenerator={generate:jest.fn().mockResolvedValue([proposal])}; await expect(service.generateValidated(user,'token',gapId,generator)).resolves.toHaveLength(1); expect(repository.createCandidate).toHaveBeenCalledTimes(1); });
});
