import { CorrelationService } from './correlation.service';
import { RequestCorrelationMiddleware } from './request-correlation.middleware';
import { TelemetryService } from './telemetry.service';
import { sanitizeSentryEvent,sentryOptions } from './sentry';
import { OpenAIModelRouter } from '../model-router/providers/openai/openai-model-router';
import { ClaudeModelRouter } from '../model-router/providers/anthropic/claude-model-router';
import { resolveOpenAIModel,resolveAnthropicModel } from '../model-router/model-profile.registry';
import type { ModelRouterRequest } from '../model-router/model-router.types';
import { hasExplicitMetricEndpoint,hasExplicitTraceEndpoint,initializeTelemetry,PrivacySafeSpanExporter,sanitizeAutomaticHttpSpan,sanitizeHttpSpanAttributes } from './instrumentation';
import { SpanKind,SpanStatusCode,type SpanContext } from '@opentelemetry/api';
import type { ReadableSpan,SpanExporter } from '@opentelemetry/sdk-trace-base';

const request:ModelRouterRequest={task:'CONVERSATIONAL_RESPONSE',path:'FAST',complexity:'LOW',behavioralGuidance:'secret prompt',context:[{role:'USER',content:'private message'}],locale:'und',modality:'TEXT',latencyBudgetMs:3000,costBudget:'LOW',safetyLevel:'STANDARD'};
describe('Correlation and telemetry foundation v1',()=>{
 it('generates a server request UUID, ignores inbound identity, and returns it',()=>{const c=new CorrelationService(),headers:Record<string,string>={};new RequestCorrelationMiddleware(c).use({headers:{'x-request-id':'attacker'}} as never,{setHeader:(k:string,v:string)=>headers[k]=v},()=>{expect(c.current()?.request_id).toMatch(/^[0-9a-f-]{36}$/);});expect(headers['x-request-id']).toMatch(/^[0-9a-f-]{36}$/);expect(headers['x-request-id']).not.toBe('attacker');});
 it('isolates concurrent scopes and preserves context through await',async()=>{const c=new CorrelationService();const run=(delay:number)=>c.runRequest(async()=>{const id=c.current()!.request_id;await new Promise(r=>setTimeout(r,delay));expect(c.current()!.request_id).toBe(id);return id;});const ids=await Promise.all([run(5),run(1)]);expect(ids[0]).not.toBe(ids[1]);});
 it('binds canonical IDs once and nests orchestration, engine, and provider IDs',()=>{const c=new CorrelationService();c.runRequest(()=>{c.bindCanonical('session','turn');expect(()=>c.bindCanonical('other')).toThrow('CORRELATION_ID_CONFLICT');c.withOrchestration(()=>{const orchestration=c.current()!.orchestration_id;expect(orchestration).toBeTruthy();c.withEngine(()=>c.withProvider(()=>expect(c.current()).toMatchObject({session_id:'session',turn_id:'turn',orchestration_id:orchestration,engine_call_id:expect.any(String),provider_call_id:expect.any(String)})));});});});
 it('returns an immutable copy rather than the live correlation store',()=>{const c=new CorrelationService();c.runRequest(()=>{const snapshot=c.current()!;expect(Object.isFrozen(snapshot)).toBe(true);expect(()=>{(snapshot as any).session_id='attacker';}).toThrow();expect(c.current()?.session_id).toBeUndefined();});});
 it('sanitizes every Sentry raw payload surface, raw path, and stack runtime data',()=>{
  const sentinel='SENTINEL_SECRET_9f21';
  const event:any=sanitizeSentryEvent({
   message:sentinel,transaction:`GET /${sentinel}`,transaction_info:{source:sentinel},logentry:{message:sentinel},
   request:{method:'POST',data:{content:sentinel},query_string:`token=${sentinel}`,url:`/sessions/${sentinel}?token=${sentinel}`,cookies:sentinel,headers:{authorization:sentinel}},
   user:{id:sentinel},extra:{raw:sentinel},contexts:{provider:{body:sentinel}},breadcrumbs:[{data:{secret:sentinel}}],
   exception:{values:[{type:'ProviderError',value:sentinel,stacktrace:{frames:[{filename:'safe.ts',function:'handler',lineno:7,vars:{token:sentinel},pre_context:[sentinel],context_line:sentinel,post_context:[sentinel]}]}}]},
  });
  expect(JSON.stringify(event)).not.toContain(sentinel);expect(event.request).toEqual({method:'POST'});expect(event.exception.values[0].stacktrace.frames[0]).toEqual({filename:'safe.ts',function:'handler',lineno:7});expect(sentryOptions).toMatchObject({enabled:false,tracesSampleRate:0,skipOpenTelemetrySetup:true,sendDefaultPii:false});expect(sentryOptions.beforeBreadcrumb({category:'http',data:{secret:sentinel}})).toBeNull();
 });
 it('exports only method, normalized route template, and status from automatic HTTP metadata',()=>{const sentinel='SECRET_QUERY',raw=`/sessions/SECRET_SESSION/turns/SECRET_TURN?token=${sentinel}`;const attributes=sanitizeHttpSpanAttributes({'url.full':`https://host${raw}`,'url.path':raw,'url.query':`token=${sentinel}`,'http.target':raw,'http.request.header.authorization':sentinel,'client.address':'203.0.113.1','server.address':'host','user_agent.original':sentinel,'http.request.method':'GET','http.route':'/sessions/:sessionId/turns/:turnId','http.response.status_code':200});expect(attributes).toEqual({'http.request.method':'GET','http.route':'/sessions/:sessionId/turns/:turnId','http.response.status_code':200});expect(JSON.stringify(attributes)).not.toContain(sentinel);});
 it('preserves the complete ReadableSpan contract without mutating the original while sanitizing export',()=>{const secret='SECRET_SESSION',context:SpanContext={traceId:'1'.repeat(32),spanId:'2'.repeat(16),traceFlags:1};class PrototypeSpan{spanContext(){return context;}}const original=Object.assign(new PrototypeSpan(),{name:`GET /sessions/${secret}`,kind:SpanKind.SERVER,parentSpanContext:context,startTime:[1,2],endTime:[3,4],status:{code:SpanStatusCode.ERROR,description:secret},attributes:{'http.request.method':'GET','http.route':'/sessions/:sessionId','url.path':`/sessions/${secret}`},links:[{context,attributes:{safe:'yes'}}],events:[{name:'exception',time:[2,3],attributes:{'exception.message':secret}}],duration:[2,2],ended:true,resource:{attributes:{'service.name':'test'}},instrumentationScope:{name:'@opentelemetry/instrumentation-http',version:'1'},droppedAttributesCount:1,droppedEventsCount:2,droppedLinksCount:3})as unknown as ReadableSpan;let received:ReadableSpan|undefined;const delegate:SpanExporter={export:(spans,callback)=>{received=spans[0];expect(received.spanContext()).toBe(context);callback({code:0});},shutdown:async()=>undefined};new PrivacySafeSpanExporter(delegate).export([original],()=>undefined);expect(received).toMatchObject({name:'GET /sessions/:sessionId',parentSpanContext:context,startTime:[1,2],endTime:[3,4],status:{code:SpanStatusCode.ERROR},events:[],links:original.links,duration:[2,2],ended:true,resource:original.resource,instrumentationScope:original.instrumentationScope,droppedAttributesCount:1,droppedEventsCount:2,droppedLinksCount:3});expect(JSON.stringify(received)).not.toContain(secret);expect(original.name).toContain(secret);expect(original.events).toHaveLength(1);});
 it('normalizes unsafe automatic span names and strips events and status descriptions',()=>{const secret='SECRET_TURN';const span={name:`GET /turns/${secret}`,kind:SpanKind.SERVER,spanContext:()=>({traceId:'1'.repeat(32),spanId:'2'.repeat(16),traceFlags:1}),startTime:[0,0],endTime:[0,1],status:{code:SpanStatusCode.ERROR,description:secret},attributes:{'http.request.method':'GET','url.path':`/turns/${secret}`},links:[],events:[{name:'exception',time:[0,0],attributes:{'exception.stacktrace':secret}}],duration:[0,1],ended:true,resource:{},instrumentationScope:{name:'@opentelemetry/instrumentation-express'},droppedAttributesCount:0,droppedEventsCount:0,droppedLinksCount:0}as unknown as ReadableSpan;const safe=sanitizeAutomaticHttpSpan(span);expect(safe.name).toBe('GET request');expect(safe.events).toEqual([]);expect(safe.status).toEqual({code:SpanStatusCode.ERROR});expect(JSON.stringify(safe)).not.toContain(secret);});
 it('disables telemetry when exporter or SDK bootstrap factories throw instead of throwing at module load',()=>{const throwing=()=>{throw new Error('bootstrap failed');},factories={createTraceExporter:throwing,createMetricExporter:throwing,createMetricReader:throwing,createSdk:throwing}as never;expect(()=>initializeTelemetry({NODE_ENV:'production',OTEL_EXPORTER_OTLP_ENDPOINT:'http://unused'},factories)).not.toThrow();expect(initializeTelemetry({NODE_ENV:'production',OTEL_EXPORTER_OTLP_ENDPOINT:'http://unused'},factories)).toBeUndefined();expect(initializeTelemetry({NODE_ENV:'production'},factories)).toBeUndefined();});
 it('recognizes generic and signal-specific OTLP endpoints without constructing exporters in tests',()=>{expect(hasExplicitTraceEndpoint({OTEL_EXPORTER_OTLP_ENDPOINT:'http://collector:4318'})).toBe(true);expect(hasExplicitMetricEndpoint({OTEL_EXPORTER_OTLP_ENDPOINT:'http://collector:4318'})).toBe(true);expect(hasExplicitTraceEndpoint({OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:'http://collector/custom-traces'})).toBe(true);expect(hasExplicitMetricEndpoint({OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:'http://collector/custom-metrics'})).toBe(true);expect(hasExplicitTraceEndpoint({})).toBe(false);expect(hasExplicitMetricEndpoint({})).toBe(false);});
 it('keeps successful and failing work authoritative when every telemetry primitive throws',async()=>{const c=new CorrelationService(),t=new TelemetryService(c),success=jest.fn().mockResolvedValue('ok'),original=new Error('original provider failure'),failure=jest.fn().mockRejectedValue(original);(t as any).tracer={startActiveSpan:(_n:string,_o:any,callback:any)=>callback({setAttribute:()=>{throw new Error('attribute');},setStatus:()=>{throw new Error('status');},end:()=>{throw new Error('end');}})};for(const key of ['providerCalls','providerErrors','providerDuration','inputTokens','outputTokens'])(t as any)[key]={add:()=>{throw new Error('metric');},record:()=>{throw new Error('metric');}};await expect(c.runRequest(()=>t.withProvider('openai','model','FAST',1,success,()=>{throw new Error('usage');}))).resolves.toBe('ok');await expect(c.runRequest(()=>t.withProvider('openai','model','FAST',1,failure))).rejects.toBe(original);expect(success).toHaveBeenCalledTimes(1);expect(failure).toHaveBeenCalledTimes(1);});
 it('executes work once when span creation itself fails',async()=>{const c=new CorrelationService(),t=new TelemetryService(c),work=jest.fn().mockResolvedValue(42);(t as any).tracer={startActiveSpan:()=>{throw new Error('tracer unavailable');}};await expect(c.runRequest(()=>t.withEngine('engine','FAST',work))).resolves.toBe(42);expect(work).toHaveBeenCalledTimes(1);});
 it('wraps OpenAI with a provider ID upstream but never sends correlation IDs in payload or headers',async()=>{const c=new CorrelationService(),t=new TelemetryService(c);let seen:any;const create=jest.fn().mockImplementation(async(body:any,options:any)=>{seen=c.current();expect(JSON.stringify({body,options})).not.toMatch(/request_id|provider_call_id|engine_call_id/);return{output_text:'ok',usage:{input_tokens:2,output_tokens:1}};});const router=new OpenAIModelRouter({apiKey:'x',resolveModel:resolveOpenAIModel,maxOutputTokens:10,timeoutMs:3000,maxRetries:0},{responses:{create}},t);await c.runRequest(()=>c.withOrchestration(()=>router.generate(request)));expect(seen.provider_call_id).toBeTruthy();expect(create).toHaveBeenCalledTimes(1);});
 it('wraps Anthropic consistently and uses only returned token usage',async()=>{const c=new CorrelationService(),t=new TelemetryService(c);let seen:any;const create=jest.fn().mockImplementation(async()=>{seen=c.current();return{content:[{type:'text',text:'ok'}],usage:{input_tokens:3,output_tokens:2}};});const router=new ClaudeModelRouter({apiKey:'x',resolveModel:resolveAnthropicModel,maxOutputTokens:10,timeoutMs:3000,maxRetries:0},{messages:{create}},t);await c.runRequest(()=>c.withOrchestration(()=>router.generate(request)));expect(seen.provider_call_id).toBeTruthy();expect(create).toHaveBeenCalledTimes(1);});
 it('keeps telemetry attributes bounded and never needs content payloads',async()=>{const c=new CorrelationService(),t=new TelemetryService(c);await expect(c.runRequest(()=>t.withEngine('context_builder','FAST',async()=>{expect(JSON.stringify(c.current())).not.toContain('private message');return 42;}))).resolves.toBe(42);});
 it('records eligibility with low-cardinality metadata only',()=>{const c=new CorrelationService(),t=new TelemetryService(c),add=jest.fn();(t as any).hypothesisEligibilityOutcomes={add};t.recordHypothesisGenerationEligibility('eligible','FAST');expect(add).toHaveBeenCalledWith(1,{outcome:'eligible',processing_path:'FAST',contract_version:'1'});expect(JSON.stringify(add.mock.calls)).not.toMatch(/user|content|evidence|memory|session|turn|provider/i);});
 it('records intent extraction with low-cardinality outcomes only',()=>{const c=new CorrelationService(),t=new TelemetryService(c),add=jest.fn();(t as any).hypothesisIntentExtractionOutcomes={add};t.recordHypothesisIntentExtraction('authority_rejected','DEEP');expect(add).toHaveBeenCalledWith(1,{outcome:'authority_rejected',processing_path:'DEEP',contract_version:'1'});expect(JSON.stringify(add.mock.calls)).not.toMatch(/user|content|evidence|memory|session|turn|provider_error/i);});
 it('records request assembly without request contents or identifiers',()=>{const c=new CorrelationService(),t=new TelemetryService(c),add=jest.fn();(t as any).hypothesisGenerationRequestAssemblyOutcomes={add};t.recordHypothesisGenerationRequestAssembly('ready','FAST');expect(add).toHaveBeenCalledWith(1,{outcome:'ready',processing_path:'FAST',contract_version:'1'});expect(JSON.stringify(add.mock.calls)).not.toMatch(/problem|evidence|scope|session|turn|user|request_json/i);});
 it('records Controlled Generation using bounded outcomes only',()=>{const c=new CorrelationService(),t=new TelemetryService(c),add=jest.fn();(t as any).controlledHypothesisGenerationOutcomes={add};t.recordControlledHypothesisGeneration('accepted_nonzero','FAST');expect(add).toHaveBeenCalledWith(1,{outcome:'accepted_nonzero',processing_path:'FAST',contract_version:'1'});expect(JSON.stringify(add.mock.calls)).not.toMatch(/problem|evidence|hypothesis|session|turn|user|provider_error|request_json/i);});
});
