import { Injectable } from '@nestjs/common';
import { metrics,SpanStatusCode,trace,type Attributes,type Span,type Tracer } from '@opentelemetry/api';
import { CorrelationService } from './correlation.service';

type Usage={inputTokens:number;outputTokens:number};
type Instrument={add?:(value:number,attributes?:Attributes)=>void;record?:(value:number,attributes?:Attributes)=>void};

@Injectable()
export class TelemetryService{
 private readonly tracer:Tracer;private readonly engineDuration:Instrument;private readonly providerDuration:Instrument;private readonly providerCalls:Instrument;private readonly providerErrors:Instrument;private readonly inputTokens:Instrument;private readonly outputTokens:Instrument;private readonly turnOutcomes:Instrument;private readonly publisherOperations:Instrument;
 constructor(private readonly correlation:CorrelationService){
  this.tracer=this.safe(()=>trace.getTracer('qandeel-api'),{startActiveSpan:(_name:string,_options:unknown,callback:(span:Span)=>unknown)=>callback(this.noopSpan())}as unknown as Tracer);
  const meter=this.safe(()=>metrics.getMeter('qandeel-api'),undefined);
  this.engineDuration=this.safe<Instrument|undefined>(()=>meter?.createHistogram('qandeel.engine.duration',{unit:'ms'}),undefined)??{};this.providerDuration=this.safe<Instrument|undefined>(()=>meter?.createHistogram('qandeel.provider.duration',{unit:'ms'}),undefined)??{};
  this.providerCalls=this.safe<Instrument|undefined>(()=>meter?.createCounter('qandeel.provider.calls'),undefined)??{};this.providerErrors=this.safe<Instrument|undefined>(()=>meter?.createCounter('qandeel.provider.errors'),undefined)??{};this.inputTokens=this.safe<Instrument|undefined>(()=>meter?.createCounter('qandeel.provider.input_tokens'),undefined)??{};this.outputTokens=this.safe<Instrument|undefined>(()=>meter?.createCounter('qandeel.provider.output_tokens'),undefined)??{};this.turnOutcomes=this.safe<Instrument|undefined>(()=>meter?.createCounter('qandeel.turn.outcomes'),undefined)??{};this.publisherOperations=this.safe<Instrument|undefined>(()=>meter?.createCounter('qandeel.runtime_event_publisher.operations'),undefined)??{};
 }
 withEngine<T>(engine:string,path:string|undefined,work:()=>Promise<T>|T):Promise<T>{return this.scoped(()=>this.correlation.withEngine(()=>this.span('qandeel.engine',{engine,processing_path:path},work)),work);}
 withProvider<T>(provider:string,model:string,path:string,timeout:number,work:()=>Promise<T>,usage?:(value:T)=>Usage|undefined):Promise<T>{return this.scoped(()=>this.correlation.withProvider(()=>this.providerSpan(provider,model,path,timeout,work,usage)),work);}
 recordTurnOutcome(outcome:string,path?:string):void{this.safeVoid(()=>this.turnOutcomes.add?.(1,{outcome,...(path?{processing_path:path}:{})}));}
 recordPublisherOperation(operation:'connect'|'claim'|'publish'|'ack'|'retry'|'quarantine'|'close',outcome:'success'|'failure'|'conflict'):void{this.safeVoid(()=>this.publisherOperations.add?.(1,{operation,outcome,transport:'redis_streams'}));}
 private async span<T>(name:string,dimensions:Record<string,string|undefined>,work:()=>Promise<T>|T):Promise<T>{const start=this.now();return this.traceOnce(name,this.spanAttributes(dimensions),work,(span,outcome)=>{this.safeVoid(()=>span.setAttribute('qandeel.outcome',outcome));if(outcome==='error')this.safeVoid(()=>span.setStatus({code:SpanStatusCode.ERROR}));this.safeVoid(()=>this.engineDuration.record?.(this.now()-start,this.metricAttributes(dimensions)));});}
 private async providerSpan<T>(provider:string,model:string,path:string,timeout:number,work:()=>Promise<T>,readUsage?:(value:T)=>Usage|undefined):Promise<T>{const dimensions={provider,model,processing_path:path},start=this.now();this.safeVoid(()=>this.providerCalls.add?.(1,dimensions));try{return await this.traceOnce('qandeel.provider',this.spanAttributes({...dimensions,timeout:String(timeout)}),work,(span,outcome,value)=>{this.safeVoid(()=>span.setAttribute('qandeel.outcome',outcome));if(outcome==='error'){this.safeVoid(()=>span.setStatus({code:SpanStatusCode.ERROR}));this.safeVoid(()=>this.providerErrors.add?.(1,{...dimensions,outcome:'error'}));}else{const usage=this.safe(()=>readUsage?.(value as T),undefined);if(usage){this.safeVoid(()=>this.inputTokens.add?.(usage.inputTokens,dimensions));this.safeVoid(()=>this.outputTokens.add?.(usage.outputTokens,dimensions));}}});}finally{this.safeVoid(()=>this.providerDuration.record?.(this.now()-start,dimensions));}}
 private async traceOnce<T>(name:string,attributes:Attributes,work:()=>Promise<T>|T,finish:(span:Span,outcome:'success'|'error',value?:T)=>void):Promise<T>{let workPromise:Promise<T>|undefined;const runOnce=()=>workPromise??=Promise.resolve().then(work);try{return await this.tracer.startActiveSpan(name,{attributes},async span=>{try{const value=await runOnce();this.safeVoid(()=>finish(span,'success',value));return value;}catch(error){this.safeVoid(()=>finish(span,'error'));throw error;}finally{this.safeVoid(()=>span.end());}});}catch(error){if(workPromise)return workPromise;return runOnce();}}
 private scoped<T>(telemetryWork:()=>Promise<T>,work:()=>Promise<T>|T):Promise<T>{let workPromise:Promise<T>|undefined;const once=()=>workPromise??=Promise.resolve().then(work);try{const result=telemetryWork();return Promise.resolve(result).catch(error=>workPromise?workPromise:Promise.reject(error));}catch{return once();}}
 private spanAttributes(extra:Record<string,string|undefined>):Attributes{return this.safe(()=>{const current=this.correlation.current(),result:Attributes={};if(current)for(const[key,value]of Object.entries(current))if(value)result[`qandeel.${key}`]=value;for(const[key,value]of Object.entries(extra))if(value!==undefined)result[`qandeel.${key}`]=value;return result;},{});}
 private metricAttributes(values:Record<string,string|undefined>):Attributes{const allowed=new Set(['engine','provider','model','processing_path','outcome']),result:Attributes={};for(const[key,value]of Object.entries(values))if(allowed.has(key)&&value!==undefined)result[key]=value;return result;}
 private now():number{return this.safe(()=>performance.now(),0);}private safe<T>(operation:()=>T,fallback:T):T{try{return operation();}catch{return fallback;}}private safeVoid(operation:()=>void):void{try{operation();}catch{}}
 private noopSpan():Span{return{setAttribute:()=>this.noopSpan(),setStatus:()=>this.noopSpan(),end:()=>undefined}as unknown as Span;}
}
